# FlashRAG Naive RAG — Evaluation on PubMed Summary QA

Evaluates [FlashRAG](https://github.com/RUC-NLPIR/FlashRAG) (WWW 2025) in **Naive RAG** mode on the first 50 questions  
of `pubmed_summary_qa.csv`, using the same metrics as NeuroRAG and MedRAG.

**Pipeline:**
1. **Corpus** — PubMed abstracts fetched via Entrez API (top-20 per question, deduplicated)
2. **Retriever** — BM25 (`bm25s` backend, no Java/GPU required)
3. **Generator** — `gpt-4o-mini` via OpenRouter (single call, no fusing or reranking)

**Why this is a fair baseline:** FlashRAG Naive RAG is a single-stage pipeline published in a  
peer-reviewed academic paper (WWW 2025). It lacks NeuroRAG's multi-source retrieval,  
multi-model fusing, LLM reranking, and contextual compression.

## 1. Install dependencies

In [1]:
!pip install wavedrom --use-pep517
!pip install flashrag-dev --pre
!pip install bm25s

Requirement already satisfied: wavedrom in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (2.0.3.post3)
Requirement already satisfied: svgwrite in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from wavedrom) (1.4.3)
Requirement already satisfied: six in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from wavedrom) (1.17.0)
Requirement already satisfied: pyyaml in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from wavedrom) (6.0.3)
Requirement already satisfied: flashrag-dev in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (0.3.0.dev20260410)
Requirement already satisfied: datasets in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from flashrag-dev) (3.6.0)
Requirement already satisfied: base58 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from flashrag-dev) (2.1.1)
Requirement already satisfied: nltk in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from flashrag-dev) (3.9.4)
Requirement already satisfied: numpy in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from flashrag-dev) (2.3.5)
Requirement already satisfied: langid in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from flashrag-dev) (1.1.6)
Requirement already satisfied: openai in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from flashrag-dev) (2.14.0)
Requirement already satisfied: peft in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from flashrag-dev) (0.19.1)
Requirement already satisfied: PyYAML in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from flashrag-dev) (6.0.3)
Requirement already satisfied: rank_bm25 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from flashrag-dev) (0.2.2)
Requirement already satisfied: rouge in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from flashrag-dev) (1.0.1)
Requirement already satisfied: spacy in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from flashrag-dev) (3.8.14)
Requirement already satisfied: tiktoken in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from flashrag-dev) (0.12.0)
Requirement already satisfied: torch in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from flashrag-dev) (2.11.0)
Requirement already satisfied: tqdm in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from flashrag-dev) (4.67.3)
Requirement already satisfied: transformers>=4.40.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from flashrag-dev) (5.6.2)
Requirement already satisfied: bm25s==0.2.1 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from bm25s[core]==0.2.1->flashrag-dev) (0.2.1)
Requirement already satisfied: fschat in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from flashrag-dev) (0.2.36)
Requirement already satisfied: streamlit in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from flashrag-dev) (1.40.1)
Requirement already satisfied: chonkie<1.1.0,>=1.0.2 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from flashrag-dev) (1.0.10)
Requirement already satisfied: gradio>=5.0.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from flashrag-dev) (6.14.0)
Requirement already satisfied: rouge-chinese in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from flashrag-dev) (1.0.3)
Requirement already satisfied: jieba in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from flashrag-dev) (0.42.1)
Requirement already satisfied: scipy in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from bm25s==0.2.1->bm25s[core]==0.2.1->flashrag-dev) (1.16.3)
Requirement already satisfied: orjson in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from bm25s[core]==0.2.1->flashrag-dev) (3.11.5)
Requirement already satisfied: PyStemmer in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from bm25s[core]==0.2.1->flashrag-dev) (3.0.0)
Requirement already satisfied: numba in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from bm25s[core]==0.2.1->flashrag-dev) (0.63.1)
Requirement already satisfied: tokenizers>=0.16.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from chonkie<1.1.0,>=1.0.2->flashrag-dev) (0.22.2)
Requirement already satisfied: anyio<5.0,>=3.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from gradio>=5.0.0->flashrag-dev) (3.7.1)
Requirement already satisfied: brotli>=1.1.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from gradio>=5.0.0->flashrag-dev) (1.2.0)
Requirement already satisfied: fastapi<1.0,>=0.115.2 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from gradio>=5.0.0->flashrag-dev) (0.135.3)
Requirement already satisfied: gradio-client==2.5.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from gradio>=5.0.0->flashrag-dev) (2.5.0)
Requirement already satisfied: groovy~=0.1 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from gradio>=5.0.0->flashrag-dev) (0.1.2)
Requirement already satisfied: hf-gradio<1.0,>=0.4.1 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from gradio>=5.0.0->flashrag-dev) (0.4.1)
Requirement already satisfied: httpx<1.0,>=0.24.1 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from gradio>=5.0.0->flashrag-dev) (0.28.1)
Requirement already satisfied: huggingface-hub<2.0,>=0.33.5 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from gradio>=5.0.0->flashrag-dev) (1.12.0)
Requirement already satisfied: jinja2<4.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from gradio>=5.0.0->flashrag-dev) (3.1.6)
Requirement already satisfied: markupsafe<4.0,>=2.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from gradio>=5.0.0->flashrag-dev) (3.0.3)
Requirement already satisfied: packaging in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from gradio>=5.0.0->flashrag-dev) (24.2)
Requirement already satisfied: pandas<4.0,>=1.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from gradio>=5.0.0->flashrag-dev) (2.3.3)
Requirement already satisfied: pillow<13.0,>=8.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from gradio>=5.0.0->flashrag-dev) (11.3.0)
Requirement already satisfied: pydantic<=3.0,>=2.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from gradio>=5.0.0->flashrag-dev) (2.12.5)
Requirement already satisfied: pydub<1.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from gradio>=5.0.0->flashrag-dev) (0.25.1)
Requirement already satisfied: python-multipart<1.0,>=0.0.18 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from gradio>=5.0.0->flashrag-dev) (0.0.26)
Requirement already satisfied: pytz>=2017.2 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from gradio>=5.0.0->flashrag-dev) (2025.2)
Requirement already satisfied: safehttpx<0.2.0,>=0.1.7 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from gradio>=5.0.0->flashrag-dev) (0.1.7)
Requirement already satisfied: semantic-version~=2.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from gradio>=5.0.0->flashrag-dev) (2.10.0)
Requirement already satisfied: starlette<2.0,>=0.40.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from gradio>=5.0.0->flashrag-dev) (1.0.0)
Requirement already satisfied: tomlkit<0.15.0,>=0.12.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from gradio>=5.0.0->flashrag-dev) (0.13.3)
Requirement already satisfied: typer<1.0,>=0.12 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from gradio>=5.0.0->flashrag-dev) (0.25.1)
Requirement already satisfied: typing-extensions~=4.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from gradio>=5.0.0->flashrag-dev) (4.15.0)
Requirement already satisfied: uvicorn>=0.14.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from gradio>=5.0.0->flashrag-dev) (0.44.0)
Requirement already satisfied: fsspec in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from gradio-client==2.5.0->gradio>=5.0.0->flashrag-dev) (2025.3.0)
Requirement already satisfied: regex>=2025.10.22 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from transformers>=4.40.0->flashrag-dev) (2025.11.3)
Requirement already satisfied: safetensors>=0.4.3 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from transformers>=4.40.0->flashrag-dev) (0.7.0)
Requirement already satisfied: filelock in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from datasets->flashrag-dev) (3.20.2)
Requirement already satisfied: pyarrow>=15.0.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from datasets->flashrag-dev) (22.0.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from datasets->flashrag-dev) (0.3.8)
Requirement already satisfied: requests>=2.32.2 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from datasets->flashrag-dev) (2.33.1)
Requirement already satisfied: xxhash in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from datasets->flashrag-dev) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from datasets->flashrag-dev) (0.70.16)
Requirement already satisfied: aiohttp in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from fschat->flashrag-dev) (3.13.5)
Requirement already satisfied: markdown2[all] in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from fschat->flashrag-dev) (2.5.5)
Requirement already satisfied: nh3 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from fschat->flashrag-dev) (0.3.5)
Requirement already satisfied: prompt-toolkit>=3.0.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from fschat->flashrag-dev) (3.0.52)
Requirement already satisfied: rich>=10.0.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from fschat->flashrag-dev) (13.9.4)
Requirement already satisfied: shortuuid in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from fschat->flashrag-dev) (1.0.13)
Requirement already satisfied: click in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from nltk->flashrag-dev) (8.3.1)
Requirement already satisfied: joblib in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from nltk->flashrag-dev) (1.5.3)
Requirement already satisfied: distro<2,>=1.7.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from openai->flashrag-dev) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from openai->flashrag-dev) (0.12.0)
Requirement already satisfied: sniffio in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from openai->flashrag-dev) (1.3.1)
Requirement already satisfied: psutil in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from peft->flashrag-dev) (6.1.1)
Requirement already satisfied: accelerate>=0.21.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from peft->flashrag-dev) (1.13.0)
Requirement already satisfied: setuptools<82 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from torch->flashrag-dev) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from torch->flashrag-dev) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from torch->flashrag-dev) (3.6.1)
Requirement already satisfied: six in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from rouge->flashrag-dev) (1.17.0)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from spacy->flashrag-dev) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from spacy->flashrag-dev) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from spacy->flashrag-dev) (1.0.10)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from spacy->flashrag-dev) (2.0.8)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from spacy->flashrag-dev) (3.0.9)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from spacy->flashrag-dev) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from spacy->flashrag-dev) (1.1.2)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from spacy->flashrag-dev) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from spacy->flashrag-dev) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from spacy->flashrag-dev) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from spacy->flashrag-dev) (1.3.3)
Requirement already satisfied: altair<6,>=4.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from streamlit->flashrag-dev) (5.5.0)
Requirement already satisfied: blinker<2,>=1.0.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from streamlit->flashrag-dev) (1.9.0)
Requirement already satisfied: cachetools<6,>=4.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from streamlit->flashrag-dev) (5.5.2)
Requirement already satisfied: protobuf<6,>=3.20 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from streamlit->flashrag-dev) (5.29.6)
Requirement already satisfied: tenacity<10,>=8.1.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from streamlit->flashrag-dev) (9.1.2)
Requirement already satisfied: toml<2,>=0.10.1 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from streamlit->flashrag-dev) (0.10.2)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from streamlit->flashrag-dev) (3.1.46)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from streamlit->flashrag-dev) (0.9.1)
Requirement already satisfied: tornado<7,>=6.0.3 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from streamlit->flashrag-dev) (6.5.4)
Requirement already satisfied: jsonschema>=3.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from altair<6,>=4.0->streamlit->flashrag-dev) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from altair<6,>=4.0->streamlit->flashrag-dev) (2.15.0)
Requirement already satisfied: idna>=2.8 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from anyio<5.0,>=3.0->gradio>=5.0.0->flashrag-dev) (3.11)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from fastapi<1.0,>=0.115.2->gradio>=5.0.0->flashrag-dev) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from fastapi<1.0,>=0.115.2->gradio>=5.0.0->flashrag-dev) (0.0.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from aiohttp->fschat->flashrag-dev) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from aiohttp->fschat->flashrag-dev) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from aiohttp->fschat->flashrag-dev) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from aiohttp->fschat->flashrag-dev) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from aiohttp->fschat->flashrag-dev) (6.7.0)
Requirement already satisfied: propcache>=0.2.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from aiohttp->fschat->flashrag-dev) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from aiohttp->fschat->flashrag-dev) (1.22.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit->flashrag-dev) (4.0.12)
Requirement already satisfied: certifi in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from httpx<1.0,>=0.24.1->gradio>=5.0.0->flashrag-dev) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from httpx<1.0,>=0.24.1->gradio>=5.0.0->flashrag-dev) (1.0.9)
Requirement already satisfied: h11>=0.16 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from httpcore==1.*->httpx<1.0,>=0.24.1->gradio>=5.0.0->flashrag-dev) (0.16.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from huggingface-hub<2.0,>=0.33.5->gradio>=5.0.0->flashrag-dev) (1.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from pandas<4.0,>=1.0->gradio>=5.0.0->flashrag-dev) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from pandas<4.0,>=1.0->gradio>=5.0.0->flashrag-dev) (2025.3)
Requirement already satisfied: wcwidth in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from prompt-toolkit>=3.0.0->fschat->flashrag-dev) (0.2.14)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from pydantic<=3.0,>=2.0->gradio>=5.0.0->flashrag-dev) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from pydantic<=3.0,>=2.0->gradio>=5.0.0->flashrag-dev) (2.41.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from requests>=2.32.2->datasets->flashrag-dev) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.26 in /opt/homebrew/Caskroom/miniconda/base/lib/python3.12/site-packages (from requests>=2.32.2->datasets->flashrag-dev) (2.3.0)

## 2. Imports

In [2]:
import sys

sys.path.append('..')
sys.path.append('../neurorag')

import os
import json
import time
import xml.etree.ElementTree as ET
from pathlib import Path

import httpx
import pandas as pd
import numpy as np
from tqdm import tqdm
from dotenv import load_dotenv
from getpass import getpass

from metrics import (
    embeddings_cosine_sim_metric,
    bleu_metric,
    rogue_l_metric,
    rogue_1_metric,
    factscore_metric,
    bert_score_metric,
)

import warnings
warnings.filterwarnings('ignore')

## 3. Environment variables

In [3]:
load_dotenv()

for key in ['OPENROUTER_API_KEY', 'ENTREZ_EMAIL']:
    if not os.getenv(key):
        os.environ[key] = getpass(key)

OPENROUTER_KEY = os.environ['OPENROUTER_API_KEY']
ENTREZ_EMAIL   = os.environ['ENTREZ_EMAIL']

ANSWER_STYLE = (
    'Answer in 2-3 sentences (30-50 words). '
    'State the key fact first, then supporting detail. '
    'Write like a PubMed abstract sentence.'
)

print('Environment ready.')

Environment ready.

## 4. Load dataset

In [4]:
N_QUESTIONS = 50
df = pd.read_csv('../datasets/pubmed_summary_qa.csv').head(N_QUESTIONS)
questions        = df['question'].tolist()
expected_answers = df['answer'].tolist()

print(f'Loaded {len(questions)} questions.')
df.head()

Loaded 50 questions.

,question,answer
0,Which brain region is involved in working memo...,The dorsolateral prefrontal cortex (DLPFC) is ...
1,Are other brain regions also involved in worki...,"Yes, other brain regions, such as the premotor..."
2,What is a visuomotor task?,A visuomotor task is a type of task that requi...
3,What brain regions are involved in visuomotor ...,The brain regions involved in visuomotor trans...
4,What is the role of the prefrontal cortex in v...,The prefrontal cortex is involved in the prepa...

## 5. Build PubMed corpus

Fetch the top-20 PubMed abstracts for each question, deduplicate, and save as a  
`corpus.jsonl` file in FlashRAG format: `{"id": "<pmid>", "contents": "<title + abstract>"}`.  
Results are cached so the cell can be re-run without extra API calls.

In [5]:
CORPUS_FILE = Path('flashrag_corpus.jsonl')
CORPUS_CACHE_FILE = Path('flashrag_corpus_cache.json')
TOP_K_CORPUS = 20  # abstracts per question

ENTREZ_SEARCH = 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi'
ENTREZ_FETCH  = 'https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi'


def _search_pmids(query: str, top_k: int) -> list[str]:
    r = httpx.get(ENTREZ_SEARCH, params={
        'db': 'pubmed', 'term': query, 'retmax': top_k,
        'retmode': 'json', 'email': ENTREZ_EMAIL,
    }, timeout=15)
    r.raise_for_status()
    return r.json().get('esearchresult', {}).get('idlist', [])


def _fetch_abstracts(pmids: list[str]) -> dict[str, str]:
    """Returns {pmid: 'Title: ... Abstract: ...'}"""
    if not pmids:
        return {}
    r = httpx.get(ENTREZ_FETCH, params={
        'db': 'pubmed', 'id': ','.join(pmids),
        'retmode': 'xml', 'rettype': 'abstract', 'email': ENTREZ_EMAIL,
    }, timeout=30)
    r.raise_for_status()
    root = ET.fromstring(r.text)
    result = {}
    for article in root.findall('.//PubmedArticle'):
        pmid_el = article.find('.//PMID')
        if pmid_el is None:
            continue
        pmid = pmid_el.text or ''
        title_el = article.find('.//ArticleTitle')
        title = (title_el.text or '').strip() if title_el is not None else ''
        abstract = ' '.join(
            (el.text or '').strip()
            for el in article.findall('.//AbstractText') if el.text
        )
        if abstract:
            result[pmid] = f'Title: {title}\nAbstract: {abstract}'
    return result


# Load previously fetched corpus cache
if CORPUS_CACHE_FILE.exists():
    with open(CORPUS_CACHE_FILE) as f:
        corpus_cache: dict[str, str] = json.load(f)  # {pmid: text}
else:
    corpus_cache = {}

print('Fetching PubMed abstracts...')
for question in tqdm(questions):
    try:
        pmids = _search_pmids(question, top_k=TOP_K_CORPUS)
        new_pmids = [p for p in pmids if p not in corpus_cache]
        if new_pmids:
            fetched = _fetch_abstracts(new_pmids)
            corpus_cache.update(fetched)
        time.sleep(0.35)  # PubMed rate limit: 3 req/s
    except Exception as e:
        print(f'  Warning: {e}')

# Persist
with open(CORPUS_CACHE_FILE, 'w') as f:
    json.dump(corpus_cache, f, ensure_ascii=False)

# Write FlashRAG corpus JSONL
with open(CORPUS_FILE, 'w') as f:
    for pmid, text in corpus_cache.items():
        f.write(json.dumps({'id': pmid, 'contents': text}) + '\n')

print(f'Corpus: {len(corpus_cache)} unique abstracts → {CORPUS_FILE}')

Fetching PubMed abstracts...

100%|██████████| 50/50 [00:49<00:00,  1.00it/s]

Corpus: 490 unique abstracts → flashrag_corpus.jsonl

## 6. Build BM25 index

Uses FlashRAG's `index_builder` with the `bm25s` backend (no Java or GPU required).

In [6]:
import subprocess

INDEX_DIR = Path('flashrag_index')
# The index_builder creates files inside a 'bm25/' subdirectory
_index_marker = INDEX_DIR / 'bm25' / 'params.index.json'

if not _index_marker.exists():
    print('Building BM25 index...')
    result = subprocess.run(
        [
            sys.executable, '-m', 'flashrag.retriever.index_builder',
            '--retrieval_method', 'bm25',
            '--corpus_path', str(CORPUS_FILE),
            '--bm25_backend', 'bm25s',
            '--save_dir', str(INDEX_DIR),
        ],
        capture_output=True, text=True,
    )
    if result.returncode != 0:
        print('STDERR:', result.stderr[-2000:])
        raise RuntimeError('Index build failed')
    print('Index built successfully.')
else:
    print(f'Index already exists at {_index_marker.parent.resolve()}')

Index already exists at /Users/vladimirskvortsov/Projects/neurorag/notebooks/flashrag_index/bm25

## 7. Prepare FlashRAG dataset

FlashRAG expects a `test.jsonl` file with fields `id`, `question`, and `golden_answers`.

In [7]:
DATA_DIR = Path('flashrag_data')
DATASET_NAME = 'pubmed_qa'

# FlashRAG expects: data_dir / dataset_name / split.jsonl
dataset_dir = DATA_DIR / DATASET_NAME
dataset_dir.mkdir(parents=True, exist_ok=True)

test_file = dataset_dir / 'test.jsonl'
with open(test_file, 'w') as f:
    for i, (q, a) in enumerate(zip(questions, expected_answers)):
        f.write(json.dumps({'id': str(i), 'question': q, 'golden_answers': [a]}) + '\n')

print(f'Wrote {len(questions)} questions to {test_file}')

Wrote 50 questions to flashrag_data/pubmed_qa/test.jsonl

## 8. Configure and run FlashRAG SequentialPipeline

**Naive RAG** = BM25 retrieval → single LLM call (no reranking, no fusing).

In [8]:
from flashrag.config import Config
from flashrag.utils import get_dataset
from flashrag.pipeline import SequentialPipeline
from flashrag.prompt import PromptTemplate

# Re-define paths here so this cell is self-contained
INDEX_DIR = Path('flashrag_index')
BM25_INDEX_DIR = INDEX_DIR / 'bm25'

# Sanity-check — fail fast with a clear message
if not (BM25_INDEX_DIR / 'params.index.json').exists():
    raise FileNotFoundError(
        f'BM25 index not found at {BM25_INDEX_DIR.resolve()}. '
        'Re-run cell 6 (Build BM25 index) first.'
    )

config_dict = {
    # Paths
    'data_dir':    str(DATA_DIR),
    'dataset_name': DATASET_NAME,
    'save_dir':    'flashrag_output/',
    'corpus_path': str(CORPUS_FILE.resolve()),
    'split': ['test'],

    # Retriever — BM25 (bm25s backend, files live in INDEX_DIR/bm25/)
    'retrieval_method': 'bm25',
    'bm25_backend':     'bm25s',
    'index_path':       str(BM25_INDEX_DIR.resolve()),
    'retrieval_topk':   10,
    'silent_retrieval': True,

    # Generator — OpenAI-compatible (-> OpenRouter)
    'framework':       'openai',
    'generator_model': 'openai/gpt-4.1',
    'openai_setting': {
        'api_key':  OPENROUTER_KEY,
        'base_url': 'https://openrouter.ai/api/v1',
    },
    'generation_params': {
        'max_tokens':   200,
        'temperature':  0,
    },
    'generator_max_input_len': 4096,

    # Evaluation — we compute our own metrics afterwards
    'metrics': [],
    'save_intermediate_data': True,
    'save_metric_score': False,
    'save_note': 'flashrag_naive',
}

config = Config(config_dict=config_dict)

# Custom prompt matching our ANSWER_STYLE
prompt_template = PromptTemplate(
    config,
    system_prompt=(
        f'You are a biomedical expert. OUTPUT RULE: {ANSWER_STYLE} '
        'Answer the question using only the provided documents. '
        'Be direct and factual - no preamble, no caveats.\n\n'
        'Documents:\n{reference}'
    ),
    user_prompt='Question: {question}\nAnswer:',
)

all_split = get_dataset(config)
test_data = all_split['test']

pipeline = SequentialPipeline(config, prompt_template=prompt_template)

print(f'Pipeline ready. Running on {len(test_data)} questions...')
output_dataset = pipeline.run(test_data, do_eval=False)
print('Done.')

Loading test dataset from: flashrag_data/pubmed_qa/test.jsonl...
Warning:  'Could not automatically map openai/gpt-4.1 to a tokeniser. Please use `tiktoken.get_encoding` to explicitly get the tokeniser you expect.'

Generating train split: 0 examples [00:00, ? examples/s]

Pipeline ready. Running on 50 questions...

Split strings:   0%|          | 0/50 [00:00<?, ?it/s]

OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.

Error:  'Could not automatically map openai/gpt-4.1 to a tokeniser. Please use `tiktoken.get_encoding` to explicitly get the tokeniser you expect.'
The input text length is greater than the maximum length (4483 > 4096) and has been truncated!
The input text length is greater than the maximum length (4402 > 4096) and has been truncated!
The input text length is greater than the maximum length (4225 > 4096) and has been truncated!
The input text length is greater than the maximum length (4172 > 4096) and has been truncated!
The input text length is greater than the maximum length (4546 > 4096) and has been truncated!
The input text length is greater than the maximum length (4113 > 4096) and has been truncated!
The input text length is greater than the maximum length (4568 > 4096) and has been truncated!
The input text length is greater than the maximum length (4297 > 4096) and has been truncated!
The input text length is greater than the maximum length (4172 > 4096) and has been truncated!
The input text length is greater than the maximum length (4113 > 4096) and has been truncated!
The input text length is greater than the maximum length (4225 > 4096) and has been truncated!
The input text length is greater than the maximum length (4522 > 4096) and has been truncated!
The input text length is greater than the maximum length (4295 > 4096) and has been truncated!
The input text length is greater than the maximum length (4982 > 4096) and has been truncated!
The input text length is greater than the maximum length (4982 > 4096) and has been truncated!
The input text length is greater than the maximum length (4168 > 4096) and has been truncated!
The input text length is greater than the maximum length (4138 > 4096) and has been truncated!
The input text length is greater than the maximum length (4222 > 4096) and has been truncated!
The input text length is greater than the maximum length (4113 > 4096) and has been truncated!
The input text length is greater than the maximum length (4113 > 4096) and has been truncated!

Generation process:   0%|          | 0/13 [00:00<?, ?it/s]

[{'role': 'system', 'content': "You are a biomedical expert. OUTPUT RULE: Answer in 2-3 sentences (30-50 words). State the key fact first, then supporting detail. Write like a PubMed abstract sentence. Answer the question using only the provided documents. Be direct and factual - no preamble, no caveats.\n\nDocuments:\nDoc 1(Title: Title: Linking the evolution of two prefrontal brain regions to social and foraging challenges in primates.) Abstract: The diversity of cognitive skills across primates remains both a fascinating and a controversial issue. Recent comparative studies provided conflicting results regarding the contribution of social vs ecological constraints to the evolution of cognition. Here, we used an interdisciplinary approach combining comparative cognitive neurosciences and behavioral ecology. Using brain imaging data from 16 primate species, we measured the size of two prefrontal brain regions, the frontal pole (FP) and the dorso-lateral prefrontal cortex (DLPFC), respectively, involved in metacognition and working memory, and examined their relation to a combination of socio-ecological variables. The size of these prefrontal regions, as well as the whole brain, was best explained by three variables: body mass, daily traveled distance (an index of ecological constraints), and population density (an index of social constraints). The strong influence of ecological constraints on FP and DLPFC volumes suggests that both metacognition and working memory are critical for foraging in primates. Interestingly, FP volume was much more sensitive to social constraints than DLPFC volume, in line with laboratory studies showing an implication of FP in complex social interactions. Thus, our data highlights the relative weight of social vs ecological constraints on the evolution of specific prefrontal brain regions and their associated cognitive operations in primates. Primates – such as lemurs, monkeys and humans – can perform a diverse range of cognitive skills, from memory to processing speech. But how did this diversity of cognitive skills evolve? To answer this question, scientists often compare the brain sizes of different species and measure how this relates to their social behaviors or ecology in the wild. But using the whole brain as a measure of global cognitive capacities seems crude in the light of modern cognitive neuroscience studies, which have shown that specific parts of the brain are responsible for certain cognitive skills. It is unclear how relevant the findings of cognitive neuroscience studies, which test animals in a laboratory, are to real life situations and evolution. To address this gap, Bouret et al. integrated methods from both behavioral ecology and cognitive neuroscience to examine the size of primate brain regions. The team studied brain images from 16 primate species, focusing on two regions that have been linked to specific cognitive functions in laboratory experiments. They examined the frontal pole, which is involved in metacognition (the ability to be aware of and assess one’s own thoughts), and the dorsolateral prefrontal cortex, which is involved in working memory (the ability to temporarily store information to solve a problem). Bouret et al. then compared the size of these regions to socio-ecological factors: how much each species performs complex social interactions and how hard it is to find food in the wild, by measuring their population density and daily travel distance, respectively. This revealed that the volume of the frontal pole is larger in species that experience more complex social interactions and in species that struggle to find food – two tasks thought to require metacognition. The dorsolateral prefrontal cortex, however, is only larger in species that have difficulty foraging, which might require a strong working memory to plan travel routes. These findings suggest that laboratory experiments linking cognitive skills to specific parts of the brain are reliable enough to predict the size of these regions across wild primates. The work of Bouret et al. also helps bridge the gap between cognitive neuroscience and behavioral ecology, and demonstrates how these two disciplines can be combined to investigate the evolution of cognition.\nDoc 2(Title: Title: Social media use and early adolescent brain structure: Findings from the Adolescent Brain Cognitive Development (ABCD) Study.) Abstract: Many adolescents initiate social media use during early adolescence, but the associations of early social media use with neurodevelopment have not been extensively studied. We utilized neuroimaging data from the U.S. Adolescent Brain Cognitive Development (ABCD) Study to investigate the association of social media use (hours per day) or social media addiction (Social Media Addiction Questionnaire) with brain morphology in early adolescence. We analyzed data from 7,614 participants with high-quality structural MRI and complete covariate data at Year 2 (2018-2020, ages 10-13). In addition to pre-defined cortical regions, we performed vertexwise analysis using the Fast and Efficient Mixed Effects Algorithm (FEMA), which is unbiased by arbitrary borders between atlas-based brain regions and provides higher spatial resolution. After adjusting for demographics, socioeconomic factors, genetic ancestry, non-social media screen time, and scanner features, higher average daily social media use was significantly associated with lower total cortical thickness and volume. Region-of-interest (ROI) and vertexwise analysis identified broad regions with lower cortical thickness across the prefrontal cortices, temporal lobe, occipital lobe, and parietal lobe associated with social media use and social media addiction, which overlap with key nodes of the default mode network, prefrontal executive control networks, and visual processing and attention networks. Social media addiction was not significantly associated with differences in brain morphology in ROI analysis. Our findings in a large nationwide population demonstrate that higher social media use is associated with variation in cortical morphology, but future studies are required to establish the directionality of this association.\nDoc 3(Title: Title: Bilingualism modulates functional connectivity induced by a domain-general artificial grammar learning task.) Abstract: Bilingualism is associated with distinct patterns of resting-state functional brain connectivity – a consequence of ongoing language control demands that do not apply to monolinguals. However, it is not well understood how these patterns affect, and are affected by, brain activation for domain-general cognitively demanding tasks. Here, we employ a novel task-driven resting-state electroencephalography design including an implicit Lindenmayer grammar learning task, which tracks aperiodic and hierarchical dependencies, to determine task-related functional connectivity changes in bilinguals. Quantified bilingual experience was used as a predictor of directional effects, using Generalised Additive Models to account for non-linear patterns. Our results revealed post-task alterations to connectivity involving increased involvement of occipital regions, reduced involvement of frontal and central regions, and faster reaction times to stimuli at higher levels of bilingual experience. Crucially, the regions implicated post-task appear to reflect task-relevant regions which are involved in the language and executive control networks, reflecting greater short-term task-driven flexibility. These findings have important implications for our understanding of how domain-general processing and connectivity are shaped by linguistic experience. The online version contains supplementary material available at 10.1038/s41598-026-42094-x.\nDoc 4(Title: Title: Brain function in language and associated networks in non- or minimally verbal children.) Abstract: Language is universal in humans, develops robustly in infancy and is rarely absent entirely in aphasia following strokes. Non- or minimally verbal children, in whom language has not developed by school age in either production or comprehension, thus provide an unparalleled window into the human brain when language function is minimal. Yet insights from functional MRI are absent. Here we report results from a first study of intrinsic connectivity in nine non- or minimally verbal children with autism spectrum disorder scanned under sedation with propofol, along with eight typically developing children (scanned awake), using resting-state functional MRI. We targeted both functional connectivity and anatomically constrained, generative effective connectivity in speech and language regions, the insula and associated networks and the hippocampus. Identical analyses were applied to an independent resting-state MRI dataset of healthy adults scanned both under propofol and while awake, to evaluate sedation confounds. Non- or minimally verbal children with autism spectrum disorder, compared to their neurotypical peers, showed a widespread pattern of hypoconnectivity in auditory speech perception, fronto-temporal and semantic processing regions, which extended further to the insula and the hippocampus. Effective connectivity results selectively replicated these patterns, which correlated with Autism Diagnostic Observation Schedule behavioural scores within the group of non- or minimally verbal children with autism spectrum disorder. This hypoconnectivity pattern extended neither to the adults scanned under propofol, nor to the visual cortex used as a control region in non- or minimally verbal children with autism spectrum disorder, supporting that this pattern of results is not explained by sedation. Together, this first evidence from intrinsic connectivity reveals a broad pattern of underconnectivity across key cognitive networks, which provides a neural correlate for the significant breakdown of language-related cognitive functions in this population.\nDoc 5(Title: Title: [Neural activity related to emotional and empathic deficits in subjects with post-traumatic stress disorder who survived the L'Aquila (Central Italy) 2009 earthquake].) Abstract: Post-Traumatic Stress Disorder (PTSD) is a chronic anxiety disorder. The continued efforts to control the distressing memories by traumatized individuals, together with the reduction of responsiveness to the outside world, are called Emotional Numbing (EN). The EN is one of the central symptoms in PTSD and it plays an integral role not only in the development and maintenance of post-traumatic symptomatology, but also in the disability of emotional regulation. This disorder shows an abnormal response of cortical and limbic regions which are normally involved in understanding emotions since the very earliest stages of the development of processing ability. Patients with PTSD exhibit exaggerated brain responses to emotionally negative stimuli. Identifying the neural correlates of emotion regulation in these subjects is important for elucidating the neural circuitry involved in emotional and empathic dysfunction. We showed that PTSD patients, all survivors of the L'Aquila 2009 earthquake, have a higher sensitivity to negative emotion and lower empathy levels. These emotional and empathic deficits are accompanied by neural brain functional correlates. Indeed PTSD subjects exhibit functional abnormalities in brain regions that are involved in stress regulation and emotional responses. The reduced activation of the frontal areas and a stronger activation of the limbic areas when responding to emotional stimuli could lead the subjects to enact coping strategies aimed at protecting themselves from the re-experience of pain related to traumatic events. This would result in a dysfunctional hyperactivation of subcortical areas, which may cause emotional distress and, consequently, impaired social relationships often reported by PTSD patients.\nDoc 6(Title: Title: The working memory networks of the human brain.) Abstract: Working memory and short-term memory are closely related in their cognitive architecture, capacity limitations, and functional neuroanatomy, which only partly overlap with those of long-term memory. The author reviews the functional neuroimaging literature on the commonalities and differences between working memory and short-term memory and the interplay of areas with modality-specific and supramodal representations in the brain networks supporting these fundamental cognitive processes. Sensory stores in the visual, auditory, and somatosensory cortex play a role in short-term memory, but supramodal parietal and frontal areas are often recruited as well. Classical working memory operations such as manipulation, protection against interference, or updating almost certainly require at least some degree of prefrontal support, but many pure maintenance tasks involve these areas as well. Although it seems that activity shifts from more posterior regions during encoding to more anterior regions during delay, some studies reported sustained delay activity in sensory areas as well. This spatiotemporal complexity of the short-term memory/working memory networks is mirrored in the activation patterns that may explain capacity constraints, which, although most prominent in the parietal cortex, seem to be pervasive across sensory and premotor areas. Finally, the author highlights open questions for cognitive neuroscience research of working memory, such as that of the mechanisms for integrating different types of content (binding) or those providing the link to long-term memory.\nDoc 7(Title: Title: Cerebral correlates of preserved cognitive skills in autism: a functional MRI study of embedded figures task performance.) Abstract: When considering the cognitive abilities of people with autism, the majority of studies have explored domains in which there are deficits. However, on tests of local processing and visual search, exemplified by the Embedded Figures Task (EFT), people with autism have been reported to demonstrate superiority over normal controls. This study employed functional MRI of subjects during the performance of the EFT to test the hypothesis that normal subjects and a group with autism would activate different brain regions and that differences in the patterns of these regional activations would support distinct models of cerebral processing underlying EFT performance in the two groups. It was found that several cerebral regions were similarly activated in the two groups. However, normal controls, as well as demonstrating generally more extensive task-related activations, additionally activated prefrontal cortical areas that were not recruited in the group with autism. Conversely, subjects with autism demonstrated greater activation of ventral occipitotemporal regions. These differences in functional anatomy suggest that the cognitive strategies adopted by the two groups are different: the normal strategy invokes a greater contribution from working memory systems while the autistic group strategy depends to an abnormally large extent on visual systems for object feature analysis. This interpretation is discussed in relation to a model of autism which proposes a predisposition towards local rather than global modes of information processing.\nDoc 8(Title: Title: Categorization for Faces and Tools-Two Classes of Objects Shaped by Different Experience-Differs in Processing Timing, Brain Areas Involved, and Repetition Effects.) Abstract: The brain mechanisms that integrate the separate features of sensory input into a meaningful percept depend upon the prior experience of interaction with the object and differ between categories of objects. Recent studies using representational similarity analysis (RSA) have characterized either the spatial patterns of brain activity for different categories of objects or described how category structure in neuronal representations emerges in time, but never simultaneously. Here we applied a novel, region-based, multivariate pattern classification approach in combination with RSA to magnetoencephalography data to extract activity associated with qualitatively distinct processing stages of visual perception. We asked participants to name what they see whilst viewing bitonal visual stimuli of two categories predominantly shaped by either value-dependent or sensorimotor experience, namely faces and tools, and meaningless images. We aimed to disambiguate the spatiotemporal patterns of brain activity between the meaningful categories and determine which differences in their processing were attributable to either perceptual categorization\nDoc 9(Title: Title: Neural representations of phonological information in bilingual language production.) Abstract: Previous research has explored the neural mechanisms of bilinguals' language production, but most studies focused on neural mechanisms of cognitive control during language production. Therefore, it is unclear which brain regions represent lexical information (especially phonological information) during production and how they are affected by language context. To address those questions, we used representational similarity analysis to explore neural representations of phonological information in native (L1) and second languages (L2) in the single- and mixed-language contexts, respectively. Results showed that Chinese-English bilinguals behaviorally performed worse and exhibited more activations in brain regions associated with language processing and cognitive control in the mixed-language context relative to the single-language context. Further representational similarity analysis revealed that phonological representations of L1 were detected in the left pars opercularis, middle frontal gyrus, and anterior supramarginal gyrus, while phonological representations of L2 were detected in the bilateral occipitotemporal cortex regardless of the target language. More interestingly, robust phonological representations of L1 were observed in brain areas related to phonological processing during L2 production regardless of language context. These results provide direct neuroimaging evidence for the nonselective processing hypothesis and highlight the superiority of phonological representations in the dominant language during bilingual language production.\nDoc 10(Title: Title: Predicting the word frequency effect in naturalistic Chinese reading: A multilevel analysis of brain function and gene expression.) Abstract: The word frequency effect (WFE) refers to the phenomenon whereby high-frequency words are processed more efficiently than low-frequency words. This robust effect is consistently observed across different languages and task paradigms. Previous studies have examined its neural mechanisms using techniques such as functional MRI, which identified brain regions involved in frequency-based lexical processing. However, it remains unclear whether these regions can longitudinally predict the magnitude of the WFE at the individual level. In this study, we combined eye-tracking technique with imaging-transcriptomic approaches to identify potential neurobiological markers underlying the WFE. Our results revealed a distributed set of cortical and subcortical regions whose regional homogeneity (ReHo) patterns negatively predicted the magnitude of the WFE, as estimated by first fixation duration and single fixation duration, with particular emphasis on the basal ganglia-thalamo-cortical circuits, underscoring their critical role in lexical processing efficiency. In addition, neurotransmitter systems enriched in WFE-related ReHo patterns were identified, and functional enrichment analyses revealed distinct biological processes for genes upregulated and downregulated in these areas. Furthermore, we observed divergent developmental trajectories between the two gene sets, highlighting temporally and regionally specific gene expression patterns t

Generation process:   8%|▊         | 1/13 [00:01<00:21,  1.83s/it]

[{'role': 'system', 'content': 'You are a biomedical expert. OUTPUT RULE: Answer in 2-3 sentences (30-50 words). State the key fact first, then supporting detail. Write like a PubMed abstract sentence. Answer the question using only the provided documents. Be direct and factual - no preamble, no caveats.\n\nDocuments:\nDoc 1(Title: Title: Visual cortical dynamics supporting predictable attentional capture.) Abstract: Visual behavior depends on the ability to prioritize relevant sensory information while filtering out distractions. Predictable sensory contexts enable more efficient behavior by altering sensory processing. Using laminar neurophysiology in macaque visual cortex measuring population spiking during a feature-based pop-out visual search task, we examined how predictable visual routines influence cortical columnar processing of sensory information. By manipulating predictability through attentional priming, we found improved behavioral performance with predictable stimulus arrays. These behavioral changes were supported by earlier neuronal attentional target selection driven by reduced variability in the sensory response to the predictable target stimulus and more homogeneous feedforward processing dynamics across the cortical column. More effective distractor suppression was driven by adapted feedforward processing of the more frequent distractor stimulus. Taken together, these changes implicate independent mechanisms for target enhancement and distractor suppression. Our results highlight how predictions from experience alter visual columnar processing to optimize attentional selection through streamlining feedforward signaling. Both target enhancement and distractor suppression are independently observable in visual cortex with different profiles of modulation as a function of predictability.Predictions produce stronger, more reliable feedforward responses to attention-capturing targets across the visual cortical layers.Better distractor suppression with stimulus predictability is driven by adapted sensory representations, not top-down inhibition. How do predictions help determine what catches our attention? It is well known that when primates repeatedly perform visuomotor tasks, they become more proficient. Using neural recordings across the layers of the visual cortex, Groot et al. demonstrate that more efficient feedforward processing of sensory information contributes to improved visual behavior under predictable sensory conditions. These findings highlight the crucial role of predictions in proactively shaping sensory representations to facilitate efficient attentive behavior.\nDoc 2(Title: Title: Disrupting motor cortical regional activity during motor sequence skill training impairs human motor visuomotor skill acquisition and learning that is not sequence-specific.) Abstract: Implicit sequence and visuomotor skill learning is important for successful goal-directed behavior in everyday tasks. However, prior research has primarily relied on correlational methods to investigate the underlying neural mechanisms of sequence and visuomotor skill learning. To evaluate the necessary contributions of different motor cortical regions to both types of skill learning, we enrolled 62 neurotypical adults (41 female, 21 male) and delivered spatiotemporally resolved single-pulse transcranial magnetic stimulation (TMS) over either the premotor cortex (PMC) or primary motor cortex (M1) to transiently disrupt activity while participants practiced an implicit motor sequence task. We hypothesized that 1) PMC disruption would preferentially reduce sequence-specific skill acquisition (Experiment 1) and retention (Experiment 2) while 2) M1 disruption would diminish visuomotor skill acquisition and retention but not sequence learning. Our results demonstrated that TMS-based interference over both M1 and PMC did not disrupt implicit sequence-specific motor skill learning after training however, it did disrupt visuomotor skill acquisition and total learning that was not sequence-specific. Further, disruption of PMC activity had a greater effect on reducing visuomotor skill learning than M1 supporting a potentially distinct role of the PMC in the early stages of skill learning.\nDoc 3(Title: Title: The role of the striatum in visuomotor integration during handwriting: an fMRI study.) Abstract: This study investigates the role of the dorsal/sensorimotor striatum in visuomotor integration (i.e., the transformation of internal visual information about letter shapes into motor output) during handwriting. Twenty healthy participants underwent fMRI scanning with tasks consisting of self-paced handwriting of alphabetically ordered single letters and simple dots, with both tasks performed without visual feedback. Functional connectivity (FC) from these two tasks was compared to demonstrate the difference between coordinated activity arising during handwriting and the activity during a simpler motor condition. Our study focused upon the writing-specific cortico-striatal network of preselected regions of interest consisting of the visual word form area (VWFA), anterior intraparietal sulcus/superior parietal lobule, striatum, premotor cortex/Exner\'s area, and primary and supplementary motor regions. We observed systematically increased task-induced cortico-striatal and cortico-cortical FC. This increased synchronization of neural activity between the VWFA, i.e., the visual cortical area containing information about letter shapes, and the frontoparietal motor regions is mediated by the striatum. These findings suggest the involvement of the striatum in integrating stored letter-shape information with motor planning and execution during handwriting.\nDoc 4(Title: Title: The human posterior cingulate, retrosplenial, and medial parietal cortex effective connectome, and implications for memory and navigation.) Abstract: The human posterior cingulate, retrosplenial, and medial parietal cortex are involved in memory and navigation. The functional anatomy underlying these cognitive functions was investigated by measuring the effective connectivity of these Posterior Cingulate Division (PCD) regions in the Human Connectome Project-MMP1 atlas in 171 HCP participants, and complemented with functional connectivity and diffusion tractography. First, the postero-ventral parts of the PCD (31pd, 31pv, 7m, d23ab, and v23ab) have effective connectivity with the temporal pole, inferior temporal visual cortex, cortex in the superior temporal sulcus implicated in auditory and semantic processing, with the reward-related vmPFC and pregenual anterior cingulate cortex, with the inferior parietal cortex, and with the hippocampal system. This connectivity implicates it in hippocampal episodic memory, providing routes for "what," reward and semantic schema-related information to access the hippocampus. Second, the antero-dorsal parts of the PCD (especially 31a and 23d, PCV, and also RSC) have connectivity with early visual cortical areas including those that represent spatial scenes, with the superior parietal cortex, with the pregenual anterior cingulate cortex, and with the hippocampal system. This connectivity implicates it in the "where" component for hippocampal episodic memory and for spatial navigation. The dorsal-transitional-visual (DVT) and ProStriate regions where the retrosplenial scene area is located have connectivity from early visual cortical areas to the parahippocampal scene area, providing a ventromedial route for spatial scene information to reach the hippocampus. These connectivities provide important routes for "what," reward, and "where" scene-related information for human hippocampal episodic memory and navigation. The midcingulate cortex provides a route from the anterior dorsal parts of the PCD and the supracallosal part of the anterior cingulate cortex to premotor regions.\nDoc 5(Title: Title: Movement-related activity during goal-directed hand actions in the monkey ventrolateral prefrontal cortex.) Abstract: Grasping actions require the integration of two neural processes, one enabling the transformation of object properties into corresponding motor acts, and the other involved in planning and controlling action execution on the basis of contextual information. The first process relies on parieto-premotor circuits, whereas the second is considered to be a prefrontal function. Up to now, the prefrontal cortex has been mainly investigated with conditional visuomotor tasks requiring a learned association between cues and behavioural output. To clarify the functional role of the prefrontal cortex in grasping actions, we recorded the activity of ventrolateral prefrontal (VLPF) neurons while monkeys (Macaca mulatta) performed tasks requiring reaching-grasping actions in different contextual conditions (in light and darkness, memory-guided, and in the absence of abstract learned rules). The results showed that the VLPF cortex contains neurons that are active during action execution (movement-related neurons). Some of them showed grip selectivity, and some also responded to object presentation. Most movement-related neurons discharged during action execution both with and without visual feedback, and this discharge typically did not change when the action was performed with object mnemonic information and in the absence of abstract rules. The findings of this study indicate that a population of VLPF neurons play a role in controlling goal-directed grasping actions in several contexts. This control is probably exerted within a wider network, involving parietal and premotor regions, where the role of VLPF movement-related neurons would be that of activating, on the basis of contextual information, the representation of the motor goal of the intended action (taking possession of an object) during action planning and execution.\nDoc 6(Title: Title: Intact hemisphere and corpus callosum compensate for visuomotor functions after early visual cortex damage.) Abstract: Unilateral damage to the primary visual cortex (V1) leads to clinical blindness in the opposite visual hemifield, yet nonconscious ability to transform unseen visual input into motor output can be retained, a condition known as "blindsight." Here we combined psychophysics, functional magnetic resonance imaging, and tractography to investigate the functional and structural properties that enable the developing brain to partly overcome the effects of early V1 lesion in one blindsight patient. Visual stimuli appeared in either the intact or blind hemifield and simple responses were given with either the left or right hand, thereby creating conditions where visual input and motor output involve the same or opposite hemisphere. When the V1-damaged hemisphere was challenged by incoming visual stimuli, or controlled manual responses to these unseen stimuli, the corpus callosum (CC) dynamically recruited areas in the visual dorsal stream and premotor cortex of the intact hemisphere to compensate for altered visuomotor functions. These compensatory changes in functional brain activity were paralleled by increased connections in posterior regions of the CC, where fibers connecting homologous areas of the parietal cortex course.\nDoc 7(Title: Title: Is the extrastriate body area part of the dorsal visuomotor stream?) Abstract: The extrastriate body area (EBA) processes visual information about body parts, and it is considered one among a series of category-specific perceptual modules distributed across the occipito-temporal cortex. However, recent evidence raises the possibility that EBA might also provide an interface between perception and action, linking the ventral and dorsal streams of visual information processing. Here, we assess anatomical evidence supporting this possibility. We localise EBA in individual subjects using a perceptual task and compare the characteristics of its functional and structural connectivity to those of two perceptual areas, the lateral occipital complex (LOC) and the fusiform body area (FBA), separately for each hemisphere. We apply complementary analyses of resting-state fMRI and diffusion-weighted MRI data in a group of healthy right-handed human subjects (N\xa0=\xa031). Functional and structural connectivity profiles indicate that EBA interacts more strongly with dorsal-stream regions compared to other portions of the occipito-temporal cortex involved in processing body parts (FBA) and object identification (LOC). These findings provide anatomical ground for a revision of the functional role of EBA. Building on a number of recent observations, we suggest that EBA contributes to planning goal-directed actions, possibly by specifying a desired postural configuration to parieto-frontal areas involved in computing movement parameters.\nDoc 8(Title: Title: Visual processing of manipulable objects in the ventral stream is modulated by inputs from parietal action systems.) Abstract: Functional object use requires the integration of visuomotor representations processed in the dorsal visual pathway with representations of surface texture and material composition of objects, processed in the ventral visual pathway. Do regions in the ventral visual pathway project outputs to dorsal visual pathway action systems, or are the outputs of the dorsal visual pathway communicated to the ventral visual pathway to modulate processing? And what are the white matter pathways that mediate structural connectivity in support of functional object use? Here we show that the left inferior parietal cortex, a region within the dorsal visual pathway, exerts a direct effect on neural responses in ventral occipital-temporal cortex during visual processing of manipulable objects. We studied a series of consecutively enrolled participants in the pre-operative phase of their neurosurgical care (N = 109) with lesions principally distributed throughout the left hemisphere. Participants completed an object processing category localizer functional MRI experiment in which they viewed images of manipulable objects, animals, faces, and places. We then used Voxel-based Lesion-Activity Mapping (VLAM), a technique in which functional responses in a region-of-interest are used to predict variance in voxel-wise lesion incidence throughout the brain. In the VLAM analyses performed here, we found that lesions to the left anterior intraparietal sulcus and left supramarginal gyrus, two inferior parietal regions known to support object-directed grasping and manipulation, respectively, cause reduced neural responses for manipulable objects (compared to faces, places and animals) in the fusiform gyrus. Parietal lesions do not affect neural responses during visual processing of places in the same region of the fusiform gyrus, even though places elicit stronger responses in the fusiform gyrus than manipulable objects. Seventy-five of 109 participants took part in a common diffusion MRI protocol, permitting a connectome-wide analyses relating white matter fiber integrity to the strength of functional responses for manipulable objects in the left fusiform gyrus. This analysis demonstrated that the descending portion of the left arcuate fasciculus mediates parietal-totemporal lobe connectivity for manipulable objects, supporting the integration of action representations with conceptual and perceptual attributes of objects. By combining voxel-based and connectome-wide lesion-symptom mapping methods with functional MRI, we have demonstrated that structural connectivity to dorsal visual pathway areas supporting skilled manual action shape category-specific neural responses for manipulable objects within the ventral visual pathway.\nDoc 9(Title: Title: Real and Imagined Grasping Movements Differently Activate the Human Dorsomedial Parietal Cortex.) Abstract: Object prehension typically includes a transport phase (reaching) and a grip phase (grasping). Within the posterior parietal cortex (PPC), grasping movements have been traditionally associated to a lateral activation, although recent monkey evidence suggests also a medial involvement. Here, we wanted to determine whether grasping-related activities are present in the human dorsomedial parietal cortex, by focusing on two cortical regions specialized in the monkey in controlling limb movements, i.e., V6A (composed by its ventral and dorsal sectors, V6Av and V6Ad, respectively) and PEc, both recently defined also in humans. We acquired functional magnetic resonance images while participants performed both real (pantomimed) and imagined grasping of visually-presented objects. We found that the human areas V6Ad (hV6Ad) and PEc (hPEc) were both activated by real grasping, whereas hV6Ad only was activated by the imagery of grasping movements. hV6Av was not involved in either types of grasping. These results speak against the traditional notion of a medial-to-lateral segregation of reaching versus grasping information within the PPC and strengthen the idea that the human dorsomedial parietal cortex implements the whole complex pattern of visuomotor transformations required for object-oriented actions. Our findings suggest that hV6Ad is particularly involved in implementing all the visuomotor transformations needed to create an abstract representation of the object-directed action, while hPEc is involved in implementing the sensorimotor transformations needed to actually perform that action.\nDoc 10(Title: Title: Visuomotor adaptation and savings are preserved in individuals with depression.) Abstract: Depression is a mental disorder associated primarily with mood and cognitive symptoms. Several studies show that depression is additionally accompanied by decrements in gross and fine motor functioning. The present study examined to what extent depression affects the ability to adapt sensorimotor behavior. A total of 20 participants with depression and 22 controls performed a manual adaptation task in which they had to adapt joystick movements to a visual perturbation. We assessed the rate of adaptation following the introduction of the visual perturbation (both for early and later stages of adaptation) and the rate of de-adaptation following its removal. In addition, questionnaires were used to measure severity of depressive symptoms and quality of life. Participants completed these assessments twice (i.e., at baseline and after an approximately 15-week interval), allowing us to also assess savings of adaptation as well as the link between changes in mood and sensorimotor performance. We found that across all participants reliable adaptation patterns and savings of adaptation were observed. Results of Bayesian models showed moderate evidence indicating that depression was not associated with poorer adaptability or savings. Furthermore, adaptation rates were not associated with the severity of depressive symptoms. These findings further refine the psychomotor profile of depression and suggest that it does not affect sensorimotor adaptation or savings of adaptation.\n'}, {'role': 'user', 'content': 'Question: What is the role of the prefrontal cortex in visuomotor tasks?\nAnswer:'}]
----asd-asd-a--------

Generation process:  15%|█▌        | 2/13 [00:03<00:18,  1.70s/it]

[{'role': 'system', 'content': "You are a biomedical expert. OUTPUT RULE: Answer in 2-3 sentences (30-50 words). State the key fact first, then supporting detail. Write like a PubMed abstract sentence. Answer the question using only the provided documents. Be direct and factual - no preamble, no caveats.\n\nDocuments:\nDoc 1(Title: Title: Bilingualism modulates functional connectivity induced by a domain-general artificial grammar learning task.) Abstract: Bilingualism is associated with distinct patterns of resting-state functional brain connectivity – a consequence of ongoing language control demands that do not apply to monolinguals. However, it is not well understood how these patterns affect, and are affected by, brain activation for domain-general cognitively demanding tasks. Here, we employ a novel task-driven resting-state electroencephalography design including an implicit Lindenmayer grammar learning task, which tracks aperiodic and hierarchical dependencies, to determine task-related functional connectivity changes in bilinguals. Quantified bilingual experience was used as a predictor of directional effects, using Generalised Additive Models to account for non-linear patterns. Our results revealed post-task alterations to connectivity involving increased involvement of occipital regions, reduced involvement of frontal and central regions, and faster reaction times to stimuli at higher levels of bilingual experience. Crucially, the regions implicated post-task appear to reflect task-relevant regions which are involved in the language and executive control networks, reflecting greater short-term task-driven flexibility. These findings have important implications for our understanding of how domain-general processing and connectivity are shaped by linguistic experience. The online version contains supplementary material available at 10.1038/s41598-026-42094-x.\nDoc 2(Title: Title: A Book Review of 'Handbook of Children and Screens: Digital Media, Development, and Well-Being From Birth Through Adolescence' Edited by Dimitri A. Christakis and Laurent Hale.) Abstract: Dimitri A. Christakis and Lauren Hale's This book explains how digital media and screens influence children’s development from early childhood to adolescence. It shows how screen use affects attention, learning, sleep, social relationships, and emotional well-being. The book highlights that digital media can shape brain development, sometimes by replacing important activities like play, reading, and face-to-face interaction. It also explains how children today interact with different technologies such as social media, video games, and artificial intelligence, and how these experiences vary depending on age and context. These contribute to the problems such as attention difficulties, reduced empathy, and excessive use. While more research is needed to clearly establish cause and effect, by discussing issues like digital literacy, balanced screen use with it impact on cognition, it helps child psychologists, researchers, teachers, and families better understand how to create healthier psychologically sound digital environments for children’s growth and development.\nDoc 3(Title: Title: Investigating Cognitive Load and Autonomic Arousal During Voice Production and Vocal Auditory-Motor Adaptation.) Abstract: Cognitive load and autonomic arousal are hypothesized to affect voice production, yet the nature of these relationships is unclear. The purpose of this study was to assess how cognitive load and autonomic arousal differentially affect voice production and vocal motor control. Physiological measures of autonomic arousal were recorded from 30 adults under different cognitive loads elicited by a Stroop task. In Experiment 1, voice acoustic measures were measured during speech production. In Experiment 2, fundamental frequency ( In Experiment 1, increased cognitive load was associated with increases in sound pressure level, whereas increases in autonomic arousal measures (i.e., decreases in skin conductance rise time, pulse amplitude, and period) were related to decreases in cepstral peak prominence. Increased autonomic arousal (i.e., decreased pulse amplitude) was related to increased adaptation in Experiment 2. Participants who responded to increased cognitive load by decreasing Differential effects of cognitive load and autonomic arousal emphasize the importance of individual physiological variability when assessing how stress affects the voice.\nDoc 4(Title: Title: Neural representations of phonological information in bilingual language production.) Abstract: Previous research has explored the neural mechanisms of bilinguals' language production, but most studies focused on neural mechanisms of cognitive control during language production. Therefore, it is unclear which brain regions represent lexical information (especially phonological information) during production and how they are affected by language context. To address those questions, we used representational similarity analysis to explore neural representations of phonological information in native (L1) and second languages (L2) in the single- and mixed-language contexts, respectively. Results showed that Chinese-English bilinguals behaviorally performed worse and exhibited more activations in brain regions associated with language processing and cognitive control in the mixed-language context relative to the single-language context. Further representational similarity analysis revealed that phonological representations of L1 were detected in the left pars opercularis, middle frontal gyrus, and anterior supramarginal gyrus, while phonological representations of L2 were detected in the bilateral occipitotemporal cortex regardless of the target language. More interestingly, robust phonological representations of L1 were observed in brain areas related to phonological processing during L2 production regardless of language context. These results provide direct neuroimaging evidence for the nonselective processing hypothesis and highlight the superiority of phonological representations in the dominant language during bilingual language production.\nDoc 5(Title: Title: Continuous Theta Burst Stimulation Inhibits Contralesional Parietal and Occipital Activity During Imagined Movements After Stroke.) Abstract: Repetitive transcranial magnetic stimulation, when paired with skilled motor practice, shows promise for motor recovery after stroke via modulation of cortical excitability. After stroke, continuous theta burst stimulation (cTBS) has been used to reduce excitability in the contralesional cortex. In theory this increases excitability in the homologous motor area in the ipsilesional motor cortex. However, the response to cTBS is inconsistent. In turn, it is difficult to understand the broader impact of cTBS on brain activity after stroke. Here, 30 participants with middle cerebral artery stroke (>\u20096\u2009months post-stroke; nine females; 68\u2009±\u200913\u2009years; 15 left hemisphere stroke) underwent both active and sham cTBS applied over the contralesional primary motor cortex, in counterbalanced order across individuals. Before and after cTBS, participants completed a functional magnetic resonance imaging experiment where they engaged in a motor imagery (the mental rehearsal of a movement) task involving opening a door with their stroke affected arm/hand. Continuous TBS led to reduced activity (pre\u2009>\u2009post) in parietal and occipital brain regions including the calcarine sulcus, cuneus, precuneus, and posterior cingulate cortex during motor imagery. No changes in brain activity were observed following sham stimulation. These findings suggest that cTBS can decrease activity in regions involved in higher-order or compensatory visuospatial processing. Overall, this work furthers our understanding of how cTBS influences brain activity in individuals with stroke, which is critical to inform the use of cTBS as a potential therapy for individuals with stroke.\nDoc 6(Title: Title: I'm trying to read here! How does irrelevant speech affect how you read?) Abstract: Reading involves a remarkable coordination of perceptual and linguistic processes. This coordination is reflected by a close coupling between reading eye movements and lexical properties of words, such as word frequency and predictability, as well as morpho-syntactic and semantic regularities. Yet, reading is also subject to interference, and a common source of interference is when others are speaking nearby. Then, how does irrelevant speech affect reading as reflected in eye movements? Fifty-nine participants (mean age: 19, SD age: 1.22, 25 females, 34 males, primary language: English) read passages from the PROVO corpus Luke and Christianson (Behav Res Methods 50(2):826-833. https://doi.org/10.3758/s13428-017-0908-4 , 2018) under intelligible irrelevant speech or the silence condition, with eye movements recorded. We investigated how irrelevant speech influences the coupling between eye movements and several indicators of lexical difficulty, including word frequency, cloze probability (exact-word predictability), large language model-generated surprisal, morpho-syntactic predictability (part-of-speech and inflection), and semantic similarity (general meaning). Associations between lexical variables and word looking times remained robust during first-pass reading and were unaffected by irrelevant speech, suggesting intact lexical processing during early stages of reading. However, disruption emerged in later eye-movement measures (i.e., total viewing time), where low-frequency and semantically unpredictable words prompted increased re-reading under irrelevant speech. These results indicate that intelligible irrelevant speech selectively interferes with post-lexical, higher-order processing. The increased re-reading of rare and semantically unpredictable words suggests that readers compensate for speech interference by revisiting these words to better integrate their meanings into a coherent understanding of the text.\nDoc 7(Title: Title: Linking the evolution of two prefrontal brain regions to social and foraging challenges in primates.) Abstract: The diversity of cognitive skills across primates remains both a fascinating and a controversial issue. Recent comparative studies provided conflicting results regarding the contribution of social vs ecological constraints to the evolution of cognition. Here, we used an interdisciplinary approach combining comparative cognitive neurosciences and behavioral ecology. Using brain imaging data from 16 primate species, we measured the size of two prefrontal brain regions, the frontal pole (FP) and the dorso-lateral prefrontal cortex (DLPFC), respectively, involved in metacognition and working memory, and examined their relation to a combination of socio-ecological variables. The size of these prefrontal regions, as well as the whole brain, was best explained by three variables: body mass, daily traveled distance (an index of ecological constraints), and population density (an index of social constraints). The strong influence of ecological constraints on FP and DLPFC volumes suggests that both metacognition and working memory are critical for foraging in primates. Interestingly, FP volume was much more sensitive to social constraints than DLPFC volume, in line with laboratory studies showing an implication of FP in complex social interactions. Thus, our data highlights the relative weight of social vs ecological constraints on the evolution of specific prefrontal brain regions and their associated cognitive operations in primates. Primates – such as lemurs, monkeys and humans – can perform a diverse range of cognitive skills, from memory to processing speech. But how did this diversity of cognitive skills evolve? To answer this question, scientists often compare the brain sizes of different species and measure how this relates to their social behaviors or ecology in the wild. But using the whole brain as a measure of global cognitive capacities seems crude in the light of modern cognitive neuroscience studies, which have shown that specific parts of the brain are responsible for certain cognitive skills. It is unclear how relevant the findings of cognitive neuroscience studies, which test animals in a laboratory, are to real life situations and evolution. To address this gap, Bouret et al. integrated methods from both behavioral ecology and cognitive neuroscience to examine the size of primate brain regions. The team studied brain images from 16 primate species, focusing on two regions that have been linked to specific cognitive functions in laboratory experiments. They examined the frontal pole, which is involved in metacognition (the ability to be aware of and assess one’s own thoughts), and the dorsolateral prefrontal cortex, which is involved in working memory (the ability to temporarily store information to solve a problem). Bouret et al. then compared the size of these regions to socio-ecological factors: how much each species performs complex social interactions and how hard it is to find food in the wild, by measuring their population density and daily travel distance, respectively. This revealed that the volume of the frontal pole is larger in species that experience more complex social interactions and in species that struggle to find food – two tasks thought to require metacognition. The dorsolateral prefrontal cortex, however, is only larger in species that have difficulty foraging, which might require a strong working memory to plan travel routes. These findings suggest that laboratory experiments linking cognitive skills to specific parts of the brain are reliable enough to predict the size of these regions across wild primates. The work of Bouret et al. also helps bridge the gap between cognitive neuroscience and behavioral ecology, and demonstrates how these two disciplines can be combined to investigate the evolution of cognition.\nDoc 8(Title: Title: Unveiling the neuroplastic capacity of the bilingual brain: insights from healthy and pathological individuals.) Abstract: Research on the neural imprint of dual-language experience, crucial for understanding how the brain processes dominant and non-dominant languages, remains inconclusive. Conflicting evidence suggests either similarity or distinction in neural processing, with implications for bilingual patients with brain tumors. Preserving dual-language functions after surgery requires considering pre-diagnosis neuroplastic changes. Here, we combine univariate and multivariate fMRI methodologies to test a group of healthy Spanish-Basque bilinguals and a group of bilingual patients with gliomas affecting the language-dominant hemisphere while they overtly produced sentences in either their dominant or non-dominant language. Findings from healthy participants revealed the presence of a shared neural system for both languages, while also identifying regions with distinct language-dependent activation and lateralization patterns. Specifically, while the dominant language engaged a more left-lateralized network, speech production in the non-dominant language relied on the recruitment of a bilateral basal ganglia-thalamo-cortical circuit. Notably, based on language lateralization patterns, we were able to robustly decode (AUC: 0.80\u2009±\u20090.18) the language being used. Conversely, bilingual patients exhibited bilateral activation patterns for both languages. For the dominant language, regions such as the cerebellum, thalamus, and caudate acted in concert with the sparsely activated language-specific nodes. In the case of the non-dominant language, the recruitment of the default mode network was notably prominent. These results demonstrate the compensatory engagement of non-language-specific networks in the preservation of bilingual speech production, even in the face of pathological conditions. Overall, our findings underscore the pervasive impact of dual-language experience on brain functional (re)organization, both in health and disease.\nDoc 9(Title: Title: Relating latent factors of reasoning, affect, and cognition to the delusional experience.) Abstract: Reasoning biases play a crucial role in the formation and maintenance of delusions. In psychosis, it is unclear whether these biases cluster onto similar underlying factors or represent independent constructs. The current study presents data on task-based reasoning biases and self-reported cognitive biases, as well as cognition and affect. Using these data, we aimed to understand mechanisms underlying facets of clinical delusional severity and broader unusual thought content. Participants with schizophrenia-spectrum disorders (SSD; N\u2009=\u200975) were enrolled following hospitalization for an acute psychotic episode. Non-clinical comparison participants (NCC; N\u2009=\u200970) were recruited for comparison of affect, cognition, and reasoning biases. Exploratory factor analysis and multivariable linear regressions were performed in the SSD group only. Core clinical delusions and broader unusual thought content, alongside preoccupation, conviction, and distress were used as outcome measures. SSD participants had more severe reasoning biases, cognitive deficits, and negative affect than NCC. In SSD, factor analysis revealed four latent constructs representing belief updating, cognitive biases, affective disturbances, and general cognitive ability. Affect was significantly associated with delusional preoccupation and distress. Belief updating was the primary factor associated with conviction. Cognitive biases related to the number of unusual beliefs endorsed, but no other aspects of severity. General cognitive ability was unrelated to all facets of delusional severity in our sample. Affective disturbances and belief updating map onto distinct aspects of clinical delusions in SSD; delusion severity is not robustly related to cognitive impairment. Reducing delusional conviction may require treatments focused on how new evidence is integrated into existing beliefs.\nDoc 10(Title: Title: Design of a deep learning prediction model for Alzheimer's and Parkinson's Disease using MRI images.) Abstract: Alzheimer's disease (AD) and Parkinson's disease (PD) are types of neurodegenerative diseases that affect the body and get worse over time. The cause of AD mainly involves the buildup of protein which are abnormal, issues with the immune reaction, death of neurons. Different from this, the death of the neurons that make dopamine leads to PD and causes both motor and non-motor problems. MRI images are used to provide an early and correct diagnosis to enable timely treatment planning and management of the disease. In this paper, a design of an AI-based deep learning framework is proposed for the classification of neurodegenerative disease based on the brain MRI data. The pipeline that we propose begins with data preparation including data augmentation using InceptionGAN for augmentation of the dataset and fixing of class imbalance issues. A composite method of feature extraction using ConvNeXt and MaxViT along with the Cross-Fusion Attention model, worked well to capture local and global spatial features. Bayesian Optimization and Genetic Algorithm are used to optimize hyperparameters for improving the performance of the model. The Hybrid Deep Neural Network (HDNN) is the last classifier with an accuracy of 97.4%. Based on performance accuracy, F1-score, the model is strong and reliable. We used Gradient-weighted Class Activation Mapping++ to explain how regions of interest in the brain influence our model's decisions. This study offers an interpretable and high-performing deep learning framework for the early and precise prediction of neurodegenerative disorders utilizing MRI imaging, thereby enhancing clinical decision-making and patient care.\n"}, {'role': 'user', 'conten

Generation process:  23%|██▎       | 3/13 [00:05<00:16,  1.69s/it]

[{'role': 'system', 'content': 'You are a biomedical expert. OUTPUT RULE: Answer in 2-3 sentences (30-50 words). State the key fact first, then supporting detail. Write like a PubMed abstract sentence. Answer the question using only the provided documents. Be direct and factual - no preamble, no caveats.\n\nDocuments:\nDoc 1(Title: Title: Relationship between impaired cerebral lymphatic function and iron deposition, blood flow in VaD: a clinical MRI study.) Abstract: The neural mechanisms induced by cerebral small vessel disease (CSVD) in the vascular dementia (VaD) is extremely complex. Recent studies have identified altered lymphatic function as a key factor contributing to the development of cognitive deficits, whether they linked to iron deposition and reduced cerebral blood flow remains unclear. The study involved 59 participants, comprising 30 healthy controls and 29 patients with VaD. Each participant underwent QSM, ASL, and DTI imaging scans and clinical measurements. The ALPS index based on DTI, QSM, and ASL for the left and right hemispheres, as well as for the whole brain were calculated and compared between groups. Regional mean susceptibility and mean CBF based on AAL template were calculated and compared between groups. Correlation analyses were performed between altered indexes and clinical measurements. Finally, mediation analyses were conducted to determine whether the mean susceptibility rate and mean CBF were involved in the modulation process of the ALPS. DTI-ALPS based analysis demonstrated a significantly lower ALPS index for the left, right, and whole brain in the VaD as compared to healthy controls. Mean susceptibility in the bilateral superior occipital gyrus and bilateral middle occipital gyrus was significantly higher, whereas mean CBF in the eft inferior frontal gyrus, opercular part, right rolandic operculum, right insula, and right heschl gyrus was significantly lower in the VaD. Further correlation analyses revealed associations between elevated mean susceptibility, reduced ALPS index, and cognitive impairments. Additionally, the results of correlation and mediation analyses suggested that CBF may be involved in the regulatory process of DTI-ALPS. Our results demonstrated that altered lymphatic function is a key pathological factor in VaD, and reduced cerebral blood flow may play a role in this process. These findings provide a theoretical basis for identifying new targets in the treatment of VaD.\nDoc 2(Title: Title: Visual processing of manipulable objects in the ventral stream is modulated by inputs from parietal action systems.) Abstract: Functional object use requires the integration of visuomotor representations processed in the dorsal visual pathway with representations of surface texture and material composition of objects, processed in the ventral visual pathway. Do regions in the ventral visual pathway project outputs to dorsal visual pathway action systems, or are the outputs of the dorsal visual pathway communicated to the ventral visual pathway to modulate processing? And what are the white matter pathways that mediate structural connectivity in support of functional object use? Here we show that the left inferior parietal cortex, a region within the dorsal visual pathway, exerts a direct effect on neural responses in ventral occipital-temporal cortex during visual processing of manipulable objects. We studied a series of consecutively enrolled participants in the pre-operative phase of their neurosurgical care (N = 109) with lesions principally distributed throughout the left hemisphere. Participants completed an object processing category localizer functional MRI experiment in which they viewed images of manipulable objects, animals, faces, and places. We then used Voxel-based Lesion-Activity Mapping (VLAM), a technique in which functional responses in a region-of-interest are used to predict variance in voxel-wise lesion incidence throughout the brain. In the VLAM analyses performed here, we found that lesions to the left anterior intraparietal sulcus and left supramarginal gyrus, two inferior parietal regions known to support object-directed grasping and manipulation, respectively, cause reduced neural responses for manipulable objects (compared to faces, places and animals) in the fusiform gyrus. Parietal lesions do not affect neural responses during visual processing of places in the same region of the fusiform gyrus, even though places elicit stronger responses in the fusiform gyrus than manipulable objects. Seventy-five of 109 participants took part in a common diffusion MRI protocol, permitting a connectome-wide analyses relating white matter fiber integrity to the strength of functional responses for manipulable objects in the left fusiform gyrus. This analysis demonstrated that the descending portion of the left arcuate fasciculus mediates parietal-totemporal lobe connectivity for manipulable objects, supporting the integration of action representations with conceptual and perceptual attributes of objects. By combining voxel-based and connectome-wide lesion-symptom mapping methods with functional MRI, we have demonstrated that structural connectivity to dorsal visual pathway areas supporting skilled manual action shape category-specific neural responses for manipulable objects within the ventral visual pathway.\nDoc 3(Title: Title: Beta and Gamma Dynamics in Attentional Networks Predict Conscious Reports.) Abstract: What neural events precede conscious reports? Hemisphere-asymmetric attentional networks are causally related to conscious perception (Bartolomeo et al., 2025; Kaufmann et al., 2024), but their spectrotemporal dynamics remain unclear. Here, we used magnetoencephalography to examine brain oscillations occurring in human participants (male and female) before a near-threshold target during the cue-target period. In 67% of trials, a supra-threshold visual cue appeared near the target placeholder box, indicating that the target would appear at that location (valid condition). In the remaining 33% of trials, the target appeared at the opposite location (invalid condition). We analyzed brain oscillations, coherence, and theta-gamma phase-amplitude (PAC) coupling in 18 regions of interest involved in attentional and perception (Martín-Signes et al., 2024). Results revealed that: (1) Report of validly cued targets was preceded by early (∼58 ms post-cue) beta-band activity in the right-hemisphere superior parietal lobule. (2) Report of invalidly cued targets was preceded by late (∼166 ms post-cue) beta-band activity in the right temporo-occipital (TO) region, PAC in the right lateral visual cortex, and low gamma coherence between this region and the left temporo-parietal junction, (3) Unreported invalidly cued targets were preceded by PAC in the right TO, and by high gamma coherence between this region and the right middle frontal gyrus suggesting a pre-target bias. We show that conscious report is preceded by temporally dissociable, frequency-specific reconfigurations of right-lateralized attentional networks, with an early parietal beta-mediated orienting window and a later ventral beta- and gamma-mediated window that predict conscious reports before target onset.\nDoc 4(Title: Title: The mind\'s eyes: Distinct neural correlates of spatial and object imagery.) Abstract: Mental imagery has long been central to understanding human cognition, yet its neural basis remains debated. Although neuroimaging studies often treat mental imagery as a unitary construct, behavioral research suggests a dissociation between object imagery (visualizing static objects in detail) and spatial imagery (visualizing dynamic transformations of objects and their relations). To test whether these forms of imagery rely on distinct neural systems, we conducted a pre-registered activation likelihood estimation (ALE) meta-analysis of 46 fMRI and PET studies (N\u202f=\u202f591; 772 foci). Conjunction analyses revealed overlapping activity across the medial frontal gyrus, precuneus, and inferior parietal lobule, suggesting a common frontoparietal network underlying general imagery processes. However, contrast analyses revealed patterns of activation dependent on imagery type (object vs. spatial). While spatial imagery was associated with unique activation in bilateral superior parietal lobules, consistent with dorsal visual stream involvement, object imagery elicited unique activation in left-lateralized frontoparietal and ventral stream regions. These findings parallel the dual-stream model of visual processing, suggesting that object imagery, like object recognition, engages the ventral "what" stream, whereas spatial imagery, like spatial perception and transformation, engages the dorsal "where/how" stream. Theoretically, this distinction offers a new perspective on an old debate, namely, the extent to which mental imagery mirrors perception. Our findings suggest that the answer depends on the type of imagery engaged, pointing to task-specific alignment between imagery and perception. Practically, these results invite a reappraisal of how imagery relates to academic, occupational, and everyday behaviors, raising new questions about how different forms of imagery may support distinct cognitive processes.\nDoc 5(Title: Title: The human posterior cingulate, retrosplenial, and medial parietal cortex effective connectome, and implications for memory and navigation.) Abstract: The human posterior cingulate, retrosplenial, and medial parietal cortex are involved in memory and navigation. The functional anatomy underlying these cognitive functions was investigated by measuring the effective connectivity of these Posterior Cingulate Division (PCD) regions in the Human Connectome Project-MMP1 atlas in 171 HCP participants, and complemented with functional connectivity and diffusion tractography. First, the postero-ventral parts of the PCD (31pd, 31pv, 7m, d23ab, and v23ab) have effective connectivity with the temporal pole, inferior temporal visual cortex, cortex in the superior temporal sulcus implicated in auditory and semantic processing, with the reward-related vmPFC and pregenual anterior cingulate cortex, with the inferior parietal cortex, and with the hippocampal system. This connectivity implicates it in hippocampal episodic memory, providing routes for "what," reward and semantic schema-related information to access the hippocampus. Second, the antero-dorsal parts of the PCD (especially 31a and 23d, PCV, and also RSC) have connectivity with early visual cortical areas including those that represent spatial scenes, with the superior parietal cortex, with the pregenual anterior cingulate cortex, and with the hippocampal system. This connectivity implicates it in the "where" component for hippocampal episodic memory and for spatial navigation. The dorsal-transitional-visual (DVT) and ProStriate regions where the retrosplenial scene area is located have connectivity from early visual cortical areas to the parahippocampal scene area, providing a ventromedial route for spatial scene information to reach the hippocampus. These connectivities provide important routes for "what," reward, and "where" scene-related information for human hippocampal episodic memory and navigation. The midcingulate cortex provides a route from the anterior dorsal parts of the PCD and the supracallosal part of the anterior cingulate cortex to premotor regions.\nDoc 6(Title: Title: Mental health in the perinatal period: bridging the gaps in care, evidence, and policy.) Abstract: Perinatal mental health has long been acknowledged as fundamental to the well-being of mothers and infants, yet the recognition of disorders such as postpartum depression, anxiety, and - far less commonly - psychosis still lags behind clinical need. Even where validated screening tools exist, detection remains inconsistent, and many women navigate pregnancy and the postpartum period with symptoms that go unspoken or unnoticed. In some high-income settings, suicide has emerged as a leading contributor to maternal mortality, a reminder that the health consequences of these conditions extend beyond emotional distress and reflect deeper systemic failings. In this opinion paper, we draw on recent developments across epidemiology, neuroscience, psychology, and health-system research to consider why perinatal mental health continues to occupy an uncertain place in routine care. Fragmented service pathways, variability in provider training, and uneven adoption of evidence-supported interventions create persistent gaps between what is known and what is practiced. We highlight examples - stepped-care models, collaborative teams, and digital supports - that illustrate how more coherent systems could function, even if implementation remains uneven. Although a wide range of effective interventions exists, their practical reach is limited by sociocultural norms, structural constraints, and resource imbalances. Understanding these influences together - not in isolation - helps clarify why progress has been slower than the evidence might suggest. Meaningful improvement will depend on strengthening cross-sector integration, expanding scalable technologies, and tailoring policy responses to local realities. Sustained investment in perinatal mental health offers long-term benefits for families and communities and should be regarded as central to modern maternal care.\nDoc 7(Title: Title: Intervention Effects on Phonological Processing in Children With Developmental Speech and/or Language Disorder: A Systematic Review and Meta-Analysis of Studies With Group Design.) Abstract: Challenges in phonological processing are prevalent in children with developmental speech and/or language disorders and are associated with their language acquisition and later reading skills. A recent systematic review and meta-analysis from the same project of studies with a group design on the effects of interventions on output phonology, found that oral language interventions have a positive effect on output phonology, specifically speech production accuracy. These interventions are expected to impact the phonological representational level as well and, thus, also affect phonological processing skills in this population. However, no prior systematic reviews or meta-analyses have been conducted on this topic. We conducted a systematic literature review and meta-analysis to investigate the effectiveness of oral language interventions on children and adolescents\xa0with developmental speech and/or language disorders, focusing on phonological processing as the primary outcome measure, including phonological awareness, phonological retrieval efficiency, and short-term memory. The systematic review was pre-registered (PROSPERO ID: CRD42017076075) and followed the PRISMA guidelines. A search for oral language interventions in children and adolescents\xa0with developmental speech and/or language disorders (mean age, 3-18 years) was conducted across seven databases (PubMed, Web of Science, ERIC, Cochrane Library, PsycINFO, Scopus, LLBA) for studies published between January 2006 and May 2023. We included studies with a group design and phonological processing as the outcome measure. The Cochrane risk of bias tool was used for study appraisal. Individual and average standardised mean differences g were used in the meta-analysis. We also explored the influence of various moderators. We identified 22 studies that met the inclusion criteria. Overall, the risk of bias was low to moderate. Significant and large effect sizes were found in pre-post studies with control groups, showing improvements post-intervention in phonological awareness, g\xa0=\xa00.710, p\xa0<\xa00.001, 95% CI [0.504, 0.917], and phonological short-term memory, g\xa0=\xa00.785, p\xa0=\xa00.010, 95% CI [0.192, 1.279]. Some moderator variables emerged, for example, larger effects when the interventions were based on an integrated theoretical approach, applied in small groups, or when they had processing targets. The results demonstrate that oral language interventions can effectively improve specific phonological processing skills in children and adolescents\xa0with developmental speech and/or language disorders. The identification of key moderating factors provides valuable guidance for clinical practice. What is already known on the subject Children with developmental speech and/or language disorders often have difficulties in phonological processing that can hamper their reading development. Interventions are effective for speech production, but there are no previous systematic reviews or meta-analyses on their effects on the phonological processing skills of children and adolescents with developmental speech and/or language disorders. What this paper adds to existing knowledge We present empirical evidence of the effectiveness of oral language interventions in improving phonological processing (including phonological awareness and phonological short-term memory) in children and adolescents with developmental speech and/or language disorders. What are the potential or actual clinical implications of this work? Oral language interventions have a positive effect on the phonological processing skills of children and adolescents with developmental speech and/or language disorders. They may serve as an indirect means of support for their reading development.\nDoc 8(Title: Title: Static and dynamic resting-state brain activity patterns of table tennis players in 7-Tesla MRI.) Abstract: Table tennis involves quick and accurate motor responses during training and competition. Multiple studies have reported considerably faster visuomotor responses and expertise-related intrinsic brain activity changes among table tennis players compared with matched controls. However, the underlying neural mechanisms remain unclear. Herein, we performed static and dynamic resting-state functional magnetic resonance imaging (rs-fMRI) analyses of 20 table tennis players and 21 control subjects using 7T ultra-high field imaging. We calculated the static and dynamic amplitude of low-frequency fluctuations (ALFF) of the two groups. The results revealed that table tennis players exhibited decreased static ALFF in the left inferior temporal gyrus (lITG) compared with the control group. Voxel-wised static functional connectivity (sFC) and dynamic functional connectivity (dFC) analyses using lITG as the seed region afforded complementary and overlapping results. The table tennis players exhibited decreased sFC in the right middle temporal gyrus and left inferior parietal gyrus. Conversely, they displayed increased dFC from the lITG to prefrontal cortex, particularly the left middle frontal gyrus, left superior frontal gyrus-medial, and left superior frontal gyrus-dorsolateral. These findings suggest that table tennis players demonstrate altered visuomotor transformation and executive function pathways. Both pathways involve the lITG, which is a vital node in the ventral visual stream. These static and dynamic analyses provide complementary and overlapping results, which may help us better understand the neural mechanisms underlying the changes in intrinsic brain activity and network organization induced by long-term table tennis skill training.\nDoc 9(Title: Title: Neural correlates of retrieval practice with feedback in foreign vocabulary learning: An fNIRS study.) Abstract: This study examined the neural correlates of retrieval practice with corrective feedback in foreign vocabulary learning using functional near-infrared spectroscopy (fNIRS). In a three-phase within-subject experiment, 40 Chinese-English bilinguals learned 60 Swahili-Chinese word pairs, with half assigned to restudying and half to retrieval practice. Memory performance was assessed using a cued-recall test after a 30-min delay. Behaviorally, retrieved items were recalled more accurately than rest

Generation process:  31%|███       | 4/13 [00:06<00:14,  1.63s/it]

[{'role': 'system', 'content': 'You are a biomedical expert. OUTPUT RULE: Answer in 2-3 sentences (30-50 words). State the key fact first, then supporting detail. Write like a PubMed abstract sentence. Answer the question using only the provided documents. Be direct and factual - no preamble, no caveats.\n\nDocuments:\nDoc 1(Title: Title: The human posterior cingulate, retrosplenial, and medial parietal cortex effective connectome, and implications for memory and navigation.) Abstract: The human posterior cingulate, retrosplenial, and medial parietal cortex are involved in memory and navigation. The functional anatomy underlying these cognitive functions was investigated by measuring the effective connectivity of these Posterior Cingulate Division (PCD) regions in the Human Connectome Project-MMP1 atlas in 171 HCP participants, and complemented with functional connectivity and diffusion tractography. First, the postero-ventral parts of the PCD (31pd, 31pv, 7m, d23ab, and v23ab) have effective connectivity with the temporal pole, inferior temporal visual cortex, cortex in the superior temporal sulcus implicated in auditory and semantic processing, with the reward-related vmPFC and pregenual anterior cingulate cortex, with the inferior parietal cortex, and with the hippocampal system. This connectivity implicates it in hippocampal episodic memory, providing routes for "what," reward and semantic schema-related information to access the hippocampus. Second, the antero-dorsal parts of the PCD (especially 31a and 23d, PCV, and also RSC) have connectivity with early visual cortical areas including those that represent spatial scenes, with the superior parietal cortex, with the pregenual anterior cingulate cortex, and with the hippocampal system. This connectivity implicates it in the "where" component for hippocampal episodic memory and for spatial navigation. The dorsal-transitional-visual (DVT) and ProStriate regions where the retrosplenial scene area is located have connectivity from early visual cortical areas to the parahippocampal scene area, providing a ventromedial route for spatial scene information to reach the hippocampus. These connectivities provide important routes for "what," reward, and "where" scene-related information for human hippocampal episodic memory and navigation. The midcingulate cortex provides a route from the anterior dorsal parts of the PCD and the supracallosal part of the anterior cingulate cortex to premotor regions.\nDoc 2(Title: Title: Visual cortical dynamics supporting predictable attentional capture.) Abstract: Visual behavior depends on the ability to prioritize relevant sensory information while filtering out distractions. Predictable sensory contexts enable more efficient behavior by altering sensory processing. Using laminar neurophysiology in macaque visual cortex measuring population spiking during a feature-based pop-out visual search task, we examined how predictable visual routines influence cortical columnar processing of sensory information. By manipulating predictability through attentional priming, we found improved behavioral performance with predictable stimulus arrays. These behavioral changes were supported by earlier neuronal attentional target selection driven by reduced variability in the sensory response to the predictable target stimulus and more homogeneous feedforward processing dynamics across the cortical column. More effective distractor suppression was driven by adapted feedforward processing of the more frequent distractor stimulus. Taken together, these changes implicate independent mechanisms for target enhancement and distractor suppression. Our results highlight how predictions from experience alter visual columnar processing to optimize attentional selection through streamlining feedforward signaling. Both target enhancement and distractor suppression are independently observable in visual cortex with different profiles of modulation as a function of predictability.Predictions produce stronger, more reliable feedforward responses to attention-capturing targets across the visual cortical layers.Better distractor suppression with stimulus predictability is driven by adapted sensory representations, not top-down inhibition. How do predictions help determine what catches our attention? It is well known that when primates repeatedly perform visuomotor tasks, they become more proficient. Using neural recordings across the layers of the visual cortex, Groot et al. demonstrate that more efficient feedforward processing of sensory information contributes to improved visual behavior under predictable sensory conditions. These findings highlight the crucial role of predictions in proactively shaping sensory representations to facilitate efficient attentive behavior.\nDoc 3(Title: Title: EXPRESS: What Phonological Overlap Effects Reveal about the Role of Working Memory in Native and Nonnative Language Processing.) Abstract: The present study sheds light on effects of similarity-based interference due to phonological overlap, as well as working memory during silent reading in native and nonnative speakers. While prior research has mainly focused on syntactic complexity or ambiguity to gain insight into nonnative language processing and the role of working memory, the effects of phonological overlap have remained poorly understood. Using multiline texts with varying degrees of phonological overlap, we examined whether increased amounts of overlap disrupt online reading and offline recall, and whether effects differ across native and nonnative groups or vary as a function of working memory capacity. Results revealed that greater phonological overlap caused delays during online processing, but without impacting offline recall. Crucially, native and nonnative speakers experienced online interference similarly, and working memory modulated these effects in comparable ways across both groups. These results suggest convergence both in overt behavior and in how underlying cognitive resources are used. Findings are discussed with respect to their implications for theories of native-nonnative language processing differences and possible directions for further research.\nDoc 4(Title: Title: Working memory for location and time: activity in prefrontal area 46 relates to selection rather than maintenance in memory.) Abstract: The role of the dorsal prefrontal cortex in working memory remains controversial. Influential proposals include a role in the maintenance of domain-specific information, and the processes of executive functions on remembered information. We used event-related functional magnetic resonance imaging to demonstrate a functional dissociation within prefrontal cortex in terms of the components of complex working memory tasks. The maintenance in working memory of spatial locations and their temporal order was associated with activation of area 8 and intraparietal cortex. In contrast, the selection of one location, according to its order, was associated with a distinct frontoparietal network, including dorsolateral prefrontal area 46, ventrolateral prefrontal cortex and anterior cingulate cortex and medial parietal cortex. The different contributions of these areas to selection are considered in the light of recent electrophysiological and lesion studies. We suggest a general role of the dorsolateral prefrontal area 46 in attentional selection, including selection from within working memory.\nDoc 5(Title: Title: GABAergic neurons in basal forebrain exert frequency-specific modulation on auditory cortex and enhance attentional selection of auditory stimuli.) Abstract: The basal forebrain (BF), in particular its cholinergic projections to cortex, has been implicated in regulation of attention in sensory systems. Here, we examine the role of GABAergic projections of the posterior nucleus basalis (pNB) and globus pallidus (GP) in attentional regulation in the auditory system. We employed a detection task where rats detected a narrow band target embedded in broad band noise, while optogenetically modulating GABAergic BF activity. We found that GABAergic BF modulation impacted target detection specifically close to perceptual threshold, consistent with a role in attentional modulation. We also present evidence for target frequency specificity of this modulation, including frequency selectivity and tonotopic organization of pNB/GP, as well as frequency band specific effects of optogenetics on behavioural target detection and on neural activity in auditory cortex and thalamus. Our findings highlight an important role of BF GABAergic neurons in modulating attention in the auditory pathway.\nDoc 6(Title: Title: Parvalbumin interneurons are essential for tonotopy strength in the auditory cortex.) Abstract: Tonotopy, the spatial organization of neurons based on their sound frequency responses, is a fundamental feature of the auditory pathway, extending from the cochlea to the auditory cortex. While excitatory neurons have been considered necessary for tonotopy in the cortex, the role of inhibitory interneurons remains unclear. Using a novel two-channel widefield Ca\nDoc 7(Title: Title: Movement-related activity during goal-directed hand actions in the monkey ventrolateral prefrontal cortex.) Abstract: Grasping actions require the integration of two neural processes, one enabling the transformation of object properties into corresponding motor acts, and the other involved in planning and controlling action execution on the basis of contextual information. The first process relies on parieto-premotor circuits, whereas the second is considered to be a prefrontal function. Up to now, the prefrontal cortex has been mainly investigated with conditional visuomotor tasks requiring a learned association between cues and behavioural output. To clarify the functional role of the prefrontal cortex in grasping actions, we recorded the activity of ventrolateral prefrontal (VLPF) neurons while monkeys (Macaca mulatta) performed tasks requiring reaching-grasping actions in different contextual conditions (in light and darkness, memory-guided, and in the absence of abstract learned rules). The results showed that the VLPF cortex contains neurons that are active during action execution (movement-related neurons). Some of them showed grip selectivity, and some also responded to object presentation. Most movement-related neurons discharged during action execution both with and without visual feedback, and this discharge typically did not change when the action was performed with object mnemonic information and in the absence of abstract rules. The findings of this study indicate that a population of VLPF neurons play a role in controlling goal-directed grasping actions in several contexts. This control is probably exerted within a wider network, involving parietal and premotor regions, where the role of VLPF movement-related neurons would be that of activating, on the basis of contextual information, the representation of the motor goal of the intended action (taking possession of an object) during action planning and execution.\nDoc 8(Title: Title: Category-specific memory encoding in the medial temporal lobe and beyond: the role of reward.) Abstract: The medial temporal lobe (MTL), including the hippocampus (HC), perirhinal cortex (PRC), and parahippocampal cortex (PHC), is central to memory formation. Reward enhances memory through interplay between the HC and substantia nigra/ventral tegmental area (SNVTA). While the SNVTA also innervates the MTL cortex and amygdala (AMY), their role in reward-enhanced memory is unclear. Prior research suggests category specificity in the MTL cortex, with the PRC and PHC processing object and scene memory, respectively. It is unknown, however, whether reward modulates category-specific memory processes. Furthermore, no study has demonstrated clear category specificity in the MTL for encoding processes contributing to subsequent recognition memory. To address these questions, we had 39 healthy volunteers (27 for all memory-based analyses) undergo functional magnetic resonance imaging while performing an incidental encoding task pairing objects or scenes with high or low reward, followed by a next-day recognition test. Behaviorally, high reward preferably enhanced object memory. Neural activity in the PRC and PHC reflected successful encoding of objects and scenes, respectively. Importantly, AMY encoding effects were selective for high-reward objects, with a similar pattern in the PRC. The SNVTA and HC showed no clear evidence of successful encoding. This behavioral and neural asymmetry may be conveyed through an anterior-temporal memory system, including the AMY and PRC, potentially in interplay with the ventromedial prefrontal cortex.\nDoc 9(Title: Title: Does age protect against loss of tonotopy after acute deafness in adulthood?) Abstract: The mammalian auditory system develops a topographical representation of sound frequencies along its pathways, also called tonotopy. In contrast, sensory deprivation during early development results in no or only rudimentary tonotopic organization. This study addresses two questions: (1) How robust is the central tonotopy when hearing fails in adulthood? (2) What role does age play at time of deafness? To address these questions, we deafened young and old adult rats with previously normal hearing. One month after deafening, both groups were unilaterally supplied with cochlear implants and electrically stimulated for 2 h. The central auditory neurons, which were activated as a result of the local electrical intracochlear stimulation, were visualized using Fos staining. While the auditory system of young rats lost the tonotopic organization throughout the brainstem, the auditory system of the older rats mainly sustained its tonotopy. It can be proposed that plasticity prevails in the central auditory system of young adult rats, while network stability prevails in the brains of aging rats. Consequently, age may be an important factor in protecting a hearing-experienced adult auditory system from a rapid loss of tonotopy when suffering from acute hearing loss. Furthermore, the study provides compelling evidence that acute deafness in young adult patients should be diagnosed as early as possible to prevent maladaptation of the central auditory system and thus achieve the optimal hearing outcome with a hearing prosthesis.\nDoc 10(Title: Title: Preparatory Activity in Posterior Temporal Cortex Causally Contributes to Object Detection in Scenes.) Abstract: Theories of visual selective attention propose that top-down preparatory attention signals mediate the selection of task-relevant information in cluttered scenes. Neuroimaging and electrophysiology studies have provided correlative evidence for this hypothesis, finding increased activity in target-selective neural populations in visual cortex in the period between a search cue and target onset. In this study, we used online TMS to test whether preparatory neural activity in visual cortex is causally involved in naturalistic object detection. In two experiments, participants detected the presence of object categories (cars, people) in a diverse set of photographs of real-world scenes. TMS was applied over a region in posterior temporal cortex identified by fMRI as carrying category-specific preparatory activity patterns. Results showed that TMS applied over posterior temporal cortex before scene onset (-200 and -100 msec) impaired the detection of object categories in subsequently presented scenes, relative to vertex and early visual cortex stimulation. This effect was specific to category level detection and was related to the type of attentional template participants adopted, with the strongest effects observed in participants adopting category level templates. These results provide evidence for a causal role of preparatory attention in mediating the detection of objects in cluttered daily-life environments.\n'}, {'role': 'user', 'content': 'Question: What is the role of the prefrontal cortex in cognition?\nAnswer:'}]
----asd-asd-a--------

Generation process:  38%|███▊      | 5/13 [00:08<00:12,  1.57s/it]

[{'role': 'system', 'content': 'You are a biomedical expert. OUTPUT RULE: Answer in 2-3 sentences (30-50 words). State the key fact first, then supporting detail. Write like a PubMed abstract sentence. Answer the question using only the provided documents. Be direct and factual - no preamble, no caveats.\n\nDocuments:\nDoc 1(Title: Title: The mind\'s eyes: Distinct neural correlates of spatial and object imagery.) Abstract: Mental imagery has long been central to understanding human cognition, yet its neural basis remains debated. Although neuroimaging studies often treat mental imagery as a unitary construct, behavioral research suggests a dissociation between object imagery (visualizing static objects in detail) and spatial imagery (visualizing dynamic transformations of objects and their relations). To test whether these forms of imagery rely on distinct neural systems, we conducted a pre-registered activation likelihood estimation (ALE) meta-analysis of 46 fMRI and PET studies (N\u202f=\u202f591; 772 foci). Conjunction analyses revealed overlapping activity across the medial frontal gyrus, precuneus, and inferior parietal lobule, suggesting a common frontoparietal network underlying general imagery processes. However, contrast analyses revealed patterns of activation dependent on imagery type (object vs. spatial). While spatial imagery was associated with unique activation in bilateral superior parietal lobules, consistent with dorsal visual stream involvement, object imagery elicited unique activation in left-lateralized frontoparietal and ventral stream regions. These findings parallel the dual-stream model of visual processing, suggesting that object imagery, like object recognition, engages the ventral "what" stream, whereas spatial imagery, like spatial perception and transformation, engages the dorsal "where/how" stream. Theoretically, this distinction offers a new perspective on an old debate, namely, the extent to which mental imagery mirrors perception. Our findings suggest that the answer depends on the type of imagery engaged, pointing to task-specific alignment between imagery and perception. Practically, these results invite a reappraisal of how imagery relates to academic, occupational, and everyday behaviors, raising new questions about how different forms of imagery may support distinct cognitive processes.\nDoc 2(Title: Title: The human posterior cingulate, retrosplenial, and medial parietal cortex effective connectome, and implications for memory and navigation.) Abstract: The human posterior cingulate, retrosplenial, and medial parietal cortex are involved in memory and navigation. The functional anatomy underlying these cognitive functions was investigated by measuring the effective connectivity of these Posterior Cingulate Division (PCD) regions in the Human Connectome Project-MMP1 atlas in 171 HCP participants, and complemented with functional connectivity and diffusion tractography. First, the postero-ventral parts of the PCD (31pd, 31pv, 7m, d23ab, and v23ab) have effective connectivity with the temporal pole, inferior temporal visual cortex, cortex in the superior temporal sulcus implicated in auditory and semantic processing, with the reward-related vmPFC and pregenual anterior cingulate cortex, with the inferior parietal cortex, and with the hippocampal system. This connectivity implicates it in hippocampal episodic memory, providing routes for "what," reward and semantic schema-related information to access the hippocampus. Second, the antero-dorsal parts of the PCD (especially 31a and 23d, PCV, and also RSC) have connectivity with early visual cortical areas including those that represent spatial scenes, with the superior parietal cortex, with the pregenual anterior cingulate cortex, and with the hippocampal system. This connectivity implicates it in the "where" component for hippocampal episodic memory and for spatial navigation. The dorsal-transitional-visual (DVT) and ProStriate regions where the retrosplenial scene area is located have connectivity from early visual cortical areas to the parahippocampal scene area, providing a ventromedial route for spatial scene information to reach the hippocampus. These connectivities provide important routes for "what," reward, and "where" scene-related information for human hippocampal episodic memory and navigation. The midcingulate cortex provides a route from the anterior dorsal parts of the PCD and the supracallosal part of the anterior cingulate cortex to premotor regions.\nDoc 3(Title: Title: Mental health in the perinatal period: bridging the gaps in care, evidence, and policy.) Abstract: Perinatal mental health has long been acknowledged as fundamental to the well-being of mothers and infants, yet the recognition of disorders such as postpartum depression, anxiety, and - far less commonly - psychosis still lags behind clinical need. Even where validated screening tools exist, detection remains inconsistent, and many women navigate pregnancy and the postpartum period with symptoms that go unspoken or unnoticed. In some high-income settings, suicide has emerged as a leading contributor to maternal mortality, a reminder that the health consequences of these conditions extend beyond emotional distress and reflect deeper systemic failings. In this opinion paper, we draw on recent developments across epidemiology, neuroscience, psychology, and health-system research to consider why perinatal mental health continues to occupy an uncertain place in routine care. Fragmented service pathways, variability in provider training, and uneven adoption of evidence-supported interventions create persistent gaps between what is known and what is practiced. We highlight examples - stepped-care models, collaborative teams, and digital supports - that illustrate how more coherent systems could function, even if implementation remains uneven. Although a wide range of effective interventions exists, their practical reach is limited by sociocultural norms, structural constraints, and resource imbalances. Understanding these influences together - not in isolation - helps clarify why progress has been slower than the evidence might suggest. Meaningful improvement will depend on strengthening cross-sector integration, expanding scalable technologies, and tailoring policy responses to local realities. Sustained investment in perinatal mental health offers long-term benefits for families and communities and should be regarded as central to modern maternal care.\nDoc 4(Title: Title: Intervention Effects on Phonological Processing in Children With Developmental Speech and/or Language Disorder: A Systematic Review and Meta-Analysis of Studies With Group Design.) Abstract: Challenges in phonological processing are prevalent in children with developmental speech and/or language disorders and are associated with their language acquisition and later reading skills. A recent systematic review and meta-analysis from the same project of studies with a group design on the effects of interventions on output phonology, found that oral language interventions have a positive effect on output phonology, specifically speech production accuracy. These interventions are expected to impact the phonological representational level as well and, thus, also affect phonological processing skills in this population. However, no prior systematic reviews or meta-analyses have been conducted on this topic. We conducted a systematic literature review and meta-analysis to investigate the effectiveness of oral language interventions on children and adolescents\xa0with developmental speech and/or language disorders, focusing on phonological processing as the primary outcome measure, including phonological awareness, phonological retrieval efficiency, and short-term memory. The systematic review was pre-registered (PROSPERO ID: CRD42017076075) and followed the PRISMA guidelines. A search for oral language interventions in children and adolescents\xa0with developmental speech and/or language disorders (mean age, 3-18 years) was conducted across seven databases (PubMed, Web of Science, ERIC, Cochrane Library, PsycINFO, Scopus, LLBA) for studies published between January 2006 and May 2023. We included studies with a group design and phonological processing as the outcome measure. The Cochrane risk of bias tool was used for study appraisal. Individual and average standardised mean differences g were used in the meta-analysis. We also explored the influence of various moderators. We identified 22 studies that met the inclusion criteria. Overall, the risk of bias was low to moderate. Significant and large effect sizes were found in pre-post studies with control groups, showing improvements post-intervention in phonological awareness, g\xa0=\xa00.710, p\xa0<\xa00.001, 95% CI [0.504, 0.917], and phonological short-term memory, g\xa0=\xa00.785, p\xa0=\xa00.010, 95% CI [0.192, 1.279]. Some moderator variables emerged, for example, larger effects when the interventions were based on an integrated theoretical approach, applied in small groups, or when they had processing targets. The results demonstrate that oral language interventions can effectively improve specific phonological processing skills in children and adolescents\xa0with developmental speech and/or language disorders. The identification of key moderating factors provides valuable guidance for clinical practice. What is already known on the subject Children with developmental speech and/or language disorders often have difficulties in phonological processing that can hamper their reading development. Interventions are effective for speech production, but there are no previous systematic reviews or meta-analyses on their effects on the phonological processing skills of children and adolescents with developmental speech and/or language disorders. What this paper adds to existing knowledge We present empirical evidence of the effectiveness of oral language interventions in improving phonological processing (including phonological awareness and phonological short-term memory) in children and adolescents with developmental speech and/or language disorders. What are the potential or actual clinical implications of this work? Oral language interventions have a positive effect on the phonological processing skills of children and adolescents with developmental speech and/or language disorders. They may serve as an indirect means of support for their reading development.\nDoc 5(Title: Title: Non-linguistic comprehension, social inference and empathizing skills in autistic young adults, young adults with autistic traits and control young adults: Group differences and interrelatedness of skills.) Abstract: Despite increasing knowledge of social communication skills of autistic peole, the interrelatedness of different skills such as non-linguistic comprehension, social inference and empathizing skills is not much known about. A better understanding of the complex interplay between different domains of social communication helps us to develop assessment protocols for individuals with social communication difficulties. To compare the performances of autistic young adults, young adults with autistic traits identified in childhood and control young adults in social communication tasks measuring non-linguistic comprehension, social inference and empathizing skills. In addition, to examine associations between the different social communication measures. Autistic young adults (n = 34), young adults with autistic traits (n = 19) and control young adults (n = 36) completed the extra- and paralinguistic scales of the Assessment Battery for Communication (ABaCo), the Faux Pas Recognition Test, Social-Pragmatic Questions (SoPra) and the Empathy Quotient (EQ). Group differences were found in the performance in the ABaCo, SoPra and EQ scores. Compared with the control young adults, autistic young adults scored lower. The performance of the young adults in the autistic traits group fell in between the other two groups. There were no group differences in the Faux Pas Recognition Test. The variability within the groups was large in all measurements. In the control group, there was a significant correlation between EQ and SoPra scores and between the Faux Pas and SoPra scores. In the autistic group, a significant correlation was found between Faux Pas and SoPra scores. Also, other patterns were observed but these were not statistically significant. The young adults with autistic traits fell in between the control and autistic young adults, highlighting the presence of the continuum in the terms of features of social communication. The results support other current research that suggests that theory of mind and other social communication skills may not be universally or widely impaired in all autistic individuals without cognitive deficits. Although all tasks examined social communication skills, only a small number of significant correlations were found between test scores. This highlights that clinical conclusions about a person\'s social communication should be based on the outcomes of different types of methods measuring different aspects of social communication. It is clear that the interrelatedness of different social communication skills needs further research. What is already known on this subject For successful communication, the ability to infer others\' emotions, intentions and mental states is crucial. Autistic people have difficulty with many aspects of social communication. However, the associations between different aspects of social communication need to be better understood. What this paper adds to existing knowledge The unique contribution of this study is to compare the performance of autistic people not only with that of a control group but also with people with childhood autistic traits. This provides an understanding of the interrelatedness of different social communication skills in people with varying degrees of autistic traits. This study used four assessment methods focusing on three different social communication elements (non-linguistic comprehension, social inference and empathizing skills). These elements have complex relationships to one another, some being closely overlapping, some more distally related and some reflect more complex multifactorial elements. This study shows that although groups differ from each other in most of the assessments, the performance of different groups overlapped showing that many autistic young adults can perform well in non-linguistic and social inference tasks in structured assessment contexts. What are the potential or actual clinical implications of this work? Our findings suggest that in the assessment of social communication, self-reports and clinical assessments can be used effectively together. They can complement each other, pointing out the strengths and weaknesses of a person, leading to more personalized therapeutic interventions.\nDoc 6(Title: Title: Explicitly nonlinear fMRI networks reveal hidden trajectories of infant brain development.) Abstract: Nonlinearity is a hallmark of brain complexity at multiple scales. However, existing functional magnetic resonance imaging (fMRI) functional connectivity studies typically utilize linear methods. Therefore, links between nonlinear fMRI connectivity patterns and the development of the human brain during critical periods such as infancy remain unclear. To address this gap in knowledge, we developed a data-driven approach to capture brain intrinsic connectivity networks from explicitly nonlinear resting-state fMRI connectivity and profiled their developmental associations in a cohort of typically developing human infants. We identified neurobiologically structured nonlinear fMRI connectivity patterns during early postnatal life, indicating that macroscopic brain ensembles systematically participate in nonlinear relationships at birth. Furthermore, we found that linear and explicitly nonlinear network counterparts are linked to partially overlapping but complementary developmental profiles during this period of rapid brain maturation, with the explicitly nonlinear approach unveiling insights into the development of networks that have been associated with sensorimotor capacities, default mode processes, executive functioning, language production, and stimulus saliency. Our study marks the first comprehensive developmental investigation of whole-brain nonlinear fMRI networks in human infants and deepens contemporary perspectives on neuroimaging data discovery by emphasizing the informational richness of nonlinear relationships at fMRI scales of observation.\nDoc 7(Title: Title: Categorization for Faces and Tools-Two Classes of Objects Shaped by Different Experience-Differs in Processing Timing, Brain Areas Involved, and Repetition Effects.) Abstract: The brain mechanisms that integrate the separate features of sensory input into a meaningful percept depend upon the prior experience of interaction with the object and differ between categories of objects. Recent studies using representational similarity analysis (RSA) have characterized either the spatial patterns of brain activity for different categories of objects or described how category structure in neuronal representations emerges in time, but never simultaneously. Here we applied a novel, region-based, multivariate pattern classification approach in combination with RSA to magnetoencephalography data to extract activity associated with qualitatively distinct processing stages of visual perception. We asked participants to name what they see whilst viewing bitonal visual stimuli of two categories predominantly shaped by either value-dependent or sensorimotor experience, namely faces and tools, and meaningless images. We aimed to disambiguate the spatiotemporal patterns of brain activity between the meaningful categories and determine which differences in their processing were attributable to either perceptual categorization\nDoc 8(Title: Title: Functional alteration of divided attention in people living with HIV based on a task-fMRI study.) Abstract: Impaired attention is a key feature of HIV-associated brain damage, and people living with HIV (PLWH) often have potential visual-auditory perceptual deficits. This study aimed to explore functional alterations in divided attention in PLWH using a parallel audio-visual spatiotemporal task with multimodal functional magnetic resonance imaging (fMRI) and to explore candidate neuroimaging markers of HIV-related attention impairment. Thirty-one cognitively unimpaired PLWH and 34 healthy controls (HC) completed a divided attention task during fMRI via a modified Posner paradigm. Behavioral performance and task-related brain activation were compared between the two groups. Seed-based whole-brain functional connectivity (FC) maps were computed in resting-state fMRI (rs-fMRI) using The PLWH showed lower accuracy than HC. Task-related brain activation was more extensive in PLWH, including increased activation in occipital/temporal lobes, plus frontal/parietal lobes, insula, and limbic system. Using The HIV impairs audio-visual divided attention, with fMRI revealing neural alterations in cognitively unimpaired PLWH. These findings suggest that task-related activation patterns and resting-state connectivity measures may serve as sensitive candidate markers of HIV-related brain involvement and help identify individuals at increased risk of cognitive decline, although longitudinal studies are needed to establish their prognostic value.\nDoc 9(Title: Title: EXPRESS: What Phonological Overlap Effects Reveal about the Role of Working Memory in Native and Nonnative Language Processing.) Abstract: The present study sheds light on effects of similarity-based interference due to phonological overlap, as well as working memory during silent reading in native and nonnative speakers

Generation process:  46%|████▌     | 6/13 [00:11<00:16,  2.29s/it]

[{'role': 'system', 'content': 'You are a biomedical expert. OUTPUT RULE: Answer in 2-3 sentences (30-50 words). State the key fact first, then supporting detail. Write like a PubMed abstract sentence. Answer the question using only the provided documents. Be direct and factual - no preamble, no caveats.\n\nDocuments:\nDoc 1(Title: Title: Seasonal longitudinal effects of winter birth on psychopathology, cognition, and functioning in schizophrenia-spectrum and affective disorders: Findings from the PsyCourse Study.) Abstract: Winter birth (WB) is a replicated risk factor for mental health conditions, potentially due to third-trimester Vitamin D deficiency and maternal viral infections. Beyond diagnosis, WB is associated with psychopathology, cognition, and functionality as epiphenomena. We analysed these outcomes in psychosis and affective disorders, considering illness duration and sex-specific effects. We included 535 individuals with schizophrenia-spectrum and 667 with affective disorders from the PsyCourse Study, evaluated at four time points over 18\xa0months. Participants were stratified by the birth season: winter vs. other seasons and by duration of illness (</≥5\xa0years). Psychopathology was assessed with the Positive and Negative Syndrome Scale (PANSS) for psychosis, Inventory of Depressive Symptomatology (IDS-C30) and Young Mania Rating Scale (YMRS) for affective disorders, functionality with the Global Assessment of Functioning Scale (GAF), and cognitive performance with Trail Making Tests A (TMT-A) and B (TMT-B), Verbal Digit Span, and Digit Symbol Test (DST). Linear mixed models adjusted for covariates were applied. No interaction effects between WB and diagnostic group or time remained significant after correction for multiple comparisons. In sex-stratified models, a significant WB\xa0×\xa0time interaction emerged for DST in females, with WB participants showing improvements over time in schizophrenia-spectrum disorders, and a crossover pattern in affective disorders. WB has no robust effect on long-term outcomes on schizophrenia-spectrum or affective disorders. Subtle, sex-dependent effects on cognition were observed in females, with divergent longitudinal patterns between diagnostic groups, suggesting a possible early-life influence that attenuates over the course of illness.\nDoc 2(Title: Title: Predictors of gains in social functioning after cognitive remediation in schizophrenia: Results from the multicenter ISST (Integrated Social Cognition and Social Skills Therapy) trial.) Abstract: Cognitive remediation therapy (CRT) is an evidence-based behavioral intervention that enhances functional outcomes in schizophrenia patients by improving cognition. However, not all patients benefit equally from CRT, and predictors of real-world functional improvement are poorly understood. This study aimed to identify patient-related baseline predictors of functional improvement by evaluating two distinct CRT approaches targeting different types of cognition: social cognition (Integrated Social Cognition and Social Skills Training, ISST) and neurocognition (Neurocognitive Remediation Therapy, NCRT). This secondary analysis used data from a large, multicenter randomized controlled trial. Participants with schizophrenia (N\xa0=\xa0174) were randomly assigned to ISST or NCRT for six months. Multiple linear regression analyses were performed to determine whether baseline demographic, cognitive, clinical, or functional characteristics predicted changes in real-world functioning, as measured by the Social and Occupational Functioning Assessment Scale. The Digit Symbol Substitution Test was the strongest and most consistent predictor of functional improvement. Lower baseline functioning also predicted greater gains, although only in multivariable models. Domain-specific predictors were identified for each intervention: better affect recognition predicted better outcomes in ISST, whereas verbal memory did so in NCRT. The CRT approaches studied here appear to be most effective for individuals with a more preserved baseline level of cognitive performance, especially in terms of processing speed. These findings support the use of brief cognitive assessments to guide CRT implementation and suggest that tailoring interventions to individual cognitive profiles may enhance treatment efficacy.\nDoc 3(Title: Title: Differential effects of cognitive behavioral therapy and pharmacotherapy on cognitive function in patients with major depressive disorder: A propensity-weighted longitudinal study.) Abstract: Neurocognitive dysfunction is a core feature of major depressive disorder (MDD), predicting relapse, persisting after remission, and hindering functional recovery. Although cognitive behavioral therapy (CBT) and pharmacotherapy are both established treatments, their differential effects on specific neurocognitive domains remain poorly characterized. We investigated the distinct neurocognitive effects of CBT and pharmacotherapy in patients with MDD. This study assessed 69 patients with MDD treated with either manual-based CBT combined with pharmacotherapy (n\xa0=\xa041) or pharmacotherapy alone (n\xa0=\xa028). Neurocognitive function was evaluated using the Brief Assessment of Cognition in Schizophrenia, whereas depressive and anxiety symptoms were assessed using the Montgomery-Åsberg Depression Rating Scale and Generalized Anxiety Disorder-7, respectively. Inverse probability of treatment weighting (IPTW) based on propensity scores balanced baseline characteristics between groups. Pre-post changes in neurocognitive domains were assessed using repeated-measures ANOVA. Robustness of the findings was evaluated using multiple imputation and mixed-effects models for repeated measures (MMRM). After IPTW adjustment, baseline characteristics were well balanced. A significant group × time interaction favoring CBT emerged for verbal memory (F[1,95]\xa0=\xa04.59, p\xa0=\xa0.035, η CBT combined with pharmacotherapy was associated with improvement in verbal memory compared to pharmacotherapy alone. These findings highlight the domain-specific neurocognitive benefits of combining CBT with pharmacotherapy and its potential to target neurocognitive dysfunction in MDD.\nDoc 4(Title: Title: Mental health in the perinatal period: bridging the gaps in care, evidence, and policy.) Abstract: Perinatal mental health has long been acknowledged as fundamental to the well-being of mothers and infants, yet the recognition of disorders such as postpartum depression, anxiety, and - far less commonly - psychosis still lags behind clinical need. Even where validated screening tools exist, detection remains inconsistent, and many women navigate pregnancy and the postpartum period with symptoms that go unspoken or unnoticed. In some high-income settings, suicide has emerged as a leading contributor to maternal mortality, a reminder that the health consequences of these conditions extend beyond emotional distress and reflect deeper systemic failings. In this opinion paper, we draw on recent developments across epidemiology, neuroscience, psychology, and health-system research to consider why perinatal mental health continues to occupy an uncertain place in routine care. Fragmented service pathways, variability in provider training, and uneven adoption of evidence-supported interventions create persistent gaps between what is known and what is practiced. We highlight examples - stepped-care models, collaborative teams, and digital supports - that illustrate how more coherent systems could function, even if implementation remains uneven. Although a wide range of effective interventions exists, their practical reach is limited by sociocultural norms, structural constraints, and resource imbalances. Understanding these influences together - not in isolation - helps clarify why progress has been slower than the evidence might suggest. Meaningful improvement will depend on strengthening cross-sector integration, expanding scalable technologies, and tailoring policy responses to local realities. Sustained investment in perinatal mental health offers long-term benefits for families and communities and should be regarded as central to modern maternal care.\nDoc 5(Title: Title: Brain function in language and associated networks in non- or minimally verbal children.) Abstract: Language is universal in humans, develops robustly in infancy and is rarely absent entirely in aphasia following strokes. Non- or minimally verbal children, in whom language has not developed by school age in either production or comprehension, thus provide an unparalleled window into the human brain when language function is minimal. Yet insights from functional MRI are absent. Here we report results from a first study of intrinsic connectivity in nine non- or minimally verbal children with autism spectrum disorder scanned under sedation with propofol, along with eight typically developing children (scanned awake), using resting-state functional MRI. We targeted both functional connectivity and anatomically constrained, generative effective connectivity in speech and language regions, the insula and associated networks and the hippocampus. Identical analyses were applied to an independent resting-state MRI dataset of healthy adults scanned both under propofol and while awake, to evaluate sedation confounds. Non- or minimally verbal children with autism spectrum disorder, compared to their neurotypical peers, showed a widespread pattern of hypoconnectivity in auditory speech perception, fronto-temporal and semantic processing regions, which extended further to the insula and the hippocampus. Effective connectivity results selectively replicated these patterns, which correlated with Autism Diagnostic Observation Schedule behavioural scores within the group of non- or minimally verbal children with autism spectrum disorder. This hypoconnectivity pattern extended neither to the adults scanned under propofol, nor to the visual cortex used as a control region in non- or minimally verbal children with autism spectrum disorder, supporting that this pattern of results is not explained by sedation. Together, this first evidence from intrinsic connectivity reveals a broad pattern of underconnectivity across key cognitive networks, which provides a neural correlate for the significant breakdown of language-related cognitive functions in this population.\nDoc 6(Title: Title: Neural Mechanisms of Bidirectional Visuo-Linguistic Transformation in Interactive Communication.) Abstract: Human communication requires the flexible transformation of visual input into verbal descriptions and the reconstruction of mental imagery from language. However, the neural mechanisms underlying these bidirectional transformations during social interaction remain poorly understood. Using hyperscanning fMRI and a role-switching communicative task, we investigated how individuals alternately encode visual stimuli into language and decode language into mental imagery within an interactive context. Whole-brain analyses identified brain regions implicated in these processes. Based on these findings, we selected three key regions-the inferior frontal gyrus (IFG), fusiform face area (FFA), and intraparietal sulcus (IPS)-and applied dynamic causal modeling (DCM) to examine their effective connectivity. The DCM results revealed that connectivity among IFG, FFA, and IPS dynamically reconfigures to support role-dependent shifts between top-down and bottom-up information flow. These findings highlight a flexible, coordinated neural architecture that integrates visual and linguistic information, offering new insights into how communication arises from the interplay between perceptual and language systems.\nDoc 7(Title: Title: Factors Affecting Subjective Perception of Recovery in Individuals With Schizophrenia: The Role of Metacognitive Beliefs and Cognitive Insight.) Abstract: To examine the effect of metacognitive beliefs and cognitive insight on subjective perception of recovery in individuals with schizophrenia. Participants in the current descriptive cross-sectional and correlational study comprised 133 individuals with schizophrenia being treated in the psychiatry clinic of a training and research hospital in Türkiye. Data were collected using a Personal Information Form, Metacognition Questionnaire-30 (MCQ-30), Beck Cognitive Insight Scale (BCIS), and Subjective Recovery Assessment Scale (SubRAS). Descriptive statistics, bivariate analysis, and hierarchical regression analysis were used to analyze the data. Participants\' MCQ-30, BCIS, and SubRAS scores were 84.45 ( Results of the current study can guide psychiatric-mental health nurses to develop specific interventions and programs to support subjective recovery in individuals with schizophrenia and improve their mental health outcomes.\nDoc 8(Title: Title: The Immediate and Sustained Effects of Multi-Session Biparietal Transcranial Direct Current Stimulation on Insight in Schizophrenia.) Abstract: Impaired insight into illness affects up to 95% of individuals with schizophrenia, depending on the stage of illness, and is a predictor of antipsychotic nonadherence and poor clinical outcomes. Despite its importance, no effective treatment exists. Interhemispheric imbalance in frontoparietal regions may serve as a biomarker of impaired insight into illness and target for transcranial direct current stimulation (tDCS). Meta-analyses suggest that sham-controlled multisession tDCS applied to frontotemporoparietal areas improves insight in schizophrenia. However, no randomized controlled tDCS trial has targeted the posterior parietal areas to improve insight into illness. We hypothesized that multisession biparietal tDCS would lead to both immediate (ie, following 2-weeks of tDCS) and sustained (ie, up to 4-weeks) improvement in insight in schizophrenia. Thirty-four participants with schizophrenia/schizoaffective disorder and impaired insight into illness were randomized to receive either active (n\u2009=\u200918) or sham (n\u2009=\u200916) biparietal tDCS (anodal/cathodal:P4/P3), administered twice daily over 10\xa0days. Insight was assessed using the VAGUS Insight into Psychosis scale at baseline pre-treatment, post-treatment, and weekly for 4\xa0weeks. Linear mixed-effects models compared estimated marginal mean VAGUS scores between conditions, with and without adjusting for Intelligence Quotient (IQ), illness severity, and clozapine use. Active tDCS significantly improved average VAGUS scores immediately following and up to 4\xa0weeks post-treatment. Biparietal tDCS appears to be a promising intervention for improving insight in schizophrenia. Future research should explore its adjunctive use with medication to enhance treatment adherence.\nDoc 9(Title: Title: Categorization for Faces and Tools-Two Classes of Objects Shaped by Different Experience-Differs in Processing Timing, Brain Areas Involved, and Repetition Effects.) Abstract: The brain mechanisms that integrate the separate features of sensory input into a meaningful percept depend upon the prior experience of interaction with the object and differ between categories of objects. Recent studies using representational similarity analysis (RSA) have characterized either the spatial patterns of brain activity for different categories of objects or described how category structure in neuronal representations emerges in time, but never simultaneously. Here we applied a novel, region-based, multivariate pattern classification approach in combination with RSA to magnetoencephalography data to extract activity associated with qualitatively distinct processing stages of visual perception. We asked participants to name what they see whilst viewing bitonal visual stimuli of two categories predominantly shaped by either value-dependent or sensorimotor experience, namely faces and tools, and meaningless images. We aimed to disambiguate the spatiotemporal patterns of brain activity between the meaningful categories and determine which differences in their processing were attributable to either perceptual categorization\nDoc 10(Title: Title: The mind\'s eyes: Distinct neural correlates of spatial and object imagery.) Abstract: Mental imagery has long been central to understanding human cognition, yet its neural basis remains debated. Although neuroimaging studies often treat mental imagery as a unitary construct, behavioral research suggests a dissociation between object imagery (visualizing static objects in detail) and spatial imagery (visualizing dynamic transformations of objects and their relations). To test whether these forms of imagery rely on distinct neural systems, we conducted a pre-registered activation likelihood estimation (ALE) meta-analysis of 46 fMRI and PET studies (N\u202f=\u202f591; 772 foci). Conjunction analyses revealed overlapping activity across the medial frontal gyrus, precuneus, and inferior parietal lobule, suggesting a common frontoparietal network underlying general imagery processes. However, contrast analyses revealed patterns of activation dependent on imagery type (object vs. spatial). While spatial imagery was associated with unique activation in bilateral superior parietal lobules, consistent with dorsal visual stream involvement, object imagery elicited unique activation in left-lateralized frontoparietal and ventral stream regions. These findings parallel the dual-stream model of visual processing, suggesting that object imagery, like object recognition, engages the ventral "what" stream, whereas spatial imagery, like spatial perception and transformation, engages the dorsal "where/how" stream. Theoretically, this distinction offers a new perspective on an old debate, namely, the extent to which mental imagery mirrors perception. Our findings suggest that the answer depends on the type of imagery engaged, pointing to task-specific alignment between imagery and perception. Practically, these results invite a reappraisal of how imagery relates to academic, occupational, and everyday behaviors, raising new questions about how different forms of imagery may support distinct cognitive processes.\n'}, {'role': 'user', 'content': 'Question: What is verbal fluency and how is it affected in schizophrenia?\nAnswer:'}]
----asd-asd-a--------

Generation process:  54%|█████▍    | 7/13 [00:14<00:13,  2.31s/it]

[{'role': 'system', 'content': 'You are a biomedical expert. OUTPUT RULE: Answer in 2-3 sentences (30-50 words). State the key fact first, then supporting detail. Write like a PubMed abstract sentence. Answer the question using only the provided documents. Be direct and factual - no preamble, no caveats.\n\nDocuments:\nDoc 1(Title: Title: Non-linguistic comprehension, social inference and empathizing skills in autistic young adults, young adults with autistic traits and control young adults: Group differences and interrelatedness of skills.) Abstract: Despite increasing knowledge of social communication skills of autistic peole, the interrelatedness of different skills such as non-linguistic comprehension, social inference and empathizing skills is not much known about. A better understanding of the complex interplay between different domains of social communication helps us to develop assessment protocols for individuals with social communication difficulties. To compare the performances of autistic young adults, young adults with autistic traits identified in childhood and control young adults in social communication tasks measuring non-linguistic comprehension, social inference and empathizing skills. In addition, to examine associations between the different social communication measures. Autistic young adults (n = 34), young adults with autistic traits (n = 19) and control young adults (n = 36) completed the extra- and paralinguistic scales of the Assessment Battery for Communication (ABaCo), the Faux Pas Recognition Test, Social-Pragmatic Questions (SoPra) and the Empathy Quotient (EQ). Group differences were found in the performance in the ABaCo, SoPra and EQ scores. Compared with the control young adults, autistic young adults scored lower. The performance of the young adults in the autistic traits group fell in between the other two groups. There were no group differences in the Faux Pas Recognition Test. The variability within the groups was large in all measurements. In the control group, there was a significant correlation between EQ and SoPra scores and between the Faux Pas and SoPra scores. In the autistic group, a significant correlation was found between Faux Pas and SoPra scores. Also, other patterns were observed but these were not statistically significant. The young adults with autistic traits fell in between the control and autistic young adults, highlighting the presence of the continuum in the terms of features of social communication. The results support other current research that suggests that theory of mind and other social communication skills may not be universally or widely impaired in all autistic individuals without cognitive deficits. Although all tasks examined social communication skills, only a small number of significant correlations were found between test scores. This highlights that clinical conclusions about a person\'s social communication should be based on the outcomes of different types of methods measuring different aspects of social communication. It is clear that the interrelatedness of different social communication skills needs further research. What is already known on this subject For successful communication, the ability to infer others\' emotions, intentions and mental states is crucial. Autistic people have difficulty with many aspects of social communication. However, the associations between different aspects of social communication need to be better understood. What this paper adds to existing knowledge The unique contribution of this study is to compare the performance of autistic people not only with that of a control group but also with people with childhood autistic traits. This provides an understanding of the interrelatedness of different social communication skills in people with varying degrees of autistic traits. This study used four assessment methods focusing on three different social communication elements (non-linguistic comprehension, social inference and empathizing skills). These elements have complex relationships to one another, some being closely overlapping, some more distally related and some reflect more complex multifactorial elements. This study shows that although groups differ from each other in most of the assessments, the performance of different groups overlapped showing that many autistic young adults can perform well in non-linguistic and social inference tasks in structured assessment contexts. What are the potential or actual clinical implications of this work? Our findings suggest that in the assessment of social communication, self-reports and clinical assessments can be used effectively together. They can complement each other, pointing out the strengths and weaknesses of a person, leading to more personalized therapeutic interventions.\nDoc 2(Title: Title: The human posterior cingulate, retrosplenial, and medial parietal cortex effective connectome, and implications for memory and navigation.) Abstract: The human posterior cingulate, retrosplenial, and medial parietal cortex are involved in memory and navigation. The functional anatomy underlying these cognitive functions was investigated by measuring the effective connectivity of these Posterior Cingulate Division (PCD) regions in the Human Connectome Project-MMP1 atlas in 171 HCP participants, and complemented with functional connectivity and diffusion tractography. First, the postero-ventral parts of the PCD (31pd, 31pv, 7m, d23ab, and v23ab) have effective connectivity with the temporal pole, inferior temporal visual cortex, cortex in the superior temporal sulcus implicated in auditory and semantic processing, with the reward-related vmPFC and pregenual anterior cingulate cortex, with the inferior parietal cortex, and with the hippocampal system. This connectivity implicates it in hippocampal episodic memory, providing routes for "what," reward and semantic schema-related information to access the hippocampus. Second, the antero-dorsal parts of the PCD (especially 31a and 23d, PCV, and also RSC) have connectivity with early visual cortical areas including those that represent spatial scenes, with the superior parietal cortex, with the pregenual anterior cingulate cortex, and with the hippocampal system. This connectivity implicates it in the "where" component for hippocampal episodic memory and for spatial navigation. The dorsal-transitional-visual (DVT) and ProStriate regions where the retrosplenial scene area is located have connectivity from early visual cortical areas to the parahippocampal scene area, providing a ventromedial route for spatial scene information to reach the hippocampus. These connectivities provide important routes for "what," reward, and "where" scene-related information for human hippocampal episodic memory and navigation. The midcingulate cortex provides a route from the anterior dorsal parts of the PCD and the supracallosal part of the anterior cingulate cortex to premotor regions.\nDoc 3(Title: Title: Mental health in the perinatal period: bridging the gaps in care, evidence, and policy.) Abstract: Perinatal mental health has long been acknowledged as fundamental to the well-being of mothers and infants, yet the recognition of disorders such as postpartum depression, anxiety, and - far less commonly - psychosis still lags behind clinical need. Even where validated screening tools exist, detection remains inconsistent, and many women navigate pregnancy and the postpartum period with symptoms that go unspoken or unnoticed. In some high-income settings, suicide has emerged as a leading contributor to maternal mortality, a reminder that the health consequences of these conditions extend beyond emotional distress and reflect deeper systemic failings. In this opinion paper, we draw on recent developments across epidemiology, neuroscience, psychology, and health-system research to consider why perinatal mental health continues to occupy an uncertain place in routine care. Fragmented service pathways, variability in provider training, and uneven adoption of evidence-supported interventions create persistent gaps between what is known and what is practiced. We highlight examples - stepped-care models, collaborative teams, and digital supports - that illustrate how more coherent systems could function, even if implementation remains uneven. Although a wide range of effective interventions exists, their practical reach is limited by sociocultural norms, structural constraints, and resource imbalances. Understanding these influences together - not in isolation - helps clarify why progress has been slower than the evidence might suggest. Meaningful improvement will depend on strengthening cross-sector integration, expanding scalable technologies, and tailoring policy responses to local realities. Sustained investment in perinatal mental health offers long-term benefits for families and communities and should be regarded as central to modern maternal care.\nDoc 4(Title: Title: Intervention Effects on Phonological Processing in Children With Developmental Speech and/or Language Disorder: A Systematic Review and Meta-Analysis of Studies With Group Design.) Abstract: Challenges in phonological processing are prevalent in children with developmental speech and/or language disorders and are associated with their language acquisition and later reading skills. A recent systematic review and meta-analysis from the same project of studies with a group design on the effects of interventions on output phonology, found that oral language interventions have a positive effect on output phonology, specifically speech production accuracy. These interventions are expected to impact the phonological representational level as well and, thus, also affect phonological processing skills in this population. However, no prior systematic reviews or meta-analyses have been conducted on this topic. We conducted a systematic literature review and meta-analysis to investigate the effectiveness of oral language interventions on children and adolescents\xa0with developmental speech and/or language disorders, focusing on phonological processing as the primary outcome measure, including phonological awareness, phonological retrieval efficiency, and short-term memory. The systematic review was pre-registered (PROSPERO ID: CRD42017076075) and followed the PRISMA guidelines. A search for oral language interventions in children and adolescents\xa0with developmental speech and/or language disorders (mean age, 3-18 years) was conducted across seven databases (PubMed, Web of Science, ERIC, Cochrane Library, PsycINFO, Scopus, LLBA) for studies published between January 2006 and May 2023. We included studies with a group design and phonological processing as the outcome measure. The Cochrane risk of bias tool was used for study appraisal. Individual and average standardised mean differences g were used in the meta-analysis. We also explored the influence of various moderators. We identified 22 studies that met the inclusion criteria. Overall, the risk of bias was low to moderate. Significant and large effect sizes were found in pre-post studies with control groups, showing improvements post-intervention in phonological awareness, g\xa0=\xa00.710, p\xa0<\xa00.001, 95% CI [0.504, 0.917], and phonological short-term memory, g\xa0=\xa00.785, p\xa0=\xa00.010, 95% CI [0.192, 1.279]. Some moderator variables emerged, for example, larger effects when the interventions were based on an integrated theoretical approach, applied in small groups, or when they had processing targets. The results demonstrate that oral language interventions can effectively improve specific phonological processing skills in children and adolescents\xa0with developmental speech and/or language disorders. The identification of key moderating factors provides valuable guidance for clinical practice. What is already known on the subject Children with developmental speech and/or language disorders often have difficulties in phonological processing that can hamper their reading development. Interventions are effective for speech production, but there are no previous systematic reviews or meta-analyses on their effects on the phonological processing skills of children and adolescents with developmental speech and/or language disorders. What this paper adds to existing knowledge We present empirical evidence of the effectiveness of oral language interventions in improving phonological processing (including phonological awareness and phonological short-term memory) in children and adolescents with developmental speech and/or language disorders. What are the potential or actual clinical implications of this work? Oral language interventions have a positive effect on the phonological processing skills of children and adolescents with developmental speech and/or language disorders. They may serve as an indirect means of support for their reading development.\nDoc 5(Title: Title: AI for Relational Reconnection and Social Support in Alzheimer\'s Disease: A Conceptual Framework for Socially Embedded Systems.) Abstract: Alzheimer\'s Disease (AD) has traditionally been approached through a biomedical lens, focusing on neurodegenerative markers such as amyloid-β plaques and tau protein accumulation. However, clinical evidence increasingly demonstrates that social dysfunction, which including identity confusion, emotional withdrawal, and breakdowns in social roles. This article reconceptualizes Alzheimer\'s disease as a disorder in which the primary dimension of decline lies in social relationship management capacity (SRMC), while recognizing that neurobiological and cognitive deterioration remain integral to its manifestation and progression. SRMC refers to a person\'s ability to identify, interpret, maintain, and regulate social ties embedded in complex networks. This article introduces a conceptual and technical framework for a socially embedded artificial intelligence (AI) framework designed to recognize and compensate for the deterioration of SRMC in AD. Drawing on social capital theory, affective computing, and neural social cognition research, this framework proposes a four-dimensional intervention model: relationship recognition, relationship learning, relationship establishment, and relationship management. By aligning cutting-edge AI techniques with the lived social reality of individuals with AD, this approach not only provides a new path for supportive care but also reorients ethical and technological discourse toward sustaining social personhood in the face of neurodegeneration.\nDoc 6(Title: Title: Social media use and early adolescent brain structure: Findings from the Adolescent Brain Cognitive Development (ABCD) Study.) Abstract: Many adolescents initiate social media use during early adolescence, but the associations of early social media use with neurodevelopment have not been extensively studied. We utilized neuroimaging data from the U.S. Adolescent Brain Cognitive Development (ABCD) Study to investigate the association of social media use (hours per day) or social media addiction (Social Media Addiction Questionnaire) with brain morphology in early adolescence. We analyzed data from 7,614 participants with high-quality structural MRI and complete covariate data at Year 2 (2018-2020, ages 10-13). In addition to pre-defined cortical regions, we performed vertexwise analysis using the Fast and Efficient Mixed Effects Algorithm (FEMA), which is unbiased by arbitrary borders between atlas-based brain regions and provides higher spatial resolution. After adjusting for demographics, socioeconomic factors, genetic ancestry, non-social media screen time, and scanner features, higher average daily social media use was significantly associated with lower total cortical thickness and volume. Region-of-interest (ROI) and vertexwise analysis identified broad regions with lower cortical thickness across the prefrontal cortices, temporal lobe, occipital lobe, and parietal lobe associated with social media use and social media addiction, which overlap with key nodes of the default mode network, prefrontal executive control networks, and visual processing and attention networks. Social media addiction was not significantly associated with differences in brain morphology in ROI analysis. Our findings in a large nationwide population demonstrate that higher social media use is associated with variation in cortical morphology, but future studies are required to establish the directionality of this association.\nDoc 7(Title: Title: A brain circuit of bidirectional modulation of social and nonsocial cognition by androgens and estrogens in male mice.) Abstract: Androgens and estrogens rapidly influence brain function and behaviors critical to social species, including social recognition, which is essential for group living and modulating social interactions. The specific brain regions involved and their hormonal regulation remain poorly understood. This regulation is complex, as the main circulating androgen, testosterone (T), is metabolized into estrogenic (17β-estradiol, E2) and androgenic (dihydrotestosterone, DHT) compounds, meaning its actions can be mediated through both androgen (AR) and estrogen receptors (ERs). This study identifies an estrogen-regulated, social recognition-specific brain circuit, demonstrating that T and E2, but not DHT, interact with the arginine-vasopressin (AVP) system in the bed nucleus of the stria terminalis (BNST)-lateral septum (LS) pathway to promote social recognition in male mice. T, E2, and DHT all facilitated social recognition and impaired object recognition within forty minutes of infusion into the BNST, but only the effects of T and E2 were blocked by an AVP receptor 1a (V1aR) antagonist, suggesting distinct mechanisms underlie the facilitation of social recognition by estrogens and androgens. Using CRISPR/Cas9 to selectively knock down AR, ERα, ERβ, or G protein-coupled estrogen receptor (GPER) in the BNST of male mice four weeks before steroid infusion, we found that ERα and ERβ (but not GPER) are necessary for T and E2 to rapidly facilitate social recognition, whereas DHT acts through AR. Our findings highlight the distinct roles of AR and ERs in the modulation of social recognition by steroid hormones, revealing redundant and nonoverlapping mechanisms of androgens and estrogens in the functioning of the male social brain.\nDoc 8(Title: Title: Reading the room: Autistic traits, gaze behaviour, and the ability to infer social relationships.) Abstract: Individuals high in autistic traits can have difficulty understanding verbal and non-verbal cues, and may display atypical gaze behaviour during social interactions. The aim of this study was to examine differences among neurotypical individuals with high and low levels of autistic traits with regard to their gaze behaviour and their ability to assess peers\' social status accurately. Fifty-four university students who completed the 10-item Autism Quotient (AQ-10) were eye-tracked as they watched six 20-second video clips of people ("targets") involved in a group decision-making task. Simulating natural, everyday social interactions, the video clips included moments of debate, humour, interruptions, and cross talk. Results showed that high-scorers on the AQ-10 (i.e., those with more autistic traits) did not differ from the low-scorers in either gaze behaviour or assessing the targets\' relative social status. The results based on this neurotypical group of participants suggest that the ability of individuals high in autistic traits to read social cues may be preserved in certain tasks crucial to navigating day-to-day social relationships. These findings are discussed in terms of their implications for theory of mind, weak central coherence, and social motivation theories of autism.\nDoc 9(Title: Title: Triple-Network Functional Connectivity in Adolescents 

Generation process:  62%|██████▏   | 8/13 [00:15<00:10,  2.08s/it]

[{'role': 'system', 'content': 'You are a biomedical expert. OUTPUT RULE: Answer in 2-3 sentences (30-50 words). State the key fact first, then supporting detail. Write like a PubMed abstract sentence. Answer the question using only the provided documents. Be direct and factual - no preamble, no caveats.\n\nDocuments:\nDoc 1(Title: Title: The human posterior cingulate, retrosplenial, and medial parietal cortex effective connectome, and implications for memory and navigation.) Abstract: The human posterior cingulate, retrosplenial, and medial parietal cortex are involved in memory and navigation. The functional anatomy underlying these cognitive functions was investigated by measuring the effective connectivity of these Posterior Cingulate Division (PCD) regions in the Human Connectome Project-MMP1 atlas in 171 HCP participants, and complemented with functional connectivity and diffusion tractography. First, the postero-ventral parts of the PCD (31pd, 31pv, 7m, d23ab, and v23ab) have effective connectivity with the temporal pole, inferior temporal visual cortex, cortex in the superior temporal sulcus implicated in auditory and semantic processing, with the reward-related vmPFC and pregenual anterior cingulate cortex, with the inferior parietal cortex, and with the hippocampal system. This connectivity implicates it in hippocampal episodic memory, providing routes for "what," reward and semantic schema-related information to access the hippocampus. Second, the antero-dorsal parts of the PCD (especially 31a and 23d, PCV, and also RSC) have connectivity with early visual cortical areas including those that represent spatial scenes, with the superior parietal cortex, with the pregenual anterior cingulate cortex, and with the hippocampal system. This connectivity implicates it in the "where" component for hippocampal episodic memory and for spatial navigation. The dorsal-transitional-visual (DVT) and ProStriate regions where the retrosplenial scene area is located have connectivity from early visual cortical areas to the parahippocampal scene area, providing a ventromedial route for spatial scene information to reach the hippocampus. These connectivities provide important routes for "what," reward, and "where" scene-related information for human hippocampal episodic memory and navigation. The midcingulate cortex provides a route from the anterior dorsal parts of the PCD and the supracallosal part of the anterior cingulate cortex to premotor regions.\nDoc 2(Title: Title: Effects of electroacupuncture at Zusanli on pain-perception-related brain nuclei in KOA mice: a study on cortical and subcortical c-fos expression.) Abstract: Electroacupuncture is widely accepted to treat pain related conditions, but detailed mechanisms remain unknown. To explore cortical and subcortical subnuclei involved in electroacupuncture stimulation (EAS) analgesia by observing EAS\'s analgesic efficacy and c-fos expression changes, providing a basis for neural circuit research and clinical transcranial magnetic stimulation (TMS) therapy. A chronic inflammatory pain model was established using knee osteoarthritis (KOA). Bilateral Zusanli was selected for electroacupuncture intervention. Von Frey test, open field test, elevated plus maze, and tail suspension test, and immunohistochemical staining were performed. Changes in mechanical pain threshold and pain-related emotional behaviors and distribution of c-fos positive cells in cortical and subcortical nuclei. Electroacupuncture significantly increased mechanical pain thresholds in KOA model mice. KOA modeling caused c-fos downregulation in the motor cortex, insular cortex, secondary auditory cortex, dorsal peduncular cortex, temporal association cortex, caudate putamen, lateral septal nucleus, accumbens nucleus, and the anterior cortical amygdaloid area. Electroacupuncture at Zusanli reversed these changes, upregulating c-fos in abovementioned brain regions, and additionally upregulated c-fos expression in the granular insular cortex, extended amydala. Inflammatory pain induces widespread inhibition of neuronal activity in cortical and subcortical nuclei. The core mechanisms of electroacupuncture analgesia may involve direct reversal of abnormal inhibition in the lateral septal nucleus, caudate putamen, accumbens nucleus, and the anterior cortical amygdaloid area and activation of the granular insular cortex, medial septal nucleus and the extended amygdala for pain information integration.\nDoc 3(Title: Title: Visual processing of manipulable objects in the ventral stream is modulated by inputs from parietal action systems.) Abstract: Functional object use requires the integration of visuomotor representations processed in the dorsal visual pathway with representations of surface texture and material composition of objects, processed in the ventral visual pathway. Do regions in the ventral visual pathway project outputs to dorsal visual pathway action systems, or are the outputs of the dorsal visual pathway communicated to the ventral visual pathway to modulate processing? And what are the white matter pathways that mediate structural connectivity in support of functional object use? Here we show that the left inferior parietal cortex, a region within the dorsal visual pathway, exerts a direct effect on neural responses in ventral occipital-temporal cortex during visual processing of manipulable objects. We studied a series of consecutively enrolled participants in the pre-operative phase of their neurosurgical care (N = 109) with lesions principally distributed throughout the left hemisphere. Participants completed an object processing category localizer functional MRI experiment in which they viewed images of manipulable objects, animals, faces, and places. We then used Voxel-based Lesion-Activity Mapping (VLAM), a technique in which functional responses in a region-of-interest are used to predict variance in voxel-wise lesion incidence throughout the brain. In the VLAM analyses performed here, we found that lesions to the left anterior intraparietal sulcus and left supramarginal gyrus, two inferior parietal regions known to support object-directed grasping and manipulation, respectively, cause reduced neural responses for manipulable objects (compared to faces, places and animals) in the fusiform gyrus. Parietal lesions do not affect neural responses during visual processing of places in the same region of the fusiform gyrus, even though places elicit stronger responses in the fusiform gyrus than manipulable objects. Seventy-five of 109 participants took part in a common diffusion MRI protocol, permitting a connectome-wide analyses relating white matter fiber integrity to the strength of functional responses for manipulable objects in the left fusiform gyrus. This analysis demonstrated that the descending portion of the left arcuate fasciculus mediates parietal-totemporal lobe connectivity for manipulable objects, supporting the integration of action representations with conceptual and perceptual attributes of objects. By combining voxel-based and connectome-wide lesion-symptom mapping methods with functional MRI, we have demonstrated that structural connectivity to dorsal visual pathway areas supporting skilled manual action shape category-specific neural responses for manipulable objects within the ventral visual pathway.\nDoc 4(Title: Title: Emotive language activates right temporoparietal junction, while referential language activates the left hemispheric network.) Abstract: Language has referential and emotive uses. Referential language depicts events and can be verified or falsified by comparison with the event, whereas emotive language lacks the events upon which one can determine the truth value of the sentence. Using functional magnetic resonance imaging (fMRI), we investigated the brain mechanisms of the processing of the two semantically distinct forms of language in a paradigm of empathy for pain conveyed through single short sentences. In the emotive condition, subjective expressions of pain, such as "I have a toothache", were used. In the referential condition, an objective description of events in which an individual would experience pain, such as "I cut my finger", were presented. Assuming each stimulus elicits activation proportional to pain intensity ratings, we combined referential and emotive conditions and performed an analysis with a parametric modulation model. It revealed activation in the anterior cingulate cortex and, slightly below the threshold, the anterior insula, that are involved in the perception of one\'s own pain. Without pooling the two conditions, only the referential condition yielded activation in the two regions. Crucially, although both emotive and referential language activated multiple regions, emotive sentences activated the right temporoparietal junction, whereas referential sentences activated the precuneus/retrosplenial cortex, parahippocampal cortex, and the language network in the left hemisphere. These results suggest that a complementary interhemispheric network supports the processing of both types of language.\nDoc 5(Title: Title: Working memory for location and time: activity in prefrontal area 46 relates to selection rather than maintenance in memory.) Abstract: The role of the dorsal prefrontal cortex in working memory remains controversial. Influential proposals include a role in the maintenance of domain-specific information, and the processes of executive functions on remembered information. We used event-related functional magnetic resonance imaging to demonstrate a functional dissociation within prefrontal cortex in terms of the components of complex working memory tasks. The maintenance in working memory of spatial locations and their temporal order was associated with activation of area 8 and intraparietal cortex. In contrast, the selection of one location, according to its order, was associated with a distinct frontoparietal network, including dorsolateral prefrontal area 46, ventrolateral prefrontal cortex and anterior cingulate cortex and medial parietal cortex. The different contributions of these areas to selection are considered in the light of recent electrophysiological and lesion studies. We suggest a general role of the dorsolateral prefrontal area 46 in attentional selection, including selection from within working memory.\nDoc 6(Title: Title: Neural correlates of processing situational relationships between a part and the whole: an fMRI study.) Abstract: Daily situations involve many objects and behaviors. To comprehend the meaning of situations, the relationships between objects, behaviors, and the situational context are important. To reveal the cortical networks involved in processing these relationships we used functional magnetic resonance imaging to compare brain activation during processing of behavior-situation and object-situation relationships. Each session examined two aspects of situational relationship processing: monitoring of the situational relationship and responses to irrelevant relationships. Monitoring was analyzed by comparing cortical activation during a situational relevance judgment task with that during a physical appropriateness judgment task. Responses were analyzed by comparing neural responses to situationally irrelevant and situationally relevant components. The left medial frontal cortex, fusiform gyrus, inferior frontal gyrus, calcarine sulcus, right anterior middle temporal gyrus, orbitoinsular junction, and occipito-temporo-parietal junction were commonly activated while monitoring relationships of both types. The right anterior middle temporal gyrus and orbitoinsular junction were considered to have roles in implicit monitoring because they were more deactivated during physical judgment tasks than during the resting state; this deactivation seemed to reflect unconscious situational monitoring in the resting state. Other regions seemed to be linked to explicit conscious monitoring. Responses to irrelevance were linked to separate and category-specific cortical activation in the left medial frontal cortex and frontal pole for behavioral irrelevance and in the left orbitofrontal cortex for irrelevant objects. We demonstrated that the hierarchical structure of processing situational relationships consisted of implicit monitoring, explicit monitoring, and category-specific responses to irrelevance.\nDoc 7(Title: Title: Situation model manipulations differently engage semantic and default mode networks during narrative comprehension.) Abstract: Narrative comprehension involves creating a mental representation of the events of the story: a "situation model". Maintaining a situation model is thought to be supported by the Default Mode Network (DMN), but recent work suggests that the semantic system, and specifically the ventrolateral anterior temporal lobe (ATL), may play a role in reflecting on and restructuring the situation model via internally-driven or endogenous semantic processing. The present study used fMRI to investigate how ATL and DMN brain regions respond under varying exogenous, or input-driven, and endogenous processing demands when reading social and non-social stories. We studied neural responses to three types of situation model manipulation: 1) add-incorporating new information into the situation model, 2) use-using the information in the situation model to support comprehension of narrative language input, and 3) reconfigure-restructuring the situation model. Relative to add, the use and reconfigure manipulations tended to elicit greater activation in regions of the DMN, including the dorsomedial prefrontal cortex, posterior cingulate cortex and precuneus, as well as the bilateral superior, middle and inferior ATL. Relative to non-social stories, add and use manipulations in social stories engaged the left anterior middle and superior temporal gyri and inferior parietal lobule (IPL), whereas reconfigure manipulations engaged the right superior, middle and inferior frontal gyri and IPL. The present results inform a developing framework for coordination between the ATL and DMN during narrative comprehension.\nDoc 8(Title: Title: Social supports moderate the effects of child adversity on neural correlates of threat processing.) Abstract: Child abuse and other forms of adversity are associated with alterations in threat processing and emotion regulation brain circuits. The goal of the current investigation is to determine if the availability of positive social support can ameliorate the negative impact of adversity on these brain systems. Subjects included 55 children ages 7-16 (X\u2009=\u200911.8, SD\u2009=\u20092.0). Approximately one-third of the cohort had no significant history of adversity, one-third had a history of moderate adversity, and one-third had a history of severe adversity. Brain imaging was conducted at the University of Vermont using a 3.0\u2009T Philips scanner. The Emotional Go-NoGo task with fearful and calm facial stimuli was used to assess the neural correlates of threat processing and emotion regulation in children during functional magnetic resonance imaging (fMRI). Dimensional measures of anxiety, social supports, and children\'s adverse experiences were also obtained. A conjunction analysis was used to test if trauma-related brain activation in responding to fearful vs. calm targets was impacted by social support. This approach identified multiple activation foci, including a cluster extending from the left amygdala to several other key brain regions involved in emotion regulation, including the orbitofrontal cortex, anterior cingulate cortex (ACC), anterior insula, nucleus accumbens, and frontal pole (Family Wise Error (FWE) correction, p\u2009<\u20090.05). Greater social support may reduce the effect that adversity has on neural processing of threat stimuli, consistent with the protective role of positive supports in promoting resilience and recovery demonstrated in the literature.\nDoc 9(Title: Title: Neurocognitive effects of interest on reward valuation and effort investment in boring contexts.) Abstract: Monotonous tasks are common in academic and professional settings, yet sustaining motivation and effort in such contexts remains a persistent challenge. This research examined whether inserting a brief episode of interest into an otherwise boring, incentivized task could replenish cognitive and motivational resources and sustain effort. Two competing accounts were tested. The contrast-effect hypothesis predicted that once interest was withdrawn, the remaining rewards would lose their impact, and effort would diminish. In contrast, the transfer-effect hypothesis proposed that prior interest would leave a motivational trace that preserves the effectiveness of the rewards. Study 1 (behavioral study) employed a typing task, while Study 2 (fMRI study) used a social preference guessing task, both with performance-contingent monetary incentives. In both studies, participants in the experimental group completed a boring-interesting-boring sequence, whereas those in the control group experienced a boring-neutral-boring sequence. Across two studies, results consistently supported the transfer-effect hypothesis, demonstrating that prior interest enhanced subsequent engagement, effort, and reward sensitivity, even when monetary incentives were reduced. Neuroimaging results further revealed activity in regions involved in reward processing (e.g., anterior cingulate cortex, anterior insula) and attentional control (e.g., lateral occipital cortex, inferior parietal lobule) even after interest was removed, suggesting a lingering motivational effect of interest. These findings integrate reinforcement learning and interest theories and suggest a practical strategy: sandwiching brief, interest-enhancing episodes between boring rewarded tasks can serve as a motivational reset, enabling effort and persistence in low-stimulation environments.\nDoc 10(Title: Title: The human posterior parietal cortex: effective connectome, and its relation to function.) Abstract: The effective connectivity between 21 regions in the human posterior parietal cortex, and 360 cortical regions was measured in 171 Human Connectome Project (HCP) participants using the HCP atlas, and complemented with functional connectivity and diffusion tractography. Intraparietal areas LIP, VIP, MIP, and AIP have connectivity from early cortical visual regions, and to visuomotor regions such as the frontal eye fields, consistent with functions in eye saccades and tracking. Five superior parietal area 7 regions receive from similar areas and from the intraparietal areas, but also receive somatosensory inputs and connect with premotor areas including area 6, consistent with functions in performing actions to reach for, grasp, and manipulate objects. In the anterior inferior parietal cortex, PFop, PFt, and PFcm are mainly somatosensory, and PF in addition receives visuo-motor and visual object information, and is implicated in multimodal shape and body image representations. In the posterior inferior parietal cortex, PFm and PGs combine visuo-motor, visual object, and reward input and connect with the hippocampal system. PGi in addition provides a route to motion-related superior temporal sulcus regions involved in social interactions. PGp has connectivity with intraparietal regions involved in coordinate transforms and may be involved in idiothetic update of hippocampal visual scene representations.\n'}, {'role': 'user', 'content': 'Question: What is the functional topography of the anterior cingulate cortex?\nAnswer:'}]
----asd-asd-a--------

Generation process:  69%|██████▉   | 9/13 [00:18<00:08,  2.17s/it]

[{'role': 'system', 'content': 'You are a biomedical expert. OUTPUT RULE: Answer in 2-3 sentences (30-50 words). State the key fact first, then supporting detail. Write like a PubMed abstract sentence. Answer the question using only the provided documents. Be direct and factual - no preamble, no caveats.\n\nDocuments:\nDoc 1(Title: Title: The human posterior cingulate, retrosplenial, and medial parietal cortex effective connectome, and implications for memory and navigation.) Abstract: The human posterior cingulate, retrosplenial, and medial parietal cortex are involved in memory and navigation. The functional anatomy underlying these cognitive functions was investigated by measuring the effective connectivity of these Posterior Cingulate Division (PCD) regions in the Human Connectome Project-MMP1 atlas in 171 HCP participants, and complemented with functional connectivity and diffusion tractography. First, the postero-ventral parts of the PCD (31pd, 31pv, 7m, d23ab, and v23ab) have effective connectivity with the temporal pole, inferior temporal visual cortex, cortex in the superior temporal sulcus implicated in auditory and semantic processing, with the reward-related vmPFC and pregenual anterior cingulate cortex, with the inferior parietal cortex, and with the hippocampal system. This connectivity implicates it in hippocampal episodic memory, providing routes for "what," reward and semantic schema-related information to access the hippocampus. Second, the antero-dorsal parts of the PCD (especially 31a and 23d, PCV, and also RSC) have connectivity with early visual cortical areas including those that represent spatial scenes, with the superior parietal cortex, with the pregenual anterior cingulate cortex, and with the hippocampal system. This connectivity implicates it in the "where" component for hippocampal episodic memory and for spatial navigation. The dorsal-transitional-visual (DVT) and ProStriate regions where the retrosplenial scene area is located have connectivity from early visual cortical areas to the parahippocampal scene area, providing a ventromedial route for spatial scene information to reach the hippocampus. These connectivities provide important routes for "what," reward, and "where" scene-related information for human hippocampal episodic memory and navigation. The midcingulate cortex provides a route from the anterior dorsal parts of the PCD and the supracallosal part of the anterior cingulate cortex to premotor regions.\nDoc 2(Title: Title: Visual cortical dynamics supporting predictable attentional capture.) Abstract: Visual behavior depends on the ability to prioritize relevant sensory information while filtering out distractions. Predictable sensory contexts enable more efficient behavior by altering sensory processing. Using laminar neurophysiology in macaque visual cortex measuring population spiking during a feature-based pop-out visual search task, we examined how predictable visual routines influence cortical columnar processing of sensory information. By manipulating predictability through attentional priming, we found improved behavioral performance with predictable stimulus arrays. These behavioral changes were supported by earlier neuronal attentional target selection driven by reduced variability in the sensory response to the predictable target stimulus and more homogeneous feedforward processing dynamics across the cortical column. More effective distractor suppression was driven by adapted feedforward processing of the more frequent distractor stimulus. Taken together, these changes implicate independent mechanisms for target enhancement and distractor suppression. Our results highlight how predictions from experience alter visual columnar processing to optimize attentional selection through streamlining feedforward signaling. Both target enhancement and distractor suppression are independently observable in visual cortex with different profiles of modulation as a function of predictability.Predictions produce stronger, more reliable feedforward responses to attention-capturing targets across the visual cortical layers.Better distractor suppression with stimulus predictability is driven by adapted sensory representations, not top-down inhibition. How do predictions help determine what catches our attention? It is well known that when primates repeatedly perform visuomotor tasks, they become more proficient. Using neural recordings across the layers of the visual cortex, Groot et al. demonstrate that more efficient feedforward processing of sensory information contributes to improved visual behavior under predictable sensory conditions. These findings highlight the crucial role of predictions in proactively shaping sensory representations to facilitate efficient attentive behavior.\nDoc 3(Title: Title: Lessons from human neuroimaging on the developing cerebellum in health and disease.) Abstract: The cerebellum is a critical structure for both motor and cognitive behaviors. Although the majority of human neuroimaging research has examined the cerebellum in adults, this "little brain" may be especially pivotal during development. Indeed, the cerebellum has a unique developmental timecourse relative to the cerebral cortex, suggesting that it may play a unique role in the development of motor and cognitive functions. Here, we review the literature on cerebellar development with a focus on neuroimaging studies in humans. We discuss several structural and functional MRI studies that examine the cerebellum across typical development from infancy through adulthood. We also discuss the links between the developmental time course of various cerebellar sub-regions and the emergence of core motor and cognitive functions. Finally, we investigate the consequences of cerebellar differences (and disorders that implicate the cerebellum) on motor control, language and communication, executive function, attention, and affective regulation.\nDoc 4(Title: Title: The mechanistic role of psychological expectations in human-humanoid robot cooperation.) Abstract: When collaborating, humans\' decisions are influenced by the perceived cooperative willingness of their partners, and choices are continuously adjusted based on such willingness. In this study, we manipulated the cooperative willingness of different kinds of partners (human vs. humanoid robots) and employed a Rescorla-Wagner (RW) reinforcement learning model to investigate how psychological expectations affect human cooperation with nonhuman agents (n\u202f=\u202f25 in the final analyses). The results showed similar overt behavioral performance, but distinct underlying learning dynamics and neural mechanisms depending on whether participants interacted with humans or humanoid robots. Specifically, the neural mechanisms underlying these decisions differed between partner types: Interactions with human agents elicited greater activation in reward-related regions of the putamen, whereas interactions with humanoid robot agents involved stronger activation in the precentral gyrus, a region implicated in embodied cognition. Moreover, participants exhibited distinct patterns of functional connectivity depending on the type of partner. Despite behavioral similarities, these findings highlight that psychological expectations shape decision making for human and humanoid robot partners through dissociable neural processes, reflecting type-specific cognitive representations. The findings advance our understanding of the psychological mechanisms underlying human-humanoid robot interaction and provide neuroscientific insight into the design of effective human-humanoid robot cooperation systems.\nDoc 5(Title: Title: EXPRESS: What Phonological Overlap Effects Reveal about the Role of Working Memory in Native and Nonnative Language Processing.) Abstract: The present study sheds light on effects of similarity-based interference due to phonological overlap, as well as working memory during silent reading in native and nonnative speakers. While prior research has mainly focused on syntactic complexity or ambiguity to gain insight into nonnative language processing and the role of working memory, the effects of phonological overlap have remained poorly understood. Using multiline texts with varying degrees of phonological overlap, we examined whether increased amounts of overlap disrupt online reading and offline recall, and whether effects differ across native and nonnative groups or vary as a function of working memory capacity. Results revealed that greater phonological overlap caused delays during online processing, but without impacting offline recall. Crucially, native and nonnative speakers experienced online interference similarly, and working memory modulated these effects in comparable ways across both groups. These results suggest convergence both in overt behavior and in how underlying cognitive resources are used. Findings are discussed with respect to their implications for theories of native-nonnative language processing differences and possible directions for further research.\nDoc 6(Title: Title: Role of the lateral habenula in memory through online processing of information.) Abstract: Our memory abilities, whether they involve short-term working memory or long-term episodic or procedural memories, are essential for our well-being, our capacity to adapt to constraints of our environment and survival. Therefore, several key brain regions and neurotransmitter systems are engaged in the processing of sensory information to either maintain such information in working memory so that it will quickly be used, and/or participate in the elaboration and storage of enduring traces useful for longer periods of time. Animal research has recently attracted attention on the lateral habenula which, as shown in rodents and non-human primates, seems to process information stemming in the main regions involved in memory processing, e.g., the medial prefrontal cortex, the hippocampus, the amygdala, the septal region, the basal ganglia, and participates in the control of key memory-related neurotransmitters systems, i.e., dopamine, serotonin, acetylcholine. Recently, the lateral habenula has been involved in working and spatial reference memories, in rodents, likely by participating in online processing of contextual information. In addition, several behavioral studies strongly suggest that it is also involved in the processing of the emotional valance of incoming information in order to adapt to particularly stressful situations. Therefore, the lateral habenula appears like a key region at the interface between cognition and emotion to participate in the selection of appropriate behaviors.\nDoc 7(Title: Title: Disrupting motor cortical regional activity during motor sequence skill training impairs human motor visuomotor skill acquisition and learning that is not sequence-specific.) Abstract: Implicit sequence and visuomotor skill learning is important for successful goal-directed behavior in everyday tasks. However, prior research has primarily relied on correlational methods to investigate the underlying neural mechanisms of sequence and visuomotor skill learning. To evaluate the necessary contributions of different motor cortical regions to both types of skill learning, we enrolled 62 neurotypical adults (41 female, 21 male) and delivered spatiotemporally resolved single-pulse transcranial magnetic stimulation (TMS) over either the premotor cortex (PMC) or primary motor cortex (M1) to transiently disrupt activity while participants practiced an implicit motor sequence task. We hypothesized that 1) PMC disruption would preferentially reduce sequence-specific skill acquisition (Experiment 1) and retention (Experiment 2) while 2) M1 disruption would diminish visuomotor skill acquisition and retention but not sequence learning. Our results demonstrated that TMS-based interference over both M1 and PMC did not disrupt implicit sequence-specific motor skill learning after training however, it did disrupt visuomotor skill acquisition and total learning that was not sequence-specific. Further, disruption of PMC activity had a greater effect on reducing visuomotor skill learning than M1 supporting a potentially distinct role of the PMC in the early stages of skill learning.\nDoc 8(Title: Title: Category-specific memory encoding in the medial temporal lobe and beyond: the role of reward.) Abstract: The medial temporal lobe (MTL), including the hippocampus (HC), perirhinal cortex (PRC), and parahippocampal cortex (PHC), is central to memory formation. Reward enhances memory through interplay between the HC and substantia nigra/ventral tegmental area (SNVTA). While the SNVTA also innervates the MTL cortex and amygdala (AMY), their role in reward-enhanced memory is unclear. Prior research suggests category specificity in the MTL cortex, with the PRC and PHC processing object and scene memory, respectively. It is unknown, however, whether reward modulates category-specific memory processes. Furthermore, no study has demonstrated clear category specificity in the MTL for encoding processes contributing to subsequent recognition memory. To address these questions, we had 39 healthy volunteers (27 for all memory-based analyses) undergo functional magnetic resonance imaging while performing an incidental encoding task pairing objects or scenes with high or low reward, followed by a next-day recognition test. Behaviorally, high reward preferably enhanced object memory. Neural activity in the PRC and PHC reflected successful encoding of objects and scenes, respectively. Importantly, AMY encoding effects were selective for high-reward objects, with a similar pattern in the PRC. The SNVTA and HC showed no clear evidence of successful encoding. This behavioral and neural asymmetry may be conveyed through an anterior-temporal memory system, including the AMY and PRC, potentially in interplay with the ventromedial prefrontal cortex.\nDoc 9(Title: Title: The mind\'s eyes: Distinct neural correlates of spatial and object imagery.) Abstract: Mental imagery has long been central to understanding human cognition, yet its neural basis remains debated. Although neuroimaging studies often treat mental imagery as a unitary construct, behavioral research suggests a dissociation between object imagery (visualizing static objects in detail) and spatial imagery (visualizing dynamic transformations of objects and their relations). To test whether these forms of imagery rely on distinct neural systems, we conducted a pre-registered activation likelihood estimation (ALE) meta-analysis of 46 fMRI and PET studies (N\u202f=\u202f591; 772 foci). Conjunction analyses revealed overlapping activity across the medial frontal gyrus, precuneus, and inferior parietal lobule, suggesting a common frontoparietal network underlying general imagery processes. However, contrast analyses revealed patterns of activation dependent on imagery type (object vs. spatial). While spatial imagery was associated with unique activation in bilateral superior parietal lobules, consistent with dorsal visual stream involvement, object imagery elicited unique activation in left-lateralized frontoparietal and ventral stream regions. These findings parallel the dual-stream model of visual processing, suggesting that object imagery, like object recognition, engages the ventral "what" stream, whereas spatial imagery, like spatial perception and transformation, engages the dorsal "where/how" stream. Theoretically, this distinction offers a new perspective on an old debate, namely, the extent to which mental imagery mirrors perception. Our findings suggest that the answer depends on the type of imagery engaged, pointing to task-specific alignment between imagery and perception. Practically, these results invite a reappraisal of how imagery relates to academic, occupational, and everyday behaviors, raising new questions about how different forms of imagery may support distinct cognitive processes.\nDoc 10(Title: Title: Contrastive learning explains the emergence and function of visual category-selective regions.) Abstract: Modular and distributed coding theories of category selectivity along the human ventral visual stream have long existed in tension. Here, we present a reconciling framework-contrastive coding-based on a series of analyses relating category selectivity within biological and artificial neural networks. We discover that, in models trained with contrastive self-supervised objectives over a rich natural image diet, category-selective tuning naturally emerges for faces, bodies, scenes, and words. Further, lesions of these model units lead to selective, dissociable recognition deficits, highlighting their distinct functional roles in information processing. Finally, these pre-identified units can predict neural responses in all corresponding face-, scene-, body-, and word-selective regions of human visual cortex, under a highly constrained sparse positive encoding procedure. The success of this single model indicates that brain-like functional specialization can emerge without category-specific learning pressures, as the system learns to untangle rich image content. Contrastive coding, therefore, provides a unifying account of object category emergence and representation in the human brain.\n'}, {'role': 'user', 'content': 'Question: What is the role of the prefrontal cortex in human behavior?\nAnswer:'}]
----asd-asd-a--------

Generation process:  77%|███████▋  | 10/13 [00:25<00:11,  3.79s/it]

[{'role': 'system', 'content': 'You are a biomedical expert. OUTPUT RULE: Answer in 2-3 sentences (30-50 words). State the key fact first, then supporting detail. Write like a PubMed abstract sentence. Answer the question using only the provided documents. Be direct and factual - no preamble, no caveats.\n\nDocuments:\nDoc 1(Title: Title: The mind\'s eyes: Distinct neural correlates of spatial and object imagery.) Abstract: Mental imagery has long been central to understanding human cognition, yet its neural basis remains debated. Although neuroimaging studies often treat mental imagery as a unitary construct, behavioral research suggests a dissociation between object imagery (visualizing static objects in detail) and spatial imagery (visualizing dynamic transformations of objects and their relations). To test whether these forms of imagery rely on distinct neural systems, we conducted a pre-registered activation likelihood estimation (ALE) meta-analysis of 46 fMRI and PET studies (N\u202f=\u202f591; 772 foci). Conjunction analyses revealed overlapping activity across the medial frontal gyrus, precuneus, and inferior parietal lobule, suggesting a common frontoparietal network underlying general imagery processes. However, contrast analyses revealed patterns of activation dependent on imagery type (object vs. spatial). While spatial imagery was associated with unique activation in bilateral superior parietal lobules, consistent with dorsal visual stream involvement, object imagery elicited unique activation in left-lateralized frontoparietal and ventral stream regions. These findings parallel the dual-stream model of visual processing, suggesting that object imagery, like object recognition, engages the ventral "what" stream, whereas spatial imagery, like spatial perception and transformation, engages the dorsal "where/how" stream. Theoretically, this distinction offers a new perspective on an old debate, namely, the extent to which mental imagery mirrors perception. Our findings suggest that the answer depends on the type of imagery engaged, pointing to task-specific alignment between imagery and perception. Practically, these results invite a reappraisal of how imagery relates to academic, occupational, and everyday behaviors, raising new questions about how different forms of imagery may support distinct cognitive processes.\nDoc 2(Title: Title: Network localization of functional and structural correlates of apathy in Parkinson\'s disease.) Abstract: Apathy is a prevalent and debilitating neuropsychiatric syndrome in Parkinson\'s disease (PD). While numerous functional and structural brain studies have investigated the neural correlates of PD with apathy (PD-A), their findings have often been inconsistent. Network neuroscience suggests that such a syndrome may be best understood as disruptions of distributed brain networks. We conducted a systematic review to identify whole-brain studies reporting functional or structural alterations in patients with PD-A compared to those without apathy (PD-NA), or studies correlating apathy severity. Significant peak coordinates (195 foci from 24 studies) were integrated using functional connectivity network mapping (FCNM), leveraging resting-state functional magnetic resonance imaging from 1,093 healthy Human Connectome Project (HCP) participants. We quantified spatial overlap between the PD-A-associated network and canonical brain networks. The FCNM analysis revealed that the spatially diverse brain regions previously reported in the PD-A literature converged onto a common functional connectivity network. This network predominantly involved the bilateral inferior frontal gyrus, bilateral anterior insula, bilateral dorsolateral prefrontal cortex, bilateral caudate nucleus, and bilateral thalamus. The PD-A associated network showed the highest spatial overlap with the ventral attention network (VAN; 34.05%), subcortical network (28.47%), and frontoparietal network (FPN; 24.89%). Robustness analyses confirmed these findings. Brain functional and structural correlates of apathy in PD converge on distributed networks involving the VAN, FPN, and subcortical circuits. Our network localization approach offers a unifying neurobiological framework for apathy in PD, potentially reconciling previous inconsistencies and informing the development of network-targeted interventions.\nDoc 3(Title: Title: Categorization for Faces and Tools-Two Classes of Objects Shaped by Different Experience-Differs in Processing Timing, Brain Areas Involved, and Repetition Effects.) Abstract: The brain mechanisms that integrate the separate features of sensory input into a meaningful percept depend upon the prior experience of interaction with the object and differ between categories of objects. Recent studies using representational similarity analysis (RSA) have characterized either the spatial patterns of brain activity for different categories of objects or described how category structure in neuronal representations emerges in time, but never simultaneously. Here we applied a novel, region-based, multivariate pattern classification approach in combination with RSA to magnetoencephalography data to extract activity associated with qualitatively distinct processing stages of visual perception. We asked participants to name what they see whilst viewing bitonal visual stimuli of two categories predominantly shaped by either value-dependent or sensorimotor experience, namely faces and tools, and meaningless images. We aimed to disambiguate the spatiotemporal patterns of brain activity between the meaningful categories and determine which differences in their processing were attributable to either perceptual categorization\nDoc 4(Title: Title: The human posterior cingulate, retrosplenial, and medial parietal cortex effective connectome, and implications for memory and navigation.) Abstract: The human posterior cingulate, retrosplenial, and medial parietal cortex are involved in memory and navigation. The functional anatomy underlying these cognitive functions was investigated by measuring the effective connectivity of these Posterior Cingulate Division (PCD) regions in the Human Connectome Project-MMP1 atlas in 171 HCP participants, and complemented with functional connectivity and diffusion tractography. First, the postero-ventral parts of the PCD (31pd, 31pv, 7m, d23ab, and v23ab) have effective connectivity with the temporal pole, inferior temporal visual cortex, cortex in the superior temporal sulcus implicated in auditory and semantic processing, with the reward-related vmPFC and pregenual anterior cingulate cortex, with the inferior parietal cortex, and with the hippocampal system. This connectivity implicates it in hippocampal episodic memory, providing routes for "what," reward and semantic schema-related information to access the hippocampus. Second, the antero-dorsal parts of the PCD (especially 31a and 23d, PCV, and also RSC) have connectivity with early visual cortical areas including those that represent spatial scenes, with the superior parietal cortex, with the pregenual anterior cingulate cortex, and with the hippocampal system. This connectivity implicates it in the "where" component for hippocampal episodic memory and for spatial navigation. The dorsal-transitional-visual (DVT) and ProStriate regions where the retrosplenial scene area is located have connectivity from early visual cortical areas to the parahippocampal scene area, providing a ventromedial route for spatial scene information to reach the hippocampus. These connectivities provide important routes for "what," reward, and "where" scene-related information for human hippocampal episodic memory and navigation. The midcingulate cortex provides a route from the anterior dorsal parts of the PCD and the supracallosal part of the anterior cingulate cortex to premotor regions.\nDoc 5(Title: Title: Network-based mapping and neurotransmitter architecture of gray matter correlates of neuroticism.) Abstract: Although neuroticism is a major risk factor for adverse health outcomes, its neural basis is obscured by inconsistent findings from studies of regional gray matter volume (GMV) correlates. This study sought to identify convergent functional brain networks underlying these heterogeneous GMV correlates using functional connectivity network mapping (FCNM), and to explore their neurochemical basis. We systematically identified 10 voxel-based morphometry (VBM) studies ( Despite spatial heterogeneity, neuroticism-related GMV changes consistently mapped onto three principal functional networks: the default mode network (DMN), frontoparietal network (FPN), and ventral attention network (VAN). These mappings were robust across varied analytical parameters. Moreover, the implicated networks demonstrated significant spatial correlation with the distributions of 5-hydroxytryptamine receptor 2A (5-HT2A), cannabinoid receptor type 1 (CB1), and metabotropic glutamate receptor 5 (mGluR5). Despite regional variability, GMV correlates of neuroticism converge on common large-scale brain networks involved in self-referential processing, cognitive control, and salience processing. Their significant spatial coupling with 5-HT2A, CB1, and mGluR5 receptor distributions suggests serotonergic, endocannabinoid, and glutamatergic modulatory mechanisms contributing to network-level alterations. This cross-modal and network-based approach provides a unified framework for understanding the biological substrates of neuroticism, reconciling prior inconsistencies, and identifying key targets for prevention or biomarker development.\nDoc 6(Title: Title: Localization of brain networks activated by acupuncture at anatomically adjacent acupoints in healthy participants: neuroimaging evidence and implications for migraine and stroke.) Abstract: Neuroimaging investigations reveal heterogeneous acupuncture-induced brain activation patterns. Integrating acupoint-specific activation patterns into a unified connectomic framework enables systematic elucidation of acupoint-specific therapeutic mechanisms through network-level neural decoding. This study integrated functional connectivity network mapping (FCNM) methodology, canonical brain networks, and neurotransmitter distributions to delineate the distinct cerebral activation profiles of ST36 (Zusanli) and GB34 (Yanglingquan), two acupoints with anatomical proximity but divergent therapeutic indications in healthy controls (HCs). The neural networks activated by acupuncture at ST36 and GB34 are both composed of widely distributed brain regions. These two acupoints co-activated the somatomotor network, the ventral attention network, and the dorsal attention network. The activation pattern of ST36 additionally emphasizes the visual network, while the activation pattern of GB34 primarily involves subcortical regions. The spatial patterns of activation brain networks of ST36 showed exploratory spatial correlations with the distributions of 6-fluoro-(18F)-L-3,4-dihydroxyphenylalanine (FDOPA), noradrenaline transporter (NET) and vesicular acetylcholine transporter (VAChT) neurotransmitter, while the GB34 were correlated with dopamine D1, dopamine D2, dopamine transporter, FDOPA, NET, This study delineates the distinct physiological mechanisms of ST36 and GB34 from neuroimaging and molecular perspectives. This discovery not only elucidates acupoint effect specificity through brain network organization but also expands our understanding of acupoint therapeutic mechanisms within the framework of systems neuroscience, providing a scientific basis for the precise application of acupuncture in treating diseases.\nDoc 7(Title: Title: Distinct oscillatory fingerprints of language and default-mode networks support language comprehension outcomes: A fused MRI-EEG study.) Abstract: Language comprehension is a complex cognitive process that engages multiple brain networks across multiple timescales and frequencies. Coordination across networks requires dynamic shifts in neural frequency that allow for layered, hierarchical communication. Limitations in spatial and temporal resolutions across brain imaging modalities have historically limited characterization of the real-time frequency dynamics of widespread language comprehension networks. Our objective was to implement a novel fused fMRI-EEG and Continuous Wavelet Transform (CWT) analysis to identify frequency "fingerprints" for key language networks during naturalistic language comprehension (comparing connected passages to scrambled words). CWT was performed on the EEG components to analyze frequency power changes over the 1 s post-stimuli window. Joint independent component analysis revealed three components that showed significantly greater engagement during passages with spatial expression across canonical language regions, a left-lateralized default mode sub-network (DMN), and a bilateral dorsal angular gyrus DMN subnetwork. Frequency analysis revealed that the language component corresponded with prolonged theta with corresponding beta and gamma bursts; the first DMN component displayed beta-gamma bursts; and the second DMN component showed dominant alpha activity. Network frequency profiles also differentially predicted language comprehension outcomes: 1.) Subject-level frequency profile difference from the language component was correlated with recall performance, and 2.) Language network expression correlation with reading comprehension was found to be conditional on alpha-dominant DMN expression. Our findings provide evidence that canonical brain networks that support language comprehension exhibit distinct, time-dependent cross-frequency oscillation patterns which are predictive of language ability. This work operationalizes a new approach that traces multiscale neuronal oscillations to distinct spatial networks.\nDoc 8(Title: Title: Attention-Enhanced Temporal and Spatial Feature Extraction Network for ADHD Diagnosis based on fMRI.) Abstract: Attention Deficit Hyperactivity Disorder (ADHD) is a prevalent neurodevelopmental disorder, and accurate diagnosis is critical for ensuring timely intervention. The integration of deep learning and fMRI can effectively explore the abnormal spatiotemporal features of ADHD. However, existing deep learning models are unable to fully capture the temporal dependence and spatial consistency of fMRI data, primarily due to insufficient modeling of multi-scale temporal dependencies and the lack of explicit interaction between static and dynamic brain networks, resulting in poor diagnostic performance for ADHD. To comprehensively and efficiently extract the spatiotemporal features of fMRI signals, we propose an Attention-Enhanced Spatiotemporal Feature Extraction Network (AE-STEN), which comprises a Temporal Cross-scale Convolutional Attention Module (TCAM), a Spatial Collaborative Attention-Guided Graph Representation Module (SCGRM), and a Spatial-Temporal KAN Network (STKAN). TCAM is designed to capture short- and long-term dependencies in fMRI time series by jointly modeling local transient fluctuations and global temporal dependencies. SCGRM effectively extracts consistent spatial features from both dynamic and static fMRI data by explicitly modeling their collaborative interaction rather than treating them independently. STKAN integrates the extracted spatiotemporal features for final classification. Experiments on the ADHD-200 dataset, involving 747 subjects across seven sites, demonstrate that AE-STEN achieves a classification accuracy of up to 76.06% ± 0.65%. Moreover, AE-STEN identifies brain regions associated with ADHD consistent with clinical findings, indicating strong interpretability and highlighting the model\'s potential for clinical application.\nDoc 9(Title: Title: Multiscale Cortical Remodeling Following Abrupt Visual Deafferentation in Rhegmatogenous Retinal Detachment: Imaging Transcriptomics and Neurotransmitter Mapping.) Abstract: Neuroimaging evidence indicates brain alterations in rhegmatogenous retinal detachment (RRD), but the molecular and neurochemical correlates of these macroscale patterns remain unclear. We examined gray matter volume (GMV), intrinsic neural timescale (INT) and structural covariance network (SCN) gradients in 51 patients with RRD and 45 healthy controls (HCs). Two-sample Mendelian randomization (MR) evaluated whether RRD-related genetic liability was consistent with a putative causal effect on GMV. SCN-gradient alterations were further evaluated using exploratory spatial association analyses based on the Allen Human Brain Atlas (AHBA) and complementary neurotransmitter maps. SHAP-explainable machine-learning classification models compared the discriminative utility of structural versus functional features. Patients with RRD showed reduced GMV in the visual network (VN) and shortened INT in the default mode network (DMN). MR results were consistent with a putative causal effect of RRD genetic liability on VN atrophy. SCN gradients revealed a hierarchical "visual-downward and limbic-upward" shift. Exploratory imaging-transcriptomic spatial association analyses suggested that gradient alterations were spatially aligned with gene expression patterns enriched for neurodevelopmental and synaptic pathways, including excitatory/inhibitory neuronal and microglial signatures; complementary neurotransmitter mapping analyses further suggested spatial correspondence with normative monoaminergic/cholinergic and μ-opioid maps, together with an inverse spatial association with GABAa receptor density maps. INT-based ML models outperformed GMV-based models (best AUC\u2009=\u20090.753), with SHAP identifying INT as the predominant contributor. RRD is associated with coordinated structural and functional alterations across cortical hierarchies. Exploratory transcriptomic and neurotransmitter spatial association patterns may provide biological context for these imaging abnormalities and inform future studies of prognosis and underlying mechanisms.\nDoc 10(Title: Title: Temporal synchrony and spatial similarity of interbrain subnetworks predict dyadic social interaction.) Abstract: Human social behaviors involve complex interactions between individuals, and understanding how interbrain neural activity reflects and predicts these interactions is critical for advancing social cognitive neuroscience. While electroencephalography (EEG) hyperscanning has been widely used to explore interpersonal neural dynamics, most studies focus on pairwise regional coupling, overlooking the brain\'s intrinsic network-level organization. Here, we propose a spatiotemporal network analysis framework that combines Bayesian non-negative matrix factorization with EEG source imaging to identify interpretable subnetworks with spatiotemporal information. Applying this framework to dyadic EEG datasets from interactive decision-making tasks identifies eight task-relevant subnetworks, including the default mode network (DMN), somatosensory-motor network (SMN), and visual network (VN). Effective interpersonal coordination was associated with enhanced network-level time-domain interbrain synchrony and spatial-domain inter-subject similarity, and the fusion of these metrics reliably predicted interactive behaviors. Notably, synchrony and similarity involving DMN, VN, and SMN emerge as robust predictors of interactive behaviors, with spatiotemporal coupling most prominent within these subnetworks. These findings reveal spatiotemporal network signatures underlying interpersonal neural synchronization and demonstrate the importance of distributed subnetworks and their temporal and spatial alignment in achieving effective social interactions. This framework provides a useful computational tool for probing the neurobiological basis of social behaviors.\n'}, {'role': 'user', 'content': 'Question: What brain regions are involved in the spatial attention network?\nAnsw

Generation process:  85%|████████▍ | 11/13 [00:27<00:06,  3.15s/it]

[{'role': 'system', 'content': 'You are a biomedical expert. OUTPUT RULE: Answer in 2-3 sentences (30-50 words). State the key fact first, then supporting detail. Write like a PubMed abstract sentence. Answer the question using only the provided documents. Be direct and factual - no preamble, no caveats.\n\nDocuments:\nDoc 1(Title: Title: The human posterior cingulate, retrosplenial, and medial parietal cortex effective connectome, and implications for memory and navigation.) Abstract: The human posterior cingulate, retrosplenial, and medial parietal cortex are involved in memory and navigation. The functional anatomy underlying these cognitive functions was investigated by measuring the effective connectivity of these Posterior Cingulate Division (PCD) regions in the Human Connectome Project-MMP1 atlas in 171 HCP participants, and complemented with functional connectivity and diffusion tractography. First, the postero-ventral parts of the PCD (31pd, 31pv, 7m, d23ab, and v23ab) have effective connectivity with the temporal pole, inferior temporal visual cortex, cortex in the superior temporal sulcus implicated in auditory and semantic processing, with the reward-related vmPFC and pregenual anterior cingulate cortex, with the inferior parietal cortex, and with the hippocampal system. This connectivity implicates it in hippocampal episodic memory, providing routes for "what," reward and semantic schema-related information to access the hippocampus. Second, the antero-dorsal parts of the PCD (especially 31a and 23d, PCV, and also RSC) have connectivity with early visual cortical areas including those that represent spatial scenes, with the superior parietal cortex, with the pregenual anterior cingulate cortex, and with the hippocampal system. This connectivity implicates it in the "where" component for hippocampal episodic memory and for spatial navigation. The dorsal-transitional-visual (DVT) and ProStriate regions where the retrosplenial scene area is located have connectivity from early visual cortical areas to the parahippocampal scene area, providing a ventromedial route for spatial scene information to reach the hippocampus. These connectivities provide important routes for "what," reward, and "where" scene-related information for human hippocampal episodic memory and navigation. The midcingulate cortex provides a route from the anterior dorsal parts of the PCD and the supracallosal part of the anterior cingulate cortex to premotor regions.\nDoc 2(Title: Title: Mental health in the perinatal period: bridging the gaps in care, evidence, and policy.) Abstract: Perinatal mental health has long been acknowledged as fundamental to the well-being of mothers and infants, yet the recognition of disorders such as postpartum depression, anxiety, and - far less commonly - psychosis still lags behind clinical need. Even where validated screening tools exist, detection remains inconsistent, and many women navigate pregnancy and the postpartum period with symptoms that go unspoken or unnoticed. In some high-income settings, suicide has emerged as a leading contributor to maternal mortality, a reminder that the health consequences of these conditions extend beyond emotional distress and reflect deeper systemic failings. In this opinion paper, we draw on recent developments across epidemiology, neuroscience, psychology, and health-system research to consider why perinatal mental health continues to occupy an uncertain place in routine care. Fragmented service pathways, variability in provider training, and uneven adoption of evidence-supported interventions create persistent gaps between what is known and what is practiced. We highlight examples - stepped-care models, collaborative teams, and digital supports - that illustrate how more coherent systems could function, even if implementation remains uneven. Although a wide range of effective interventions exists, their practical reach is limited by sociocultural norms, structural constraints, and resource imbalances. Understanding these influences together - not in isolation - helps clarify why progress has been slower than the evidence might suggest. Meaningful improvement will depend on strengthening cross-sector integration, expanding scalable technologies, and tailoring policy responses to local realities. Sustained investment in perinatal mental health offers long-term benefits for families and communities and should be regarded as central to modern maternal care.\nDoc 3(Title: Title: Intervention Effects on Phonological Processing in Children With Developmental Speech and/or Language Disorder: A Systematic Review and Meta-Analysis of Studies With Group Design.) Abstract: Challenges in phonological processing are prevalent in children with developmental speech and/or language disorders and are associated with their language acquisition and later reading skills. A recent systematic review and meta-analysis from the same project of studies with a group design on the effects of interventions on output phonology, found that oral language interventions have a positive effect on output phonology, specifically speech production accuracy. These interventions are expected to impact the phonological representational level as well and, thus, also affect phonological processing skills in this population. However, no prior systematic reviews or meta-analyses have been conducted on this topic. We conducted a systematic literature review and meta-analysis to investigate the effectiveness of oral language interventions on children and adolescents\xa0with developmental speech and/or language disorders, focusing on phonological processing as the primary outcome measure, including phonological awareness, phonological retrieval efficiency, and short-term memory. The systematic review was pre-registered (PROSPERO ID: CRD42017076075) and followed the PRISMA guidelines. A search for oral language interventions in children and adolescents\xa0with developmental speech and/or language disorders (mean age, 3-18 years) was conducted across seven databases (PubMed, Web of Science, ERIC, Cochrane Library, PsycINFO, Scopus, LLBA) for studies published between January 2006 and May 2023. We included studies with a group design and phonological processing as the outcome measure. The Cochrane risk of bias tool was used for study appraisal. Individual and average standardised mean differences g were used in the meta-analysis. We also explored the influence of various moderators. We identified 22 studies that met the inclusion criteria. Overall, the risk of bias was low to moderate. Significant and large effect sizes were found in pre-post studies with control groups, showing improvements post-intervention in phonological awareness, g\xa0=\xa00.710, p\xa0<\xa00.001, 95% CI [0.504, 0.917], and phonological short-term memory, g\xa0=\xa00.785, p\xa0=\xa00.010, 95% CI [0.192, 1.279]. Some moderator variables emerged, for example, larger effects when the interventions were based on an integrated theoretical approach, applied in small groups, or when they had processing targets. The results demonstrate that oral language interventions can effectively improve specific phonological processing skills in children and adolescents\xa0with developmental speech and/or language disorders. The identification of key moderating factors provides valuable guidance for clinical practice. What is already known on the subject Children with developmental speech and/or language disorders often have difficulties in phonological processing that can hamper their reading development. Interventions are effective for speech production, but there are no previous systematic reviews or meta-analyses on their effects on the phonological processing skills of children and adolescents with developmental speech and/or language disorders. What this paper adds to existing knowledge We present empirical evidence of the effectiveness of oral language interventions in improving phonological processing (including phonological awareness and phonological short-term memory) in children and adolescents with developmental speech and/or language disorders. What are the potential or actual clinical implications of this work? Oral language interventions have a positive effect on the phonological processing skills of children and adolescents with developmental speech and/or language disorders. They may serve as an indirect means of support for their reading development.\nDoc 4(Title: Title: Non-linguistic comprehension, social inference and empathizing skills in autistic young adults, young adults with autistic traits and control young adults: Group differences and interrelatedness of skills.) Abstract: Despite increasing knowledge of social communication skills of autistic peole, the interrelatedness of different skills such as non-linguistic comprehension, social inference and empathizing skills is not much known about. A better understanding of the complex interplay between different domains of social communication helps us to develop assessment protocols for individuals with social communication difficulties. To compare the performances of autistic young adults, young adults with autistic traits identified in childhood and control young adults in social communication tasks measuring non-linguistic comprehension, social inference and empathizing skills. In addition, to examine associations between the different social communication measures. Autistic young adults (n = 34), young adults with autistic traits (n = 19) and control young adults (n = 36) completed the extra- and paralinguistic scales of the Assessment Battery for Communication (ABaCo), the Faux Pas Recognition Test, Social-Pragmatic Questions (SoPra) and the Empathy Quotient (EQ). Group differences were found in the performance in the ABaCo, SoPra and EQ scores. Compared with the control young adults, autistic young adults scored lower. The performance of the young adults in the autistic traits group fell in between the other two groups. There were no group differences in the Faux Pas Recognition Test. The variability within the groups was large in all measurements. In the control group, there was a significant correlation between EQ and SoPra scores and between the Faux Pas and SoPra scores. In the autistic group, a significant correlation was found between Faux Pas and SoPra scores. Also, other patterns were observed but these were not statistically significant. The young adults with autistic traits fell in between the control and autistic young adults, highlighting the presence of the continuum in the terms of features of social communication. The results support other current research that suggests that theory of mind and other social communication skills may not be universally or widely impaired in all autistic individuals without cognitive deficits. Although all tasks examined social communication skills, only a small number of significant correlations were found between test scores. This highlights that clinical conclusions about a person\'s social communication should be based on the outcomes of different types of methods measuring different aspects of social communication. It is clear that the interrelatedness of different social communication skills needs further research. What is already known on this subject For successful communication, the ability to infer others\' emotions, intentions and mental states is crucial. Autistic people have difficulty with many aspects of social communication. However, the associations between different aspects of social communication need to be better understood. What this paper adds to existing knowledge The unique contribution of this study is to compare the performance of autistic people not only with that of a control group but also with people with childhood autistic traits. This provides an understanding of the interrelatedness of different social communication skills in people with varying degrees of autistic traits. This study used four assessment methods focusing on three different social communication elements (non-linguistic comprehension, social inference and empathizing skills). These elements have complex relationships to one another, some being closely overlapping, some more distally related and some reflect more complex multifactorial elements. This study shows that although groups differ from each other in most of the assessments, the performance of different groups overlapped showing that many autistic young adults can perform well in non-linguistic and social inference tasks in structured assessment contexts. What are the potential or actual clinical implications of this work? Our findings suggest that in the assessment of social communication, self-reports and clinical assessments can be used effectively together. They can complement each other, pointing out the strengths and weaknesses of a person, leading to more personalized therapeutic interventions.\nDoc 5(Title: Title: Categorization for Faces and Tools-Two Classes of Objects Shaped by Different Experience-Differs in Processing Timing, Brain Areas Involved, and Repetition Effects.) Abstract: The brain mechanisms that integrate the separate features of sensory input into a meaningful percept depend upon the prior experience of interaction with the object and differ between categories of objects. Recent studies using representational similarity analysis (RSA) have characterized either the spatial patterns of brain activity for different categories of objects or described how category structure in neuronal representations emerges in time, but never simultaneously. Here we applied a novel, region-based, multivariate pattern classification approach in combination with RSA to magnetoencephalography data to extract activity associated with qualitatively distinct processing stages of visual perception. We asked participants to name what they see whilst viewing bitonal visual stimuli of two categories predominantly shaped by either value-dependent or sensorimotor experience, namely faces and tools, and meaningless images. We aimed to disambiguate the spatiotemporal patterns of brain activity between the meaningful categories and determine which differences in their processing were attributable to either perceptual categorization\nDoc 6(Title: Title: EXPRESS: What Phonological Overlap Effects Reveal about the Role of Working Memory in Native and Nonnative Language Processing.) Abstract: The present study sheds light on effects of similarity-based interference due to phonological overlap, as well as working memory during silent reading in native and nonnative speakers. While prior research has mainly focused on syntactic complexity or ambiguity to gain insight into nonnative language processing and the role of working memory, the effects of phonological overlap have remained poorly understood. Using multiline texts with varying degrees of phonological overlap, we examined whether increased amounts of overlap disrupt online reading and offline recall, and whether effects differ across native and nonnative groups or vary as a function of working memory capacity. Results revealed that greater phonological overlap caused delays during online processing, but without impacting offline recall. Crucially, native and nonnative speakers experienced online interference similarly, and working memory modulated these effects in comparable ways across both groups. These results suggest convergence both in overt behavior and in how underlying cognitive resources are used. Findings are discussed with respect to their implications for theories of native-nonnative language processing differences and possible directions for further research.\nDoc 7(Title: Title: Visuomotor adaptation and savings are preserved in individuals with depression.) Abstract: Depression is a mental disorder associated primarily with mood and cognitive symptoms. Several studies show that depression is additionally accompanied by decrements in gross and fine motor functioning. The present study examined to what extent depression affects the ability to adapt sensorimotor behavior. A total of 20 participants with depression and 22 controls performed a manual adaptation task in which they had to adapt joystick movements to a visual perturbation. We assessed the rate of adaptation following the introduction of the visual perturbation (both for early and later stages of adaptation) and the rate of de-adaptation following its removal. In addition, questionnaires were used to measure severity of depressive symptoms and quality of life. Participants completed these assessments twice (i.e., at baseline and after an approximately 15-week interval), allowing us to also assess savings of adaptation as well as the link between changes in mood and sensorimotor performance. We found that across all participants reliable adaptation patterns and savings of adaptation were observed. Results of Bayesian models showed moderate evidence indicating that depression was not associated with poorer adaptability or savings. Furthermore, adaptation rates were not associated with the severity of depressive symptoms. These findings further refine the psychomotor profile of depression and suggest that it does not affect sensorimotor adaptation or savings of adaptation.\nDoc 8(Title: Title: A stroke-level large-scale database of Chinese character handwriting and the OpenHandWrite_Toolbox for handwriting research.) Abstract: Understanding what linguistic components (e.g., phonological, semantic, and orthographic systems) modulate Chinese handwriting at the character, radical, and stroke levels remains an important yet understudied topic. Additionally, there is a lack of comprehensive tools for capturing and batch-processing fine-grained handwriting data. To address these issues, we constructed a large-scale handwriting database in which 42 Chinese speakers each handwrote 1200 characters in a handwriting-to-dictation task. Additionally, we enhanced the existing handwriting package and provided comprehensive documentation for the upgraded OpenHandWrite_Toolbox. This toolbox allows users to easily modify the experimental design, capture the stroke-level handwriting trajectory, and batch-process handwriting measurements (e.g., latency and duration). Analysis of our large-scale database indicates that orthographic predictors affect handwriting preparation and execution at the character, radical, and stroke levels. Phonological factors influence handwriting at character and radical levels. Importantly, these lexical effects demonstrate hierarchical attenuation: they were most pronounced at the character level, followed by the radical, and weakest at the stroke level. These findings demonstrate that handwriting preparation and execution at the radical and stroke levels are closely intertwined with linguistic components. This database and toolbox offer valuable resources for future psycholinguistic and neurolinguistic research on the handwriting of characters and sub-characters across different languages.\nDoc 9(Title: Title: Does age protect against loss of tonotopy after acute deafness in adulthood?) Abstract: The mammalian auditory system develops a topographical representation of sound frequencies along its pathways, also called tonotopy. In contrast, sensory deprivation during early development results in no or only rudimentary tonotopic organization. This study addresses two questions: (1) How robust is the central tonotopy when hearing fails in adulthood? (2) What role does age play at time of deafness? To address these questions, we deafened young and old adult rats with previously normal hearing. One month after deafening, both groups were unilaterally supplied with cochlear implants and electrically stimulated for 2 h. The central auditory neurons, which were activated as a result of the local electrical intracochlear stimulation, were visualized using Fos staining.

Generation process:  92%|█████████▏| 12/13 [00:28<00:02,  2.71s/it]

[{'role': 'system', 'content': "You are a biomedical expert. OUTPUT RULE: Answer in 2-3 sentences (30-50 words). State the key fact first, then supporting detail. Write like a PubMed abstract sentence. Answer the question using only the provided documents. Be direct and factual - no preamble, no caveats.\n\nDocuments:\nDoc 1(Title: Title: Brief report: the relationship between visual acuity, the embedded figures test and systemizing in autism spectrum disorders.) Abstract: Enhanced performance upon the Embedded Figures Test (EFT) in individuals with autism spectrum disorder (ASD) has informed psychological theories of the non-social aspects that characterise ASD. The Extreme Male Brain theory of autism proposes that enhanced visual acuity underpins greater attention to detail (assessed by the EFT) which is a prerequisite for Systemizing. To date, however, no study has empirically examined these relationships. 13 males with ASD and 13 male controls were assessed upon tasks argued to reflect these levels of processing. The ASD group were found to have significantly greater visual acuity, EFT performance and Systemizing ability than the control group. However, regression analysis revealed that the strongest relationship was between visual acuity and EFT performance.\nDoc 2(Title: Title: Embedded Figures Test Performance in the Broader Autism Phenotype: A Meta-analysis.) Abstract: People with autism show superior performance to controls on the Embedded Figures Test (EFT). However, studies examining the relationship between autistic-like traits and EFT performance in neurotypical individuals have yielded inconsistent findings. To examine the inconsistency, a meta-analysis was conducted of studies that (a) compared high and low Autism-Spectrum Quotient (AQ) groups, and (b) treated AQ as a continuous variable. Outcomes are consistent with superior visual search forming part of the broader autism phenotype, but in existing literature, this is evident only when comparing extreme groups. Reanalysis of data from previous studies suggests findings are unlikely to be driven by a small number of high scorers. Monte Carlo simulations are used to illustrate the effect of methodological differences on results.\nDoc 3(Title: Title: Cerebral correlates of preserved cognitive skills in autism: a functional MRI study of embedded figures task performance.) Abstract: When considering the cognitive abilities of people with autism, the majority of studies have explored domains in which there are deficits. However, on tests of local processing and visual search, exemplified by the Embedded Figures Task (EFT), people with autism have been reported to demonstrate superiority over normal controls. This study employed functional MRI of subjects during the performance of the EFT to test the hypothesis that normal subjects and a group with autism would activate different brain regions and that differences in the patterns of these regional activations would support distinct models of cerebral processing underlying EFT performance in the two groups. It was found that several cerebral regions were similarly activated in the two groups. However, normal controls, as well as demonstrating generally more extensive task-related activations, additionally activated prefrontal cortical areas that were not recruited in the group with autism. Conversely, subjects with autism demonstrated greater activation of ventral occipitotemporal regions. These differences in functional anatomy suggest that the cognitive strategies adopted by the two groups are different: the normal strategy invokes a greater contribution from working memory systems while the autistic group strategy depends to an abnormally large extent on visual systems for object feature analysis. This interpretation is discussed in relation to a model of autism which proposes a predisposition towards local rather than global modes of information processing.\nDoc 4(Title: Title: How do cannabis users mentally travel in time? Evidence from an fMRI study of episodic future thinking.) Abstract: Episodic future thinking (EFT) is a cognitive function that allows individuals to imagine novel experiences that may happen in the future. Prior studies show that EFT is impaired in different groups of substance users. However, there is no evidence regarding the neurobiological mechanisms of EFT in cannabis users. We aimed to compare brain activations of regular cannabis users and non-using controls during an EFT fMRI task. Exploratory analyses were also conducted to investigate the association between EFT and cannabis use variables (e.g., duration of use, age onset, frequency of use). Twenty current cannabis users and 22 drug-naïve controls underwent an fMRI scanning session while completing a task involving envisioning future-related events and retrieval of past memories as a control condition. The EFT fMRI task was adapted from the autobiographical interview and composed of 20 auditory cue sentences (10 cues for past and 10 cues for future events). Participants were asked to recall a past or generate a future event, in response to the cues, and then rate their vividness after each response. We found that cannabis users compared to non-user controls had lower activation within the cerebellum, medial and superior temporal gyrus, lateral occipital cortex, and occipital fusiform gyrus while envisioning future events. Cannabis users rated the vividness of past events significantly lower than non-users (P\u2009<\u20090.005). There were marginal group differences for rating the vividness of future events (P\u2009=\u20090.052). Significant correlations were also found between the medial and superior temporal gyrus activities and behavioral measures of EFT and episodic memory. Cannabis users, compared to drug-naïve controls, have lower brain activation in EFT relevant regions. Thus, any attempts to improve aberrant EFT performance in cannabis users may benefit from EFT training.\nDoc 5(Title: Title: Visual search performance in the autism spectrum II: the radial frequency search task with additional segmentation cues.) Abstract: The Embedded Figures Test (EFT) requires detecting a shape within a complex background and individuals with autism or high Autism-spectrum Quotient (AQ) scores are faster and more accurate on this task than controls. This research aimed to uncover the visual processes producing this difference. Previously we developed a search task using radial frequency (RF) patterns with controllable amounts of target/distracter overlap on which high AQ participants showed more efficient search than low AQ observers. The current study extended the design of this search task by adding two lines which traverse the display on random paths sometimes intersecting target/distracters, other times passing between them. As with the EFT, these lines segment and group the display in ways that are task irrelevant. We tested two new groups of observers and found that while RF search was slowed by the addition of segmenting lines for both groups, the high AQ group retained a consistent search advantage (reflected in a shallower gradient for reaction time as a function of set size) over the low AQ group. Further, the high AQ group were significantly faster and more accurate on the EFT compared to the low AQ group. That is, the results from the present RF search task demonstrate that segmentation and grouping created by intersecting lines does not further differentiate the groups and is therefore unlikely to be a critical factor underlying the EFT performance difference. However, once again, we found that superior EFT performance was associated with shallower gradients on the RF search task.\nDoc 6(Title: Title: Global visual processing and self-rated autistic-like traits.) Abstract: The current research investigated, firstly, whether individuals with high levels of mild autistic-like traits display a similar profile of embedded figures test (EFT) and global motion performance to that seen in autism. Secondly, whether differences in EFT performance are related to enhanced local processing or reduced global processing in the ventral visual stream was also examined. Results indicated that people who scored high on the Autism-spectrum Quotient (AQ) were faster to identify embedded figures, and had poorer global motion and global form thresholds than low AQ scorers. However, the two groups did not differ on a task assessing lower-level input to the ventral stream. Overall the results indicate that individuals with high levels of autistic-like traits have difficulties with global integration in the visual pathways, which may at least partly explain their superior EFT performance.\nDoc 7(Title: Title: Developing the Leuven Embedded Figures Test (L-EFT): testing the stimulus features that influence embedding.) Abstract: The Embedded Figures Test (EFT, developed by Witkin and colleagues (1971)) has been used extensively in research on individual differences, particularly in the study of autism spectrum disorder. The EFT was originally conceptualized as a measure of field (in)dependence, but in recent years performance on the EFT has been interpreted as a measure of local versus global perceptual style. Although many have used the EFT to measure perceptual style, relatively few have focused on understanding the stimulus features that cause a shape to become embedded. The primary aim of this work was to investigate the relation between the strength of embedding and perceptual grouping on a group level. New embedded figure stimuli (both targets and contexts) were developed in which stimulus features that may influence perceptual grouping were explicitly manipulated. The symmetry, closure and complexity of the target shape were manipulated as well as its good continuation by varying the number of lines from the target that continued into the context. We evaluated the effect of these four stimulus features on target detection in a new embedded figures task (Leuven Embedded Figures Test, L-EFT) in a group of undergraduate psychology students. The results were then replicated in a second experiment using a slightly different version of the task. Stimulus features that influence perceptual grouping, especially good continuation and symmetry, clearly affected performance (lower accuracy, slower response times) on the L-EFT. Closure did not yield results in line with our predictions. These results show that some stimulus features, which are known to affect perceptual grouping, also influence how effectively a stimulus becomes embedded in different contexts. Whether these results imply that the EFT measures individual differences in perceptual grouping ability must be further investigated.\nDoc 8(Title: Title: Support for a link between the local processing bias and social deficits in autism: an investigation of embedded figures test performance in non-clinical individuals.) Abstract: The aim of this investigation was to explore the degree to which specific subsets of autistic-like traits relate to performance on the Embedded Figures Test (Witkin et al. in A manual for the embedded figures test. Consulting Psychologists Press, Palo Alto, CA, 1971). In the first group-based investigation with this focus, students were selected for their extreme scores (either high or low) on each of the 'Social Skills' and 'Details/Patterns' factors of the Autism Spectrum Quotient (Baron-Cohen et al. in J Austim Dev Disord 31:5-17, 2001). The resulting 2\xa0×\xa02 factorial design permitted examination of the degree to which the social and non-social autistic-like traits separately relate to EFT performance. Surprisingly, in two studies, superior EFT performance was found to relate only to greater social difficulty, suggesting that the local processing bias in autism may be linked specifically to the social deficits.\nDoc 9(Title: Title: Atypical neural substrates of Embedded Figures Task performance in children with Autism Spectrum Disorder.) Abstract: Superior performance on the Embedded Figures Task (EFT) has been attributed to weak central coherence in perceptual processing in Autism Spectrum Disorder (ASD). The present study used functional magnetic resonance imaging to examine the neural basis of EFT performance in 7- to 12-year-old ASD children and age- and IQ-matched controls. ASD children activated only a subset of the distributed network of regions activated in controls. In frontal cortex, control children activated left dorsolateral, medial and dorsal premotor regions whereas ASD children only activated the dorsal premotor region. In parietal and occipital cortices, activation was bilateral in control children but unilateral (left superior parietal and right occipital) in ASD children. Further, extensive bilateral ventral temporal activation was observed in control, but not ASD children. ASD children performed the EFT at the same level as controls but with reduced cortical involvement, suggesting that disembedded visual processing is accomplished parsimoniously by ASD relative to typically developing brains.\nDoc 10(Title: Title: Practice is the best of all instructors-Effects of enactment encoding and episodic future thinking on prospective memory performance in high-functioning adults with autism spectrum disorder.) Abstract: Prospective memory (PM) is the ability to remember to carry out intended actions in the future. The present study investigated the effects of episodic future thinking (EFT) and enactment encoding (EE) on PM performance in autistic adults (ASD). A total of 72 autistic individuals and 70 controls matched for age, gender, and cognitive abilities completed a computerized version of the Dresden breakfast Task, which required participants to prepare breakfast following a set of rules and time restrictions. A two (group: ASD vs. controls) by three (encoding condition: EFT vs. EE vs. standard) between-subjects design was applied. Participants were either instructed to engage in EFT or EE to prepare to the different tasks prior to performing the Dresden breakfast or received standard instructions. Analyses of variance were conducted. Autism-spectrum-disorders (ASD) participants did not differ from control participants in their PM performance, regardless of which strategy they used. Compared to the standard condition, EE but not EFT improved time-based PM performance in all participants. This is the first study to find spared time-based PM performance in autistic individuals. The results confirm earlier results of beneficial effects of EE on PM performance. Findings are discussed with regards to the methodology used, sample composition as well as autistic characteristics.\n"}, {'role': 'user', 'content': 'Question: How do individuals with autism perform on the EFT?\nAnswer:'}]
----asd-asd-a--------

Generation process: 100%|██████████| 13/13 [00:30<00:00,  2.34s/it]

Done.

## 9. Extract predicted answers

In [9]:
predicted_answers = output_dataset.pred

# Sanity check
ref_lens  = [len(a.split()) for a in expected_answers]
pred_lens = [len(a.split()) for a in predicted_answers]

print(f'Reference  avg: {np.mean(ref_lens):.1f}w')
print(f'Predicted  avg: {np.mean(pred_lens):.1f}w')
print()

for q, ref, pred in list(zip(questions, expected_answers, predicted_answers))[:3]:
    print(f'Q:    {q[:70]}')
    print(f'REF:  {ref[:130]}')
    print(f'PRED: {pred[:130]}')
    print()

Reference  avg: 35.1w
Predicted  avg: 51.7w

Q:    Which brain region is involved in working memory capacity constraints?
REF:  The dorsolateral prefrontal cortex (DLPFC) is a key brain region involved in working memory capacity constraints, exhibiting an 'i
PRED: The parietal cortex is most prominent in explaining working memory capacity constraints. Supporting evidence shows that capacity l

Q:    Are other brain regions also involved in working memory capacity const
REF:  Yes, other brain regions, such as the premotor cortex, thalamus, and superior parietal lobule, may also demonstrate capacity-const
PRED: Key fact: Autistic young adults generally score lower than controls on non-linguistic comprehension, social inference, and empathi

Q:    What is a visuomotor task?
REF:  A visuomotor task is a type of task that requires the transformation of visual signals into motor responses, such as moving a fing
PRED: A visuomotor task is a behavioral task that requires the integration of visual information with motor commands to guide movement,

## 10. Save results

In [10]:
results_df = pd.DataFrame({
    'question':         questions,
    'expected_answer':  expected_answers,
    'flashrag_answer':  predicted_answers,
})
results_df.to_csv('flashrag_results.csv', index=False)

# Also cache for re-use
cache = dict(zip(questions, predicted_answers))
with open('flashrag_cache.json', 'w') as f:
    json.dump(cache, f, indent=2, ensure_ascii=False)

print('Saved flashrag_results.csv and flashrag_cache.json')
results_df.head()

Saved flashrag_results.csv and flashrag_cache.json

,question,expected_answer,flashrag_answer
0,Which brain region is involved in working memo...,The dorsolateral prefrontal cortex (DLPFC) is ...,The parietal cortex is most prominent in expla...
1,Are other brain regions also involved in worki...,"Yes, other brain regions, such as the premotor...",Key fact: Autistic young adults generally scor...
2,What is a visuomotor task?,A visuomotor task is a type of task that requi...,A visuomotor task is a behavioral task that re...
3,What brain regions are involved in visuomotor ...,The brain regions involved in visuomotor trans...,Key brain regions involved in visuomotor trans...
4,What is the role of the prefrontal cortex in v...,The prefrontal cortex is involved in the prepa...,"The prefrontal cortex, specifically the ventro..."

## 11. Compute metrics

In [11]:
metrics = {
    'cos_score':       round(float(embeddings_cosine_sim_metric(expected_answers, predicted_answers)), 4),
    'bleu_score':      round(float(bleu_metric(expected_answers, predicted_answers)), 4),
    'rouge_1_score':   round(float(rogue_1_metric(expected_answers, predicted_answers)), 4),
    'rouge_l_score':   round(float(rogue_l_metric(expected_answers, predicted_answers)), 4),
    'factscore_score': round(float(factscore_metric(expected_answers, predicted_answers)), 4),
    'bert_score':      round(float(bert_score_metric(expected_answers, predicted_answers)), 4),
}

print('=== FlashRAG Naive RAG Metrics ===')
for name, value in metrics.items():
    print(f'{name:<20} {value:.4f}')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/389 [00:00<?, ?it/s]

[transformers] RobertaModel LOAD REPORT from: roberta-large
Key                       | Status     |
--------------------------+------------+-
lm_head.layer_norm.bias   | UNEXPECTED |
lm_head.bias              | UNEXPECTED |
lm_head.dense.weight      | UNEXPECTED |
lm_head.layer_norm.weight | UNEXPECTED |
lm_head.dense.bias        | UNEXPECTED |
pooler.dense.bias         | MISSING    |
pooler.dense.weight       | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

=== FlashRAG Naive RAG Metrics ===
cos_score            0.6070
bleu_score           0.0373
rouge_1_score        0.2236
rouge_l_score        0.1799
factscore_score      0.1249
bert_score           0.2055