In [ ]:
import json
import io
import urllib.request

import pandas as pd

## Load answer key from GitHub

In [2]:
REPO_RAW = 'https://raw.githubusercontent.com/allenai/neurodiscoverybench/main'

TEXT_DATASETS = [
    'SEA-AD-text',
    'WMB-processed-text',
    'WMB-raw-text',
    'WMB-raw-no-traces',
]

In [3]:
# Load answer_key.csv — contains gold hypotheses for text tasks
answer_key_url = f'{REPO_RAW}/eval/answer_key.csv'
with urllib.request.urlopen(answer_key_url, timeout=30) as resp:
    answer_key_text = resp.read().decode()

answer_key_df = pd.read_csv(io.StringIO(answer_key_text))
# Filter to text-only datasets
answer_key_df = answer_key_df[answer_key_df['dataset'].isin(TEXT_DATASETS)].reset_index(drop=True)
print(f'Text-based gold hypotheses: {len(answer_key_df)}')
answer_key_df

Text-based gold hypotheses: 25

,dataset,metadataid,query_id,gold_hypo
0,SEA-AD-text,0,0,"In this dataset, higher ADNC scores are observ..."
1,SEA-AD-text,1,0,"In this dataset, APOE4 allele is observed to b..."
2,SEA-AD-text,2,0,"In this dataset, individuals with high ADNC sc..."
3,SEA-AD-text,3,0,"In this dataset, donors with higher ADNC score..."
4,SEA-AD-text,4,0,"In this dataset, as ADNC scores increase, CERA..."
5,SEA-AD-text,5,0,"In this dataset, donors with high ADNC scores ..."
6,SEA-AD-text,6,0,"In this dataset, higher ADNC scores are observ..."
7,WMB-processed-text,0,0,"In the RHP region, the subclass 019 L2/3 IT PP..."
8,WMB-processed-text,1,0,"In the observed data, class '19 MB Glut' inclu..."
9,WMB-processed-text,2,0,"In the observed data, '24 MY Glut' includes 76..."
10,WMB-processed-text,3,0,"In the observed data, 'Glut' neurotransmitter ..."
11,WMB-raw-text,0,0,"In the RHP region, the subclass 019 L2/3 IT PP..."
12,WMB-raw-text,1,0,"In the observed data, class '19 MB Glut' inclu..."
13,WMB-raw-text,2,0,"In the observed data, '24 MY Glut' includes 76..."
14,WMB-raw-text,3,0,"In the observed data, 'Glut' neurotransmitter ..."
15,WMB-raw-no-traces,1,0,62 neuronal clusters exhibit dual glutamate-GA...
16,WMB-raw-no-traces,0,0,335 clusters contain no dark-phase transcripto...
17,WMB-raw-no-traces,2,0,79 % of all clusters express at least one neur...
18,WMB-raw-no-traces,3,0,35 of the dopaminergic clusters co-release ano...
19,WMB-raw-no-traces,4,0,24 of the 48 cholinergic clusters co-release g...
20,WMB-raw-no-traces,5,0,7 of the 48 cholinergic clusters co-release GABA.
21,WMB-raw-no-traces,6,0,3 of the 48 cholinergic clusters co-release bo...
22,WMB-raw-no-traces,7,0,1 of the 48 cholinergic clusters co-releases d...
23,WMB-raw-no-traces,8,0,26 clusters show significant sex-biased repres...
24,WMB-raw-no-traces,9,0,5 clusters are completely sex-specific.

## Load questions from metadata JSONs

In [4]:
records = []

for _, row in answer_key_df.iterrows():
    dataset = row['dataset']
    metadata_id = int(row['metadataid'])
    query_id = int(row['query_id'])
    gold_hypo = row['gold_hypo']

    # Fetch the metadata JSON to get the question text
    meta_url = f'{REPO_RAW}/neurodiscoverybench/{dataset}/metadata_{metadata_id}.json'
    try:
        with urllib.request.urlopen(meta_url, timeout=30) as resp:
            metadata = json.loads(resp.read().decode())

        # Extract the question matching query_id
        question = None
        for q in metadata['queries'][0]:
            if q['qid'] == query_id:
                question = q['question']
                break

        if question and pd.notna(gold_hypo):
            # Categorize: SEA-AD questions are about known neuroscience
            # relationships; WMB questions require data analysis
            if 'SEA-AD' in dataset:
                category = 'knowledge'
            else:
                category = 'data-analysis'

            records.append({
                'question': question,
                'answer': gold_hypo,
                'category': category,
                'dataset': dataset,
            })
            print(f'[{dataset}] {question}')
    except Exception as e:
        print(f'Error fetching {meta_url}: {e}')

print(f'\nTotal QA pairs: {len(records)}')

[SEA-AD-text] How does the distribution of Braak stages change across increasing ADNC categories?
[SEA-AD-text] How does the frequency of the APOE4 allele relate with increasing ADNC scores?
[SEA-AD-text] How does the median age at death vary across high and low ADNC categories in the SEA-AD cohort?
[SEA-AD-text] What is the relationship between Thal phases and higher ADNC scores in the SEA-AD cohort?
[SEA-AD-text] How do CERAD scores vary with different ADNC categories in the SEA-AD dataset?
[SEA-AD-text] How does the prevalence of clinically diagnosed dementia differ among donors with varying ADNC scores?
[SEA-AD-text] How does the presence and frequency of comorbid neuropathologies relate with ADNC scores?
[WMB-processed-text] Which subclass of glutamatergic neurons is most frequent in the RHP region?
[WMB-processed-text] What are the number of unique supertypes for the filtered class '19 MB Glut'?
[WMB-processed-text] What are the number of unique supertypes for the filtered class '24 MY Glut'?
[WMB-processed-text] What are the distribution (with cell numbers) of donor genotypes for the 'Glut' neurotransmitter class?
[WMB-raw-text] Which subclass of glutamatergic neurons is most frequent in the RHP region?
[WMB-raw-text] What are the number of unique supertypes for the filtered class '19 MB Glut'?
[WMB-raw-text] What are the number of unique supertypes for the filtered class '24 MY Glut'?
[WMB-raw-text] What are the distribution (with cell numbers) of donor genotypes for the 'Glut' neurotransmitter class?
[WMB-raw-no-traces] How many clusters contain no dark-phase transcriptomes in this dataset?
[WMB-raw-no-traces] How many neuronal clusters exhibit dual glutamate-GABA co-transmission in this dataset?
[WMB-raw-no-traces] What percentage of all the clusters express at least one neuropeptide gene?
[WMB-raw-no-traces] Of the dopaminergic clusters, what proportion also co-release another fast transmitter (GABA or Glutamate)?
[WMB-raw-no-traces] Of the 48 cholinergic clusters, how many co-release glutamate?
[WMB-raw-no-traces] Of the 48 cholinergic clusters, how many co-release GABA?
[WMB-raw-no-traces] Of the 48 cholinergic clusters, how many co-release glutamate + GABA?
[WMB-raw-no-traces] Of the 48 cholinergic clusters, how many co-release dopamine?
[WMB-raw-no-traces] How many clusters show significant sex-biased representation and across how many subclasses?
[WMB-raw-no-traces] How many clusters are completely sex-specific across males and females?

Total QA pairs: 25

## Convert to DataFrame

In [5]:
df = pd.DataFrame(records)
print(f'Total: {len(df)}')
print(f'\nBy category:')
print(df['category'].value_counts())
print(f'\nBy dataset:')
print(df['dataset'].value_counts())
df

Total: 25

By category:
category
data-analysis    18
knowledge         7
Name: count, dtype: int64

By dataset:
dataset
WMB-raw-no-traces     10
SEA-AD-text            7
WMB-processed-text     4
WMB-raw-text           4
Name: count, dtype: int64

,question,answer,category,dataset
0,How does the distribution of Braak stages chan...,"In this dataset, higher ADNC scores are observ...",knowledge,SEA-AD-text
1,How does the frequency of the APOE4 allele rel...,"In this dataset, APOE4 allele is observed to b...",knowledge,SEA-AD-text
2,How does the median age at death vary across h...,"In this dataset, individuals with high ADNC sc...",knowledge,SEA-AD-text
3,What is the relationship between Thal phases a...,"In this dataset, donors with higher ADNC score...",knowledge,SEA-AD-text
4,How do CERAD scores vary with different ADNC c...,"In this dataset, as ADNC scores increase, CERA...",knowledge,SEA-AD-text
5,How does the prevalence of clinically diagnose...,"In this dataset, donors with high ADNC scores ...",knowledge,SEA-AD-text
6,How does the presence and frequency of comorbi...,"In this dataset, higher ADNC scores are observ...",knowledge,SEA-AD-text
7,Which subclass of glutamatergic neurons is mos...,"In the RHP region, the subclass 019 L2/3 IT PP...",data-analysis,WMB-processed-text
8,What are the number of unique supertypes for t...,"In the observed data, class '19 MB Glut' inclu...",data-analysis,WMB-processed-text
9,What are the number of unique supertypes for t...,"In the observed data, '24 MY Glut' includes 76...",data-analysis,WMB-processed-text
10,What are the distribution (with cell numbers) ...,"In the observed data, 'Glut' neurotransmitter ...",data-analysis,WMB-processed-text
11,Which subclass of glutamatergic neurons is mos...,"In the RHP region, the subclass 019 L2/3 IT PP...",data-analysis,WMB-raw-text
12,What are the number of unique supertypes for t...,"In the observed data, class '19 MB Glut' inclu...",data-analysis,WMB-raw-text
13,What are the number of unique supertypes for t...,"In the observed data, '24 MY Glut' includes 76...",data-analysis,WMB-raw-text
14,What are the distribution (with cell numbers) ...,"In the observed data, 'Glut' neurotransmitter ...",data-analysis,WMB-raw-text
15,How many clusters contain no dark-phase transc...,62 neuronal clusters exhibit dual glutamate-GA...,data-analysis,WMB-raw-no-traces
16,How many neuronal clusters exhibit dual glutam...,335 clusters contain no dark-phase transcripto...,data-analysis,WMB-raw-no-traces
17,What percentage of all the clusters express at...,79 % of all clusters express at least one neur...,data-analysis,WMB-raw-no-traces
18,"Of the dopaminergic clusters, what proportion ...",35 of the dopaminergic clusters co-release ano...,data-analysis,WMB-raw-no-traces
19,"Of the 48 cholinergic clusters, how many co-re...",24 of the 48 cholinergic clusters co-release g...,data-analysis,WMB-raw-no-traces
20,"Of the 48 cholinergic clusters, how many co-re...",7 of the 48 cholinergic clusters co-release GABA.,data-analysis,WMB-raw-no-traces
21,"Of the 48 cholinergic clusters, how many co-re...",3 of the 48 cholinergic clusters co-release bo...,data-analysis,WMB-raw-no-traces
22,"Of the 48 cholinergic clusters, how many co-re...",1 of the 48 cholinergic clusters co-releases d...,data-analysis,WMB-raw-no-traces
23,How many clusters show significant sex-biased ...,26 clusters show significant sex-biased repres...,data-analysis,WMB-raw-no-traces
24,How many clusters are completely sex-specific ...,5 clusters are completely sex-specific.,data-analysis,WMB-raw-no-traces

## Inspect

In [6]:
print('=== Knowledge questions (RAG-suitable) ===')
for _, row in df[df['category'] == 'knowledge'].iterrows():
    print(f'\nQ: {row["question"]}')
    print(f'A: {row["answer"]}')

print('\n\n=== Data-analysis questions (require raw data) ===')
for _, row in df[df['category'] == 'data-analysis'].iterrows():
    print(f'\nQ: {row["question"]}')
    print(f'A: {row["answer"]}')

=== Knowledge questions (RAG-suitable) ===

Q: How does the distribution of Braak stages change across increasing ADNC categories?
A: In this dataset, higher ADNC scores are observed to be associated with higher Braak stages.

Q: How does the frequency of the APOE4 allele relate with increasing ADNC scores?
A: In this dataset, APOE4 allele is observed to be more frequent in donors with high ADNC compared to those with lower or no ADNC.

Q: How does the median age at death vary across high and low ADNC categories in the SEA-AD cohort?
A: In this dataset, individuals with high ADNC scores are observed to have a higher median age at death compared to those with low ADNC.

Q: What is the relationship between Thal phases and higher ADNC scores in the SEA-AD cohort?
A: In this dataset, donors with higher ADNC scores are observed to exhibit later Thal phases.

Q: How do CERAD scores vary with different ADNC categories in the SEA-AD dataset?
A: In this dataset, as ADNC scores increase, CERAD scores are observed to also rise.

Q: How does the prevalence of clinically diagnosed dementia differ among donors with varying ADNC scores?
A: In this dataset, donors with high ADNC scores are observed to be diagnosed with dementia prior to death in higher proportion relative to donors assigned other ADNC scores.

Q: How does the presence and frequency of comorbid neuropathologies relate with ADNC scores?
A: In this dataset, higher ADNC scores are observed to show a higher incidence of comorbid neuropathologies.


=== Data-analysis questions (require raw data) ===

Q: Which subclass of glutamatergic neurons is most frequent in the RHP region?
A: In the RHP region, the subclass 019 L2/3 IT PPP Glut is the most prevalent with 2,394 occurrences.

Q: What are the number of unique supertypes for the filtered class '19 MB Glut'?
A: In the observed data, class '19 MB Glut' includes 116 unique supertypes.

Q: What are the number of unique supertypes for the filtered class '24 MY Glut'?
A: In the observed data, '24 MY Glut' includes 76 unique supertypes.

Q: What are the distribution (with cell numbers) of donor genotypes for the 'Glut' neurotransmitter class?
A: In the observed data, 'Glut' neurotransmitter class shows the following genotype distribution: 194,986 cells with Snap25-IRES2-Cre/wt;Ai14(RCL-tdT)/wt, 8,229 cells with Ai14(RCL-tdT)/wt, 1,861 cells with Slc32a1-IRES-Cre/wt;Ai14(RCL-tdT)/wt, 223 cells with Gad2-IRES-Cre/wt;Ai14(RCL-tdT)/wt, and 65 cells with wt/wt.

Q: Which subclass of glutamatergic neurons is most frequent in the RHP region?
A: In the RHP region, the subclass 019 L2/3 IT PPP Glut is the most prevalent with 2,394 occurrences.

Q: What are the number of unique supertypes for the filtered class '19 MB Glut'?
A: In the observed data, class '19 MB Glut' includes 116 unique supertypes.

Q: What are the number of unique supertypes for the filtered class '24 MY Glut'?
A: In the observed data, '24 MY Glut' includes 76 unique supertypes.

Q: What are the distribution (with cell numbers) of donor genotypes for the 'Glut' neurotransmitter class?
A: In the observed data, 'Glut' neurotransmitter class shows the following genotype distribution: 194,986 cells with Snap25-IRES2-Cre/wt;Ai14(RCL-tdT)/wt, 8,229 cells with Ai14(RCL-tdT)/wt, 1,861 cells with Slc32a1-IRES-Cre/wt;Ai14(RCL-tdT)/wt, 223 cells with Gad2-IRES-Cre/wt;Ai14(RCL-tdT)/wt, and 65 cells with wt/wt.

Q: How many clusters contain no dark-phase transcriptomes in this dataset?
A: 62 neuronal clusters exhibit dual glutamate-GABA co-transmission.

Q: How many neuronal clusters exhibit dual glutamate-GABA co-transmission in this dataset?
A: 335 clusters contain no dark-phase transcriptomes.

Q: What percentage of all the clusters express at least one neuropeptide gene?
A: 79 % of all clusters express at least one neuropeptide gene.

Q: Of the dopaminergic clusters, what proportion also co-release another fast transmitter (GABA or Glutamate)?
A: 35 of the dopaminergic clusters co-release another fast transmitter.

Q: Of the 48 cholinergic clusters, how many co-release glutamate?
A: 24 of the 48 cholinergic clusters co-release glutamate.

Q: Of the 48 cholinergic clusters, how many co-release GABA?
A: 7 of the 48 cholinergic clusters co-release GABA.

Q: Of the 48 cholinergic clusters, how many co-release glutamate + GABA?
A: 3 of the 48 cholinergic clusters co-release both glutamate and GABA.

Q: Of the 48 cholinergic clusters, how many co-release dopamine?
A: 1 of the 48 cholinergic clusters co-releases dopamine.

Q: How many clusters show significant sex-biased representation and across how many subclasses?
A: 26 clusters show significant sex-biased representation.

Q: How many clusters are completely sex-specific across males and females?
A: 5 clusters are completely sex-specific.

## Save Data

In [7]:
df[['question', 'answer', 'category']].to_csv('neurodiscoverybench.csv', index=False)
print(f'Saved {len(df)} rows to neurodiscoverybench.csv')

Saved 25 rows to neurodiscoverybench.csv